### PR TITLE
[Auth] Restore MFA request setup to Firebase 10 behavior

### LINKED ISSUE #13856: Multi factor enrollment failing with internal error if `displayName` is `nil`
### Description

When [enrolling multi factor](https://firebase.google.com/docs/auth/ios/multi-factor#enrolling_a_second_factor), you call the following enroll method:

```swift
func enroll(
    with assertion: MultiFactorAssertion,
    displayName: String?
) async throws
```

The `displayName` property here is optional.

However, we've noticed after upgrading from 10.24.0 to 11.3.0 that the call errors with an internal error stating "Request contains an invalid argument" if `displayName` is `nil`.

If we set `displayName` to e.g. an empty string `""` instead, it works as expected.

### Reproducing the issue

```swift
let verificationId = ...
let verificationCode = ...

let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationId, verificationCode: verificationCode)
let assertion = PhoneMultiFactorGenerator.assertion(with: credential)

try await Auth.auth().currentUser?.multiFactor.enroll(with: assertion, displayName: nil) // (1)
try await Auth.auth().currentUser?.multiFactor.enroll(with: assertion, displayName: "") // (2)
```

- (1, `displayName: nil`) fails with internal error "Request contains an invalid argument."
- (2, `displayName: ""`) works as expected

### Firebase SDK Version

11.3.0

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Error Domain=FIRAuthErrorDomain Code=17999 "An internal error has occurred, print and inspect the error details for more information." UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSUnderlyingError=0x3005ac4e0 {Error Domain=FIRAuthInternalErrorDomain Code=3 "(null)" UserInfo={FIRAuthErrorUserInfoDeserializedResponseKey={
    code = 400;
    message = "Request contains an invalid argument.";
    status = "INVALID_ARGUMENT";
}, NSUnderlyingError=0x300594270 {Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data={length = 127, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}}}}, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information.}
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
Fix #13856

### CODE REVIEW

File: FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentRequest.swift [hunk 1]
```diff
@@ -64,11 +64,11 @@ class FinalizeMFAEnrollmentRequest: IdentityToolkitRequest, AuthRPCRequest {
...
-      if let phoneVerificationInfo {
-        body["phoneVerificationInfo"] = phoneVerificationInfo.dictionary
-      } else if let totpVerificationInfo {
-        body["totpVerificationInfo"] = totpVerificationInfo.dictionary
-      }
+    }
+    if let phoneVerificationInfo {
+      body["phoneVerificationInfo"] = phoneVerificationInfo.dictionary
+    } else if let totpVerificationInfo {
+      body["totpVerificationInfo"] = totpVerificationInfo.dictionary
```
Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/Backend/RPC/MultiFactor/Enroll/FinalizeMFAEnrollmentRequest.swift:71]: Compare this to Firebase 10 where Firebase 10 was always adding the phone/totp verification objects regardless if the display name was nil.

https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/Backend/RPC/MultiFactor/Enroll/FIRFinalizeMFAEnrollmentRequest.m#L62-L79

**Review by paulb777 — APPROVED** [review]
Good find! Thanks
