### PR TITLE
More safely manage background tasks

### LINKED ISSUE #3625: Error: Can't end BackgroundTask: no background task exists with identifier
### Environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.6.0

### Problem

A breakpoint fires and a console warning is shown:

```
Can't end BackgroundTask: no background task exists with identifier 344 (0x158), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
```

Zrzut ekranu 2019-08-19 o 10 07 31

#### Steps to reproduce:

I couldn't figure out the exact reproducible steps. It seems to happen quite a lot during development.

I suspect it is related to the way how `_backgroundID` is stored in `GDTCCTUploader`.

### PR DESCRIPTION
**Pull request by mikehaney24**
Also deletes a test that can't be run now.

Fixes #3625 

I believe there's still an issue on iOS 13 beta 5 on device, but I think it's an issue in iOS. I created a reduced test case, you see the entirety of the code and the warning below. The warning does not occur on a device that's iOS 12.

image

### CODE REVIEW

File: GoogleDataTransport/GDTLibrary/GDTStorage.m [hunk 1]
```diff
@@ -216,30 +221,28 @@ - (void)appWillForeground:(GDTApplication *)app {
...
-  }
-  dispatch_async(_storageQueue, ^{
-    if (@available(macOS 10.13, iOS 11.0, tvOS 11.0, *)) {
-      NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
-                                           requiringSecureCoding:YES
-                                                           error:nil];
-      [data writeToFile:[GDTStorage archivePath] atomically:YES];
-    } else {
+  self->_runningInBackground = YES;
+  if (@available(macOS 10.13, iOS 11.0, tvOS 11.0, *)) {
```
Comment (maksymmalyhin) [inline GoogleDataTransport/GDTLibrary/GDTStorage.m]: Was `dispatch_async(_storageQueue, ...)` removed here intentionally? May we bump in to a race condition here (line 116)

Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/GDTStorage.m]: No, unintentional, good catch.
