### PR TITLE
Defend against nil bundle identifiers

### LINKED ISSUE #3184: FindCertFileInResourceBundle crashes when [NSBundle bundleIdentifier] is nil
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.2.1
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
The problem occurs only when we enable log
`    [[FIRConfiguration sharedInstance] setLoggerLevel:FIRLoggerLevelDebug];
`

**Carthage**:
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"

#### Steps to reproduce:

The app crashes with the below log

```
#12. Crashed: com.google.firebase.firestore.GoogleService-Info-Ent-Develop
0  CoreFoundation                 0x10f85eeb9 CFStringGetLength + 9
1  Posski                         0x1060c6f37 firebase::firestore::util::MakeString(__CFString const*)
2  Posski                         0x10608826a firebase::firestore::remote::(anonymous namespace)::FindCertFileInResourceBundle(NSBundle*, NSBundle*)
3  Posski                         0x106087e04 firebase::firestore::remote::LoadGrpcRootCertificate()
4  Posski                         0x106085f07 firebase::firestore::remote::GrpcConnection::CreateChannel() const
5  Posski                         0x106085bb3 firebase::firestore::remote::GrpcConnection::EnsureActiveStub()
6  Posski                         0x1060863d9 firebase::firestore::remote::GrpcConnection::CreateStream(absl::string_view, firebase::firestore::auth::Token const&, firebase::firestore::remote::GrpcStreamObserver*)
7  Posski                         0x1060d5ee7 firebase::firestore::remote::WriteStream::CreateGrpcStream(firebase::firestore::remote::GrpcConnection*, firebase::firestore::auth::Token const&)
8  Posski                         0x1060c5a4c firebase::firestore::remote::Stream::ResumeStartWithCredentials(firebase::firestore::util::StatusOr<firebase::firestore::auth::Token> const&)
9  Posski                         0x1060c6b70 std::__1::__function::__func<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(firebase::firestore::util::StatusOr<firebase::firestore::auth::Token> const&) const::'lambda'(), std::__1::allocator<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(firebase::firestore::util::StatusOr<firebase::firestore::auth::Token> const&) const::'lambda'()>, void ()>::operator()()
10 Posski                         0x105ff12a0 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&)
11 Posski                         0x1060046f8 firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*)
12 libdispatch.dylib              0x11036554b _dispatch_client_callout + 8
13 libdispatch.dylib              0x11036c01c _dispatch_lane_serial_drain + 720
14 libdispatch.dylib              0x11036cb5f _dispatch_lane_invoke + 401
15 libdispatch.dylib              0x1103759a8 _dispatch_workloop_worker_thread + 645
16 libsystem_pthread.dylib        0x110741611 _pthread_wqthread + 421
17 libsystem_pthread.dylib        0x1107413fd start_wqthread + 13
18 (Missing)                      0x12ab2bc58 (Missing)

```

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

### PR DESCRIPTION
**Pull request by wilhuff**
This fixes #3184, where under some circumstances some bundles have no
CFBundleIdentifier in their Info.plist.

### CODE REVIEW

File: Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm [hunk 1]
```diff
@@ -37,6 +37,18 @@
 
 namespace {
 
+std::string DebugBundleIdentifier(NSBundle* bundle) {
```
Comment (schmidt-sebastian) [inline Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm]: Mark _Nullable?

File: Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm [hunk 2]
```diff
@@ -37,6 +37,18 @@
...
+  if (!bundle) return "(nil bundle)";
+
+  NSString* identifier = [bundle bundleIdentifier];
+  if (!identifier) {
```
Comment (schmidt-sebastian) [inline Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm]: Since this is still Objective-C, this function could be:

```
NSString* identifier = [bundle bundleIdentifier];
identifier = [bundle bundlePath];
return identifier ? util::MakeString(identifier) : "(missing bundle identifier)";
```

Your version is much more explicit, though, and you can leave it as is.

File: Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm (hunk 1 above)
Comment (wilhuff) [reply Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm]: Done.

File: Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm (hunk 2 above)
Comment (wilhuff) [reply Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm]: The second line of your suggestion doesn't work since we only want to do that if the `-bundleIdentifier` returned `nil`.

In general I'm not in favor of relying on nil dispatch. It's too easy to accidentally do when it's not intended and when reading code later it's hard to understand if it's intended or not. It also hides the conditional behavior in a way that's easy to overlook.

I did make the final line the ternary though.
