### PR TITLE
Block calls to get config until DB load completes

### LINKED ISSUE #7424: [Remote Config] Local conf randomly empty even with successful fetch
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component: RemoteConfig

### [REQUIRED] Step 2: Describe the problem
We use the 3rd loading strategy (Load new values for next startup) as described here https://firebase.google.com/docs/remote-config/loading
Our application fetches the required configuration on the splash screen.

On the first launch, this fetch succeed and the app behaves normally.
For some reason, on other launch the local configuration sometimes returns empty values.
The Firebase app is configured and the logs doesn't identify any issue even if set to max.

**The problem isn't easily reproducible on all devices, but some of them are failing almost 1 on 3 times.**

We Unfortunately couldn't narrow the devices concerned, neither the OS concerned.

When the content is empty :
- The last fetch status is `succeed`
- `defaultExpiration: TimeInterval = 600`

- When we print the value of :

RemoteConfig.remoteConfig().allKeys(from: .remote)
RemoteConfig.remoteConfig().allKeys(from: .static)
RemoteConfig.remoteConfig().allKeys(from: .default)

It returns 0 (no key was found)

#### Steps to reproduce:

Please find below the link to the sample where you can reproduce : 

https://drive.google.com/file/d/1LG4fbE4FCW4Ts61vGgvzQLUW0l6jSH4s/view?usp=sharing

To reproduce, simply install the sample, kill & launch it multiple times. Once the background is red, it means that the local conf is empty.

### PR DESCRIPTION
**Pull request by karenyz**
`_configLoadFromDBSemaphore = dispatch_semaphore_create(1)` causes the later `dispatch_semaphore_wait` call in `checkAndWaitForInitialDatabaseLoad()` to never be blocked, so it's possible to return a config before we finish loading from the DB.

Removing `dispatch_semaphore_signal` from `loadPersonalization` as its success/failure should not impact RC returning a config

fixes #7424

### CODE REVIEW

File: FirebaseRemoteConfig/Sources/RCNConfigContent.m [hunk 1]
```diff
@@ -128,7 +127,6 @@ - (void)loadConfigFromMainTable {
                   NSDictionary *activePersonalization, NSDictionary *defaultConfig) {
     self->_fetchedPersonalization = [fetchedPersonalization copy];
     self->_activePersonalization = [activePersonalization copy];
```
Comment (chliangGoogle) [inline FirebaseRemoteConfig/Sources/RCNConfigContent.m:129]: Since we only have one dispatch_semaphore_signal blocking inside `[DBManager loadMainWithBundleIdentifier:]` to block the read, should we move this `[DBManager loadPersonalizationWithCompletionHandler:]` inside `[DBManager loadMainWithBundleIdentifier:]` as well?

**Review by chliangGoogle — CHANGES_REQUESTED** [review]

**Review by paulb777 — COMMENTED** [review]
Is this also a fix for #7648?

File: FirebaseRemoteConfig/Sources/RCNConfigContent.m (hunk 1 above)
Comment (karenyz) [reply FirebaseRemoteConfig/Sources/RCNConfigContent.m:129]: Feels a bit weird to chain calls to `DBManager` and add extra latency, especially since the personalization data is separate from the RC template and isn't returned as part of the config.

I think we could refactor `[DBManager loadMainWithBundleIdentifier:]` to return personalization data along with the config (in one call), but that's a larger change and we can tackle it as a follow up. The current change will fix the reported issue, and doesn't change current personalization behavior (we already aren't blocking)

Comment (chliangGoogle) [reply FirebaseRemoteConfig/Sources/RCNConfigContent.m:129]: my concern is if developers try to read fetchedPersonalization then it might not be ready. I'm not familiar with personalization for but if we are okay that they might not be fully loaded when developers trying to read configs, i'm okay give it good to go.

Comment (chliangGoogle) [reply FirebaseRemoteConfig/Sources/RCNConfigContent.m:129]: Can you add a todo here on refactor?

**Review by chliangGoogle — APPROVED** [review]

File: FirebaseRemoteConfig/Sources/RCNConfigContent.m (hunk 1 above)
Comment (danasilver) [reply FirebaseRemoteConfig/Sources/RCNConfigContent.m:129]: Developers don't read the `fetchedPersonalization`s so it should be okay if they're not loaded when developers try to read configs. They're used to report personalization signals to GA when a personalized parameter (stored in the config that's read above and waited on) is read. More signals improve the personalizations but some missed signals don't break the system.

**Review by danasilver — APPROVED** [review]

File: FirebaseRemoteConfig/Sources/RCNConfigContent.m (hunk 1 above)
Comment (karenyz) [reply FirebaseRemoteConfig/Sources/RCNConfigContent.m:130]: added a TODO for the personalization refactor

**Review by chliangGoogle — APPROVED** [review]

**Review by paulb777 — APPROVED** [review]
