### PR TITLE
Fix RTDB crash from race

### LINKED ISSUE #9096: Intermittent crash in FUtilities.intForString
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0
  * Firebase SDK version:8.9.1
  * Installation method: `Swift Package Manager` 
  * Firebase Component: Database
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem
- It appeared when we started using the SDK as dependency of one of our SPM package, before, we were using cocoapods and it was fine.
- FirebaseDatabase entities get mapped when app is launched and it intermittently crashes in `FUtilities.intForString`

#### Steps to reproduce:
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
- Happens when we launch the app since we starting mapping entities immediately
- Attached (crashlog.txt) is the crash report

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
+ (NSNumber *)intForString:(NSString *)string {
    static NSCharacterSet *notDigits = nil;
    if (!notDigits) {
        notDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
    }
    if ([string rangeOfCharacterFromSet:notDigits].length == 0) {
        NSInteger num;
        NSScanner *scanner = [NSScanner scannerWithString:string];
        if ([scanner scanInteger:&num]) {
            return [NSNumber numberWithInteger:num];
        }
    }
    return nil;
}

```
Screen Shot 2021-12-14 at 11 11 55 AM
[crashlog.txt](https://github.com/firebase/firebase-ios-sdk/files/7708426/crashlog.txt)

### PR DESCRIPTION
**Pull request by paulb777**
Fix #9096

### CODE REVIEW

File: FirebaseDatabase/Sources/Utilities/FUtilities.m [hunk 1]
```diff
@@ -295,10 +295,11 @@ + (NSError *)errorForStatus:(NSString *)status andReason:(NSString *)reason {
...
 + (NSNumber *)intForString:(NSString *)string {
-    static NSCharacterSet *notDigits = nil;
-    if (!notDigits) {
-        notDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
-    }
+    static dispatch_once_t once;
+    static NSCharacterSet *notDigits;
+    dispatch_once(&once, ^{
+      notDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
+    });
```
Comment (ncooke3) [inline FirebaseDatabase/Sources/Utilities/FUtilities.m:302]: Curious, what is the reason we want to assign the `notDigits` just once? Is it expensive to `[[NSCharacterSet decimalDigitCharacterSet] invertedSet]`?

Comment (paulb777) [reply FirebaseDatabase/Sources/Utilities/FUtilities.m:302]: I was focused on correcting the existing implementation - but presumably it is converting a operation processing the Unicode character set to a cached value which could add up if this function is called a lot. cc: @schmidt-sebastian

Comment (ncooke3) [reply FirebaseDatabase/Sources/Utilities/FUtilities.m:302]: Gotcha, interesting, makes sense. Nice fix!

**Review by schmidt-sebastian — APPROVED** [review]
