### PR TITLE
Fix Resource generation for Carthage xcframeworks

### LINKED ISSUE #8112: Firestore Carthage installation is missing gRPC-C++ in 8.0.0
Opened to track issue raised at https://github.com/firebase/firebase-ios-sdk/issues/7576#issuecomment-843774872

### PR DESCRIPTION
**Pull request by paulb777**
Fix #8112 

Carthage resources should remain in each `.framework` instead of at the root of `.xcframework`s.

After all xcframework resources are processed and stored at the root of the .xcframework at https://github.com/firebase/firebase-ios-sdk/blob/master/ReleaseTooling/Sources/ZipBuilder/FrameworkBuilder.swift#L697, the new code consolidates both Zip Distro and Carthage resource processing in ZipBuilder.swift. 

It still remains for the future to handle platform-specific Resources.

Successful test at https://github.com/firebase/firebase-ios-sdk/actions/runs/903575515.
I verified the Zip in the artifact matches the 8.1.0 release. The only exception is GoogleSignIn Resources are now in the framework.  See comments for more discussion about GoogleSignIn.  I also verified that the Firestore, GoogleSignIn, and FIAM Carthage zips successfully install on `carthage update` including the xcframeworks that were not installing because of the Resources location.

### CODE REVIEW

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift [hunk 1]
```diff
@@ -452,28 +453,76 @@ struct ZipBuilder {
                                        rootZipDir: zipDir,
                                        builtFrameworks: frameworksToAssemble,
                                        podsToIgnore: analyticsPods)
-
         // Update the README.
         readmeDeps += dependencyString(for: pod.key, in: productDir, frameworks: podFrameworks)
-
-        // Special case for Crashlytics:
```
Comment (paulb777) [inline ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:459]: The Crashlytics code is only reindented and shows up in green below.

File: ReleaseTooling/Sources/ZipBuilder/FirebaseBuilder.swift [hunk 2]
```diff
@@ -46,24 +46,6 @@ struct FirebaseBuilder {
         options: carthageBuildOptions
       )
 
-      // Prepare the release directory for zip packaging.
```
Comment (paulb777) [inline ReleaseTooling/Sources/ZipBuilder/FirebaseBuilder.swift:49]: This chunk is migrated to the `if packageKind == "Firebase" {` code below.

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift [hunk 3]
```diff
@@ -452,28 +453,76 @@ struct ZipBuilder {
...
+          guard fileManager.isDirectory(at: xcPath),
+            xcPath.lastPathComponent.hasSuffix("xcframework"),
+            fileManager.directoryExists(at: xcResourceDir)
+          else { continue }
+
+          if packageKind == "Firebase" {
+            // Move all the bundles in the frameworks out to a common "Resources" directory to
+            // match the existing Zip structure.
+            let resourcesDir = productPath.appendingPathComponent("Resources")
+            try fileManager.moveItem(at: xcResourceDir, to: resourcesDir)
```
Comment (paulb777) [inline ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:483]: moveItem instead of `ResourcesManager.moveAllBundles` since the resources were already processed when the xcframework was created.

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift [hunk 4]
```diff
@@ -452,28 +453,76 @@ struct ZipBuilder {
...
-              fatalError("Error copying Crashlytics tools from \(source) to \(target): \(error)")
+      } catch {
+        fatalError("Could not copy frameworks from \(pod) into the zip file: \(error)")
+      }
+      do {
+        // Update Resources: For the zip distribution, they get pulled from the xcframework to the
+        // top-level product directory. For the Carthage distribution, they propagate to each
+        // individual framework.
+        // TODO: Investigate changing the zip distro to also have Resources in the .frameworks to
+        // enable different platform Resources.
```
Comment (ryanwilson) [inline ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:466]: I thought there was an issue in having them embedded in the frameworks but I can't remember, maybe it was an older Xcode version and latest versions would be fine.

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift [hunk 5]
```diff
@@ -452,28 +453,76 @@ struct ZipBuilder {
...
+            xcPath.lastPathComponent.hasSuffix("xcframework"),
+            fileManager.directoryExists(at: xcResourceDir)
+          else { continue }
+
+          if packageKind == "Firebase" {
+            // Move all the bundles in the frameworks out to a common "Resources" directory to
+            // match the existing Zip structure.
+            let resourcesDir = productPath.appendingPathComponent("Resources")
+            try fileManager.moveItem(at: xcResourceDir, to: resourcesDir)
+
```
Comment (ryanwilson) [inline ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:484]: Nit: extra blank line.

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift [hunk 6]
```diff
@@ -452,28 +453,76 @@ struct ZipBuilder {
...
+          } else {
+            let xcContents = try fileManager.contentsOfDirectory(atPath: xcPath.path)
+            for fileOrFolder in xcContents {
+              let platformPath = xcPath.appendingPathComponent(fileOrFolder)
+              guard fileManager.isDirectory(at: platformPath)
+              else { continue }
```
Comment (ryanwilson) [inline ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:490]: This could probably be on a single line

**Review by ryanwilson — APPROVED** [review]
Thanks for the comments, they helped a bunch!

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift (hunk 4 above)
Comment (paulb777) [reply ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:466]: We might have had another issue in the past, like an invalid Info.plist. My testing shows it to be fine now.

File: ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift (hunk 6 above)
Comment (paulb777) [reply ReleaseTooling/Sources/ZipBuilder/ZipBuilder.swift:490]: Addressing in next commit

**Review by paulb777 — COMMENTED** [review]
Tests look good. Will fix spaces review commit and summarize testing in PR intro, and then merge

**Comment by paulb777** [comment]
There is an issue with blaze created frameworks 😞
```
~/test-8082/Firebase-actions-dir/carthage/8.1.0/GoogleSignIn  $ swift
Welcome to Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55).
Type :help for assistance.
  1> import Foundation
  2> Bundle(path: "GoogleSignIn.framework")!.infoDictionary
$R0: [String : Any]? = 0 key/value pairs
```
The one diff in the generated zip is the GoogleSignIn resources aren't being moved out of the framework any longer.  I'll restore so that the zip is unchanged.

**Comment by paulb777** [comment]
On additional investigation, the Carthage GoogleSignIn.framework is the same structure it has always been. It turns out that Carthage needs to be able to process Info.plist's for `.xcframework`s , but not for `.framework`s.  Given that GoogleSignIn will soon move to `.xcframework`s and issues like #8154, I'll merge as is.
