### PR TITLE
Fix app_start trace not firing in SwiftUI apps using @UIApplicationDelegateAdaptor (#15802)

### LINKED ISSUE #15802: Firebase Performance app_start not firing in SwiftUI apps
### Description

Firebase Performance `app_start` does not fire in SwiftUI apps using `@UIApplicationDelegateAdaptor` because launch state is checked too early. In SwiftUI lifecycle apps (@main App + @UIApplicationDelegateAdaptor), didFinishLaunchingWithOptions can execute before any foreground scene is active, and applicationState can still report .background at that moment.

Firebase Performance checks `state == UIApplicationStateBackground` during `didFinishLaunchingWithOptions` notification handling, and incorrectly classify normal foreground launches as background launches and invalidates app_start. In SwiftUI apps, this callback is a poor place to determine whether launch was truly background

### Reproducing the issue

- Create a new SwiftUI iOS app., disabled swizzling in Info.plist
- Add Firebase Core + Firebase Performance.
- Configure Firebase in application(_:didFinishLaunchingWithOptions:) via @UIApplicationDelegateAdaptor.
- Launch app normally from Xcode (foreground launch).
- Observe debug logging and/or Performance traces in Firebase console 
"12.8.0 - [FirebasePerformance][I-PRF200007] Background launch detected. App start measurement will be skipped."

### Firebase SDK Version

12.8.0

### Xcode Version

26.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
"12.8.0 - [FirebasePerformance][I-PRF200007] Background launch detected. App start measurement will be skipped."
```

### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

### PR DESCRIPTION
**Pull request by JesusRojass**
## Description

Fixes #15802 

SwiftUI apps using `@UIApplicationDelegateAdaptor` report `applicationState` as `.background` during `didFinishLaunchingWithOptions` even on normal foreground launches, because scenes haven't connected yet. This caused the `_as` (app start) trace to be incorrectly skipped.

## Changes

Defer the background launch decision from `didFinishLaunching` to `didBecomeActive`. Record `sLaunchedInBackgroundState` at launch time and use the existing 60-minute threshold (`gAppStartMaxValidDuration`) to distinguish genuine background launches from SwiftUI's false `.background` report.

## Testing

Verified with a SwiftUI test app using `@UIApplicationDelegateAdaptor`:
- Foreground launch: `_as` trace fires correctly (~580ms)
- Background fetch launch: no trace created (correct)
- Existing prewarm and duration-threshold logic unchanged

### API Changes

  * No API changes

### CODE REVIEW

**Comment by JesusRojass** [comment]
Ready for review @visumickey 😄 💯

File: FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m [hunk 1]
```diff
@@ -259,15 +256,25 @@ - (void)appDidBecomeActiveNotification:(NSNotification *)notification {
...
-                  @"App start trace skipped due to background launch. "
-                  @"This prevents reporting incorrect multi-minute/hour durations.");
+      FPRLogDebug(kFPRTraceNotCreated, @"App start trace skipped due to background launch.");
       return;
     }
 
+    // Distinguish genuine background launches by checking how long ago +load captured appStartTime.
+    // A real foreground launch reaches didBecomeActive within seconds; a background launch that is
+    // later opened by the user will have a much larger gap.
+    if (sLaunchedInBackgroundState) {
```
Comment (visumickey) [inline FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m]: Worried about a scenario where a non-switftUI app starts itself in background, but the app gets launched before the max app start duration value - this code would account for that app start time.

I think the ideal would be differentiate if this is a SwiftUI app and make some exceptions rather than impacting all the scenarios.

Comment (JesusRojass) [reply FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m]: I have added a commit that checks for UIApplicationSceneManifest in the info.plist before deferring to keep the original behavior in the rest of the escenarios 

LMK what you think 😄

**Comment by JesusRojass** [comment]
Comment addressed! 

LMK what you think @visumickey 😄

**Comment by JesusRojass** [comment]
thanks @ncooke3 
added!

File: FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m [hunk 2]
```diff
@@ -118,15 +119,18 @@ + (void)windowDidBecomeVisible:(NSNotification *)notification {
...
-  // Detect a background launch and invalidate app start time
-  // this prevents we measure duration from background launch
   UIApplicationState state = [UIApplication sharedApplication].applicationState;
   if (state == UIApplicationStateBackground) {
-    // App launched in background so we invalidate the captured app start time
-    // to prevent incorrect measurement when user later opens the app
-    appStartTime = nil;
-    FPRLogDebug(kFPRTraceNotCreated,
-                @"Background launch detected. App start measurement will be skipped.");
+    NSDictionary *sceneManifest =
```
Comment (visumickey) [inline FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m:127]: Let's add a comment above referring what does this check means?

File: FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m [hunk 3]
```diff
@@ -259,15 +263,25 @@ - (void)appDidBecomeActiveNotification:(NSNotification *)notification {
...
-                  @"App start trace skipped due to background launch. "
-                  @"This prevents reporting incorrect multi-minute/hour durations.");
+      FPRLogDebug(kFPRTraceNotCreated, @"App start trace skipped due to background launch.");
       return;
     }
 
+    // Distinguish genuine background launches by checking how long ago +load captured appStartTime.
+    // A real foreground launch reaches didBecomeActive within seconds; a background launch that is
+    // later opened by the user will have a much larger gap.
+    if (sLaunchedInBackgroundState) {
```
Comment (visumickey) [inline FirebasePerformance/Sources/AppActivity/FPRAppActivityTracker.m]: Should this check include both the background launch and a sceneManifest? that way, we are trying to be narrow about a specific scenario we want to allow list for.

**Comment by JesusRojass** [comment]
@visumickey I've added the comment and included both cases in the check!

lmk if anything else is needed!
