### PR TITLE
[App Check] Fix JSON key ordering in `HeartbeatsPayload`

### LINKED ISSUE #11406: Heartbeat Logging unit test failure in Xcode 15
### Description

The `testRequest_IncludesHeartbeatPayload_WhenHeartbeatsNeedSending` test fails in Xcode 15.

### Reproducing the issue

Run the Auth unit tests on Xcode 15

### Firebase SDK Version

10.11

### Xcode Version

15.0-beta1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by andrewheard**
Key ordering from `JSONEncoder` is not guaranteed, resulting in test failures when output is compared directly (e.g., [`testDataRequestSuccessWhenHeartbeatsNeedSending`](https://github.com/firebase/firebase-ios-sdk/blob/f0378e9f9ea5d2d131b75d8745c778468b9b2118/FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m#L125-L135) and [`testRequest_IncludesHeartbeatPayload_WhenHeartbeatsNeedSending`](https://github.com/firebase/firebase-ios-sdk/blob/f0378e9f9ea5d2d131b75d8745c778468b9b2118/FirebaseAuth/Tests/Unit/FIRAuthBackendRPCImplementationTests.m#L421-L448)).

Added the `sortedKeys` output formatting option in debug builds to fix non-deterministic test results while avoiding unnecessary sorting costs in release builds. This resolves #11406 in local testing.

#no-changelog

### CODE REVIEW

**Review by ncooke3 — APPROVED** [review]
Nice! LGTM on green.

File: FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift [hunk 1]
```diff
@@ -91,6 +91,12 @@ extension HeartbeatsPayload: HTTPHeaderRepresentable {
   public func headerValue() -> String {
     let encoder = JSONEncoder()
     encoder.dateEncodingStrategy = .formatted(Self.dateFormatter)
+    #if DEBUG
+      if #available(iOS 11, *) {
```
Comment (andrewheard) [inline FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift:95]: Note: [`sortedKeys`](https://developer.apple.com/documentation/foundation/jsonencoder/outputformatting/2919670-sortedkeys) is only available on iOS 11.0+, macOS 10.13+, tvOS 11.0+, watchOS 4.0+, visionOS 1.0+. [`FirebaseCoreInternal`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCoreInternal.podspec#L21-L24) is already macOS 10.13+, tvOS 12.0+, watchOS 6.0+ so I just specified `iOS 11` in the availability check and let the rest fall through with `*`.

Comment (andrewheard) [reply FirebaseCore/Internal/Sources/HeartbeatLogging/HeartbeatsPayload.swift:97]: Added a TODO to remind us to remove the `if #available` check when we increase our deployment target to iOS 11+.
