### PR TITLE
FIRInstanceIDKeyPairStore crash fix 

### LINKED ISSUE #2731: Crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS [FIRInstanceIDKeyPairStore updateKeyRef:withTag:handler:]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.19.0
  * Firebase Component: FirebaseInstanceID
  * Component version: 3.8.0

### [REQUIRED] Step 3: Describe the problem

stack trace:
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1bc9d8d7c objc_msgSend + 28
1  CoreFoundation                 0x1bd6dd6d0 +[__NSDictionaryI __new::::::] + 376
2  CoreFoundation                 0x1bd6e03b4 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 64
3  Catawiki                       0x1012754cc __58-[FIRInstanceIDKeyPairStore updateKeyRef:withTag:handler:]_block_invoke (FIRInstanceIDKeyPairStore.m:416)
4  libdispatch.dylib              0x1bd2296c8 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x1bd22a484 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1bd1d69a4 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
7  CoreFoundation                 0x1bd781ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
8  CoreFoundation                 0x1bd77cbac __CFRunLoopRun + 1964
9  CoreFoundation                 0x1bd77c0e0 CFRunLoopRunSpecific + 436
10 GraphicsServices               0x1bf9f5584 GSEventRunModal + 100
11 UIKitCore                      0x1ea708c00 UIApplicationMain + 212
12 Catawiki                       0x100e78b20 main (main.swift:6)
13 libdyld.dylib                  0x1bd23abb4 start + 4
```

Also I've seen a lot of crash and error reports in Firebase Crashlytics that are missing data in the "logs" tab.

#### Steps to reproduce:

Haven't been able to reproduce locally, but this started happening on quite large scale in production in our latest version (+700 users affected). In this release we updated from Firebase 5.10 (FirebaseInstanceID 3.2.2), and at the same time adding custom screen tagging (see code below).

Looking at the relevant code in FIRInstanceIDKeyPairStore line 416, it looks like an issue handling backwards compatibility?

#### Relevant Code:

```swift
func setScreenName(_ screenName: String?, screenClass: String?) {
        Firebase.Analytics.setScreenName(screenName, screenClass: screenClass)
}
```

Not sure the latter is related to the crash..

--EDIT--
Couple of days later, it seems that the occurrence of the crash is slowing down rapidly (no change on the client side), which seems likely to me if the issue was indeed backwards compatibility/migration:

Screenshot 2019-04-08 at 10 41 11

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #2731

### CODE REVIEW

**Comment by maksymmalyhin** [comment]
The actual crash happens because `SecKeyRef` gets deallocated by the time it is added to the `NSDictionary`. 

The direct fix of the crash is to retain/release `SecKeyRef`.

The reason why the `SecKeyRef` gets deallocated, as far as I can see, is a race condition between migration and deleting a key pair. I am not sure as for the exact combination of events yet. As a simple and reliable way to fix  I consider using an internal dispatch queue for `FIRInstanceIDKeyPairStore` to protect public methods from race conditions.

@chliangGoogle  WDYT?

**Comment by chliangGoogle** [comment]
What you have now is how I would fix it. Feels like SecKeyRef is deallocated in the callback of removeItemWithQuery:.
I wonder if we make a copy of SecKeyRef, would it be good enough?

**Comment by maksymmalyhin** [comment]
@chliangGoogle My concern is following. The `SecKeyRef` supposed to be retain by [self.keyPair](https://github.com/firebase/firebase-ios-sdk/blob/25ded962e337c06dd9dc48f57b0393eba5bd1c25/Firebase/InstanceID/FIRInstanceIDKeyPairStore.m#L365), so if it gets deallocated by the callback then `self.keyPair` was assigned with a different key pair. In this case we may end up with an inconsistent state of keychain which may lead to unpleasant issues with the Instance ID.

I wonder, if you have an idea why `self.keyPair` may be assigned with a different key pair during the migration operation?

**Comment by chliangGoogle** [comment]
It is possible self.keyPair could be deallocated like [here](https://github.com/firebase/firebase-ios-sdk/blob/25ded962e337c06dd9dc48f57b0393eba5bd1c25/Firebase/InstanceID/FIRInstanceIDKeyPairStore.m#L478). This is called by invalidateKeyPairsIfNeeded during app start, but it is called before the migration happens.

This is to delete old keychain data if a plist file is not found (meaning it is a fresh install).

I wonder a serial queue would guarantee this succeeds or if we can ensure certain actions are called in order (like nullify self.keypair right away without waiting for the keychain async operation is done)

**Comment by maksymmalyhin** [comment]
I am thinking of using the queue to make sure the operations are performed in the order they were called by the class client. The downside of this is that a next operation will not be performed until previous finished. From the other side, the implementation will be easier and less affected by different edge cases. 

If that sounds good, I’ll post a draft version of it so we can discuss it in more details.

File: Firebase/InstanceID/FIRInstanceIDKeyPairStore.m [hunk 1]
```diff
@@ -365,31 +365,43 @@ - (void)migrateKeyPairCacheIfNeededWithHandler:(void (^)(NSError *error))handler
   self.keyPair = keyPair;
 
   // Either new key pair doesn't exist or it's different than legacy key pair, start the migration.
+
+  // Use a dispatch group to call handler when both private and public keys are updated.
+  dispatch_group_t dispatchGroup = dispatch_group_create();
```
Comment (chliangGoogle) [inline Firebase/InstanceID/FIRInstanceIDKeyPairStore.m]: Not sure if this is needed since the local variable keypair is already atomic and the keychain operations are guarded by a serial queue already.

Comment (maksymmalyhin) [reply Firebase/InstanceID/FIRInstanceIDKeyPairStore.m]: Yeah, probably we may call handler from the 2nd keychain handler. It's a bit implicit,  though we already rely on the `FIRInstanceIDKeychain` implementation managed by a serial queue, so, I'll remove dispatch groups.

File: Firebase/InstanceID/FIRInstanceIDKeyPairStore.m [hunk 2]
```diff
@@ -365,31 +365,43 @@ - (void)migrateKeyPairCacheIfNeededWithHandler:(void (^)(NSError *error))handler
...
-                                @"Successfully migrated the key pair from legacy ones.");
-                            if (handler) {
-                              handler(error);
-                            }
-                          }];
+               dispatch_group_leave(dispatchGroup);
+             }];
+
+  dispatch_group_enter(dispatchGroup);
+  [self updateKeyRef:keyPair.privateKey
```
Comment (chliangGoogle) [inline Firebase/InstanceID/FIRInstanceIDKeyPairStore.m]: Can we also check the nil in updateKeyRef just in case.

Comment (maksymmalyhin) [reply Firebase/InstanceID/FIRInstanceIDKeyPairStore.m]: I think, it is already checked by `[keyPair isValid]` at line 346. Do you think we need to check it here again?

Comment (chliangGoogle) [reply Firebase/InstanceID/FIRInstanceIDKeyPairStore.m]: I guess it's fine now that you move the function out of the async class.
