### PR TITLE
Verify block is still alive before calling it in task callbacks

### LINKED ISSUE #7051: EXC_BAD_ACCESS (KERN_INVALID_ADDRESS) with FIRStorageDownloadTask
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 7.1.0
  * Installation method: CocoaPods
  * Firebase Component: Storage

### [REQUIRED] Step 2: Describe the problem

Upon completion of downloadTasks, the APP crash sometimes.
The same crash bug was discussed before in this [issue](https://github.com/firebase/firebase-ios-sdk/issues/3750). But it only fixed for UploadTask, why not for DownloadTask and others?

Crash log:

```
Crashed: com.apple.main-thread
0  FirebaseStorage                0x1022ae7a8 __42-[FIRStorageDownloadTask enqueueWithData:]_block_invoke.93 + 144 (FIRStorageDownloadTask.m:144)
1  GTMSessionFetcher              0x1023fad14 __71-[GTMSessionFetcher invokeFetchCallbacksOnCallbackQueueWithData:error:]_block_invoke + 2512 (GTMSessionFetcher.m:2512)
2  libdispatch.dylib              0x18649724c _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x186498db0 _dispatch_client_callout + 20
4  libdispatch.dylib              0x1864a6800 _dispatch_main_queue_callback_4CF + 920
5  CoreFoundation                 0x18682011c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
6  CoreFoundation                 0x18681a120 __CFRunLoopRun + 2508
7  CoreFoundation                 0x18681921c CFRunLoopRunSpecific + 600
8  GraphicsServices               0x19d898784 GSEventRunModal + 164
9  UIKitCore                      0x189252200 -[UIApplication _run] + 1072
10 UIKitCore                      0x189257a74 UIApplicationMain + 168
11 ShotCut                        0x100f7e870 main + 25 (ATTemplateEditVC.swift:25)
12 libdyld.dylib                  0x1864d96c0 start + 4
```

#### Steps to reproduce:

Refer to [this](https://github.com/firebase/firebase-ios-sdk/issues/3750#issuecomment-528550777).

### PR DESCRIPTION
**Pull request by paulb777**
Fix #7051 

General case follow up to #3786

### CODE REVIEW

**Review by schmidt-sebastian — APPROVED** [review]

File: FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m [hunk 1]
```diff
@@ -94,12 +92,13 @@ - (void)enqueue {
       }
       self->_fetcherCompletion = nil;
```
Comment (maksymmalyhin) [inline FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m:93]: Mostly curious, why the retain cycle is needed here? A comment on it would be useful to avoid such questions in the future.

Comment (paulb777) [reply FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m:93]: Maybe to avoid multiple calls? I'm not sure, but either way, it seems outside the scope of this PR.

Comment (maksymmalyhin) [reply FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m:93]: sure! You just removed the warning suppression so I thought you know why it's actually needed :)

Comment (paulb777) [reply FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.m:93]: I removed the warning suppression because the warning suppression isn't needed :). Warnings don't get generated.

File: FirebaseStorage/Sources/FIRStorageDeleteTask.m [hunk 2]
```diff
@@ -72,10 +70,11 @@ - (void)enqueue {
       }
       self->_fetcherCompletion = nil;
     };
-#pragma clang diangostic pop
 
     [fetcher beginFetchWithCompletionHandler:^(NSData *_Nullable data, NSError *_Nullable error) {
-      weakSelf.fetcherCompletion(data, error);
+      if (weakSelf.fetcherCompletion != nil) {
```
Comment (wilhuff) [inline FirebaseStorage/Sources/FIRStorageDeleteTask.m:75]: This is unsafe--the object can be deallocated while the method is in progress. Calling a method does not retain self. You need to assign from weakSelf to a (new) strong reference and then check if that strong reference is nil.

**Comment by paulb777** [comment]
Thanks @wilhuff
