### PR TITLE
Fix a few misuse of OCMock in Messaging and InstanceID

### LINKED ISSUE #4345: Fix Messaging test failures with OCMock 3.5.0
From https://travis-ci.org/firebase/firebase-ios-sdk/jobs/613701583:

    - NOTE  | [iOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/Example/Messaging/Tests/FIRMessagingConnectionTest.m:210: error: -[FIRMessagingConnectionTest testLoginRequest] : failed: caught "NSInternalInconsistencyException", "Mock object was not used in OCMVerify. Did you accidentally use a real object?"

### PR DESCRIPTION
**Pull request by chliangGoogle**
This fixes #4345, #4347.

### CODE REVIEW

File: Example/InstanceID/Tests/FIRInstanceIDTest.m [hunk 1]
```diff
@@ -578,8 +578,9 @@ - (void)testDefaultToken_noCachedToken {
 
   OCMExpect([self.mockInstanceID defaultTokenWithHandler:nil]);
   XCTAssertNil([self.mockInstanceID token]);
-  [self.mockInstanceID stopMocking];
   OCMVerify([self.mockInstanceID defaultTokenWithHandler:nil]);
+  [self.mockInstanceID stopMocking];
+
```
Comment (morganchen12) [inline Example/InstanceID/Tests/FIRInstanceIDTest.m]: nit: extra newline

Comment (chliangGoogle) [reply Example/InstanceID/Tests/FIRInstanceIDTest.m]: Done.
