### PR TITLE
[SPM] Fix unfound file warnings from swift build

### LINKED ISSUE #16012: SwiftPM warning "found unhandled files" when building firebase-ios-sdk via swift build
### Description

When building a Swift package that depends on firebase-ios-sdk using Swift Package Manager, multiple warnings are emitted about unhandled files in Firebase targets.

## Expected

I expected swift build to complete without warnings related to the Firebase package, assuming all non-source files are either properly excluded or declared as resources in Package.swift.

## Actually happened

swift build completes successfully, but emits a large number of warnings such as:

warning: 'firebase-ios-sdk': found N file(s) which are unhandled; explicitly declare them as resources or exclude from the target

From the attached log:

- ~15 files under FirebaseAI/Sources/**/AGENTS.md
- ~190 files under Crashlytics/**, including:
  - Unit test files (UnitTests/*.m, .swift)
  - Test data (*.clsrecord, .log, .dylib, etc.)
  - Scripts (generate_project.sh, upload-symbols)
  - Documentation (README.md, CHANGELOG.md)
  - Misc files (.plist, .xcfilelist, .proto, etc.)

These files appear to be:

- test-only artifacts
- documentation
- scripts or auxiliary data

and are not intended to be compiled or bundled as resources.

## Impact
The build succeeds, but the warnings are noisy (hundreds of files).
It becomes difficult to distinguish actionable warnings from noise.
Consumers of the package cannot suppress or fix these warnings from their side, since exclude and resources must be defined in the dependency’s Package.swift.

### Reproducing the issue

_No response_

### Firebase SDK Version

12.11.0

### Xcode Version

26.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell
warning: 'firebase-ios-sdk': found 15 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/Imagen/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Extensions/Internal/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Public/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Public/Imagen/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Public/Live/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Protocols/Internal/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/Tools/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/Live/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/Errors/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Public/Tools/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Protocols/AGENTS.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/FirebaseAI/Sources/Types/Internal/Requests/AGENTS.md
warning: 'firebase-ios-sdk': found 190 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/internal_incremental_kv.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSFileManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSInternalReportTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/x86_64-executable
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSReportAdapterTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSProcessReportOperationTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiagnosticPayload.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockSymbolResolver.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSContextManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSCrashedMarkerFile.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRStackFrameTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Settings/FIRCLSSettingsManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/FIRCLSUnwind_arm.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/run
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/armv7-armv7s-executable
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRMockInstallations.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/ProtoSupport/generate_crashlytics_protos.sh
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSNetworking/FIRCLSNetworkResponseHandler.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/bare_min_crash/sdk.log
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/bare_min_crash/signal.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSOperation/FIRCLSCompoundOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/bare_min_crash/metadata.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSConstantsTest.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/Reports/FIRCLSProcessReportOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/errors_a.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRExceptionModelTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXDiskWriteExceptionDiagnostic.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTestsSwift/CrashlyticsRemoteConfigManagerTests.swift
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSThreadState.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/corrupt_metadata/metadata.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/DS_Store
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXCPUExceptionDiagnostic.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/binary_images_with_null_base_entry.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/Symbolication/FIRCLSSymbolicationOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSContextInitData.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/FIRStackFrame.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSFABHost.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/crashlytics.proto
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSMachO/FIRCLSCodeMapping.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Handlers/FIRCLSSignal.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSMetricKitManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/Symbolication/FIRCLSThreadArrayOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOBinaryTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSOnDemandModelTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSInstallIdentifierModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSUUID.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/FIRCrashlyticsReport.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/errors_b.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/FIRCrashlytics.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/FIRCLSdSYMTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/tvsimulator-binary
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSUtilityTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRMockGDTCoreTransport.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSInternalReport.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSSymbolResolverTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/generate_project.sh
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSRolloutsPersistenceManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Handlers/FIRCLSHandler.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/armv7k
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/third_party/libunwind/LICENSE
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSExistingReportManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSByteUtility.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockExistingReportManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/metadata.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABOperation/FABTestAsyncOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSApplication.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/Record/FIRCLSRecordHost.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/Symbolication/FIRCLSDemangleOperation.mm
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSLoggingTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSUserDefaultsTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/Symbolication/FIRCLSSerializeSymbolicatedFramesOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/LICENSE
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSUserLogging.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Operations/FIRCLSAsyncOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/tvos-binary
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/user_incremental_kv.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXCrashDiagnostic.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSFileManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSSettingsTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSManagerData.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSTempMockFileManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSMachO/FIRCLSdSYM.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSOperation/FIRCLSFABAsyncOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSNotificationManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/signal.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockOnDemandModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSAnalyticsManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSDataCollectionArbiterTest.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSSymbolicationOperationTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSBinaryImage.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/Record/FIRCLSRecordBase.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachOBinary.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSExistingReportManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRAppFake.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSDemangleOperationTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSHost.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMetricKitManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/FIRCLSMachOTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSInternalLogging.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSInstallIdentifierModelTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/bare_min_crash/internal_incremental_kv.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMetricKitManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRRecordExceptionModelTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSReportManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/mach_exception.clsrecord.symbolicated
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABOperation/FABNetworkOperationTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/i386-simulator.dSYM/Contents/Resources/DWARF/CrashTest
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSCallStackTree.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABURLBuilderTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/bare_min_crash/binary_images.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/Compact/FIRCLSCompactUnwind.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSProcess.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSExecutionIdentifierModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDataParsing.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/metadata_only_report/metadata.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSReportUploaderTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionToken.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSDwarfTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/FIRExceptionModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/log_a.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSFile.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfUnwind.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/README.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/DataCollection/FIRCLSDataCollectionArbiter.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSNetworking/FIRCLSURLBuilder.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/sdk.log
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSDwarfExpressionTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSUtility.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/armv7-armv7s.dSYM/Contents/Info.plist
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/watchOS-simulator
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/10.9.3_libobjc.A.dylib
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Components/FIRCLSContext.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABOperation/FABTestExpectations.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/i386-simulator.dSYM/Contents/Info.plist
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/Dwarf/FIRCLSDwarfExpressionMachine.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSOnDemandModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/mach_exception.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/Record/FIRCLSRecordApplication.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/armv7-armv7s-arm64.dylib
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSReportUploader.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/FIRCLSUserDefaults/FIRCLSUserDefaults.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/binary_images_missing_base_entry.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockSettings.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSMachO/machO_data/armv7-armv7s.dSYM/Contents/Resources/DWARF/CrashTest
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/FIRCLSUnwind.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXCallStackTree.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSNetworking/FIRCLSFABNetworkClient.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSRolloutsPersistenceManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/exception.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Protogen/nanopb/crashlytics.nanopb.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FABMockApplicationIdentifierModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXHangDiagnostic.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Settings/Operations/FIRCLSDownloadAndSaveSettingsOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Handlers/FIRCLSException.mm
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSConstants.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockReportManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/CHANGELOG.md
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockReportUploader.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/exception.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSSymbolResolver.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSCompactUnwindTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCrashlyticsReportTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockFileManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Mocks/FIRCLSMockMXMetadata.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/Record/FIRCLSRecordIdentity.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/CrashlyticsInputFiles.xcfilelist
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Settings/Operations/FIRCLSNetworkOperation.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/CrashlyticsKitTests-OSX-Prefix.pch
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABOperation/FABOperationInFlightCancellationTest.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FABOperation/FABOperationPreFlightCancellationTest.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/ProtoSupport/Protos/crashlytics.options
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSLaunchMarkerModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/10.9.4_libsystem_kernel.dylib
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Models/FIRCLSSettings.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Handlers/FIRCLSMachException.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/GoogleService-Info.plist
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/valid_metadata/metadata.clsrecord
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachOSlice.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSContextManagerTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/CrashlyticsKitTests-Info.plist
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSLogger.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Unwind/FIRCLSUnwind_x86.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/FIRCLSFileTests.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Helpers/FIRCLSAllocate.c
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/Crashlytics/Settings/Models/FIRCLSApplicationIdentifierModel.m
    ${PackageDirPath}/.build/checkouts/firebase-ios-sdk/Crashlytics/UnitTests/Data/ios_all_files_crash/binary_images.clsrecord
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "52548902007e7beda99fcdca31f62eccc4befe38",
        "version" : "12.11.0"
      }
    },
```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by paulb777**
Fix #16012
The [Pull Request #16041](https://github.com/firebase/firebase-ios-sdk/pull/16041/changes) in the `firebase-ios-sdk` repository aims to fix "file not found" warnings that occur during Swift Package Manager (SPM) builds.

### Key Changes

*   **Fixing Build Warnings:** The primary goal is to resolve warnings triggered by `swift build` related to missing or incorrectly referenced files.
*   **Package.swift Updates:** Modifications were made to the `Package.swift` file to refine how paths and exclusions are handled. This includes:
    
    *   Updating paths for `FirebaseCrashlyticsSwift`.
    *   Cleaning up trailing slashes in path strings (e.g., changing `"ProtoSupport/"` to `"ProtoSupport"`).
    *   Consolidating source and exclusion lists to ensure the build system correctly identifies the intended files.
*   **Documentation Consolidation:** A significant number of small `AGENTS.md` files scattered throughout the `FirebaseAI` directory were deleted and replaced with a single, comprehensive [FirebaseAI/AGENTS.md](https://www.google.com/search?q=https://github.com/firebase/firebase-ios-sdk/pull/16041/changes%23diff-87723916738245844439c065094254070774a815777823521d8b297b47690660). This new file serves as a "Codebase Map" to help AI agents navigate the SDK structure.
*   **Changelog Updates:** The `CHANGELOG.md` files for both [Crashlytics](https://www.google.com/search?q=https://github.com/firebase/firebase-ios-sdk/pull/16041/changes%23diff-7d2d38584852077e6417441548e653841e40a0efb0e00f919d3807572d4c09d5) and [FirebaseAI](https://www.google.com/search?q=https://github.com/firebase/firebase-ios-sdk/pull/16041/changes%23diff-e61be1a54558e0a138c2901a88484a0d8b4e3391216a75f1068c22731872138a) were updated to reflect these fixes.

### Statistics

*   **Files changed:** 19
*   **Additions:** 187
*   **Deletions:** 286

In short, it’s a cleanup PR focused on **improving SPM reliability** and **streamlining internal documentation** for better AI-assisted development.

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -193,9 +193,26 @@ let package = Package(
...
+        "Types/Public/Live/AGENTS.md",
+        "Protocols/Internal/AGENTS.md",
+        "Types/Internal/AGENTS.md",
+        "Types/Internal/Tools/AGENTS.md",
+        "Types/Internal/Live/AGENTS.md",
+        "Types/Internal/Errors/AGENTS.md",
+        "Types/Public/Tools/AGENTS.md",
+        "Types/AGENTS.md",
+        "Protocols/AGENTS.md",
+        "Types/Internal/Requests/AGENTS.md",
```
Comment (ncooke3) [inline Package.swift]: Thinking aloud, I wonder how valuable these directory specific agent files are, compared to a single product directory level agents file.

Comment (paulb777) [reply Package.swift]: According to Gemini: 

Reduced Tool Calls (Highly Effective for Large Contexts): For modern AI agents with large context windows (like Gemini), reading one file at the start to understand the entire project structure is much more efficient. It avoids the need for iterative file reading to discover where things are.
Full Picture Searchability: An agent can perform a simple text search within the single file to find the path and description of any file in the project instantly.

File: Package.swift [hunk 2]
```diff
@@ -563,10 +563,7 @@ let package = Package(
     .target(
       name: "FirebaseCrashlyticsSwift",
       dependencies: ["FirebaseRemoteConfigInterop"],
-      path: "Crashlytics",
-      sources: [
-        "Crashlytics/Rollouts/",
-      ]
+      path: "Crashlytics/Crashlytics/Rollouts"
```
[the remark this answers is not in the document]
Comment (paulb777) [reply Package.swift:566]: It's intended.

**Review by ncooke3 — APPROVED** [review]
