### PR TITLE
Defend against users making API calls during deinit

### LINKED ISSUE #753: Firestore Crash - FSTDispatchQueue dispatchAsync
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
  * Firebase SDK version: 4.8.0
  * Firebase Component: Firestore
  * Component version: 0.9.4

### [REQUIRED] Step 3: Describe the problem

Fatal Exception: NSInternalInconsistencyException
**FIRESTORE INTERNAL ASSERTION FAILED: dispatchAsync called when we are already running on target dispatch queue 'com.google.firebase.firestore**

#### Steps to reproduce:

Repeat doing ListenerRegistration.remove() after Query.addSnapshotListener() quickly and occasionally reproduce.

Logs

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1b287b3d __exceptionPreprocess
1  libobjc.A.dylib                0x1a50f067 objc_exception_throw
2  CoreFoundation                 0x1b287a19 +[NSException raise:format:]
3  Foundation                     0x1bb7d52d (Missing)
4  MyApp                         0x1abd33 -[FSTDispatchQueue dispatchAsync:]
5  MyApp                         0x1657ab -[FSTFirestoreClient removeListener:]
6  MyApp                         0x15a455 -[FSTListenerRegistration remove]
7  MyApp                         0x1f8f28 DataSource.deinit (DataSource.swift:384)
8  MyApp                         0x1f8fc8 DataSource.__deallocating_deinit (DataSource.swift:383)
9  libswiftCore.dylib             0x141126b _swift_release_dealloc
10 libswiftCore.dylib             0x14117c7 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrementSlow<(swift::ClearPinnedFlag)0, (swift::PerformDeinit)1>(swift::SideTableRefCountBits, unsigned int)
11 libswiftCore.dylib             0x1411753 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::ClearPinnedFlag)0, (swift::PerformDeinit)1>(unsigned int)
12 libswiftCore.dylib             0x1410945 _swift_release_
13 MyApp                         0x1ff0ac (Missing)
14 libswiftCore.dylib             0x141126b _swift_release_dealloc
15 MyApp                         0x2226e8 (Missing)
16 libswiftCore.dylib             0x141126b _swift_release_dealloc
17 libsystem_blocks.dylib         0x1a99fbb9 _Block_release
18 MyApp                         0x156e9f __destroy_helper_block_
19 libsystem_blocks.dylib         0x1a99fbb9 _Block_release
20 MyApp                         0x1573ff __destroy_helper_block_.152
21 libsystem_blocks.dylib         0x1a99fbb9 _Block_release
22 libobjc.A.dylib                0x1a50e053 object_cxxDestructFromClass(objc_object*, objc_class*)
23 libobjc.A.dylib                0x1a5196ad objc_destructInstance
24 libobjc.A.dylib                0x1a5196cd object_dispose
25 libobjc.A.dylib                0x1a529259 objc_object::sidetable_release(bool)
26 libsystem_blocks.dylib         0x1a99fbb9 _Block_release
27 MyApp                         0x163bbf -[FSTQueryListener .cxx_destruct]
28 libobjc.A.dylib                0x1a50e053 object_cxxDestructFromClass(objc_object*, objc_class*)
29 libobjc.A.dylib                0x1a5196ad objc_destructInstance
30 libobjc.A.dylib                0x1a5196cd object_dispose
31 libobjc.A.dylib                0x1a529259 objc_object::sidetable_release(bool)
32 libsystem_blocks.dylib         0x1a99fbb9 _Block_release
33 libdispatch.dylib              0x1a96259d _dispatch_queue_serial_drain
34 libdispatch.dylib              0x1a958b71 _dispatch_queue_invoke
35 libdispatch.dylib              0x1a962a1f _dispatch_queue_override_invoke
36 libdispatch.dylib              0x1a9641b5 _dispatch_root_queue_drain
37 libdispatch.dylib              0x1a96400f _dispatch_worker_thread3
38 libsystem_pthread.dylib        0x1ab0a87d _pthread_wqthread
39 libsystem_pthread.dylib        0x1ab0a45c start_wqthread
```

```
Crashed: com.twitter.crashlytics.ios.exception
0  MyApp                         0xa074b CLSProcessRecordAllThreads + 1513291
1  MyApp                         0xa074b CLSProcessRecordAllThreads + 1513291
2  MyApp                         0xa0643 CLSProcessRecordAllThreads + 1513027
3  MyApp                         0x941ed CLSHandler + 1462765
4  MyApp                         0x9f01f __CLSExceptionRecord_block_invoke + 1507359
5  libdispatch.dylib              0x1a955783 _dispatch_client_callout + 22
6  libdispatch.dylib              0x1a961a35 _dispatch_barrier_sync_f_invoke + 50
7  MyApp                         0x9ea13 CLSExceptionRecord + 1505811
8  MyApp                         0x9e83b CLSExceptionRecordNSException + 1505339
9  MyApp                         0x9e43d CLSTerminateHandler() + 1504317
10 libc++abi.dylib                0x1a50398f std::__terminate(void (*)()) + 78
11 libc++abi.dylib                0x1a5031a3 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 110
12 libobjc.A.dylib                0x1a50f139 _objc_exception_destructor(void*) + 246
13 CoreFoundation                 0x1b287a19 +[NSException raise:format:] + 94
14 Foundation                     0x1bb7d52d <redacted> + 92
15 MyApp                         0x1abd33 -[FSTDispatchQueue dispatchAsync:] + 2608435
16 MyApp                         0x1657ab -[FSTFirestoreClient removeListener:] + 2320299
17 MyApp                         0x15a455 -[FSTListenerRegistration remove] + 2274389
18 MyApp                         0x1f8f28 DataSource.deinit (DataSource.swift:384)
19 MyApp                         0x1f8fc8 DataSource.__deallocating_deinit (DataSource.swift:383)
20 libswiftCore.dylib             0x141126b _swift_release_dealloc + 18
21 libswiftCore.dylib             0x14117c7 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrementSlow<(swift::ClearPinnedFlag)0, (swift::PerformDeinit)1>(swift::SideTableRefCountBits, unsigned int) + 104
22 libswiftCore.dylib             0x1411753 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::ClearPinnedFlag)0, (swift::PerformDeinit)1>(unsigned int) + 100
23 libswiftCore.dylib             0x1410945 _swift_release_ + 148
24 MyApp                         0x1ff0ac (Missing)
25 libswiftCore.dylib             0x141126b _swift_release_dealloc + 18
26 MyApp                         0x2226e8 (Missing)
27 libswiftCore.dylib             0x141126b _swift_release_dealloc + 18
28 libsystem_blocks.dylib         0x1a99fbb9 _Block_release + 130
29 MyApp                         0x156e9f __destroy_helper_block_ + 2260639
30 libsystem_blocks.dylib         0x1a99fbb9 _Block_release + 130
31 MyApp                         0x1573ff __destroy_helper_block_.152 + 2262015
32 libsystem_blocks.dylib         0x1a99fbb9 _Block_release + 130
33 libobjc.A.dylib                0x1a50e053 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
34 libobjc.A.dylib                0x1a5196ad objc_destructInstance + 34
35 libobjc.A.dylib                0x1a5196cd object_dispose + 14
36 libobjc.A.dylib                0x1a529259 objc_object::sidetable_release(bool) + 238
37 libsystem_blocks.dylib         0x1a99fbb9 _Block_release + 130
38 MyApp                         0x163bbf -[FSTQueryListener .cxx_destruct] + 2313151
39 libobjc.A.dylib                0x1a50e053 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
40 libobjc.A.dylib                0x1a5196ad objc_destructInstance + 34
41 libobjc.A.dylib                0x1a5196cd object_dispose + 14
42 libobjc.A.dylib                0x1a529259 objc_object::sidetable_release(bool) + 238
43 libsystem_blocks.dylib         0x1a99fbb9 _Block_release + 130
44 libdispatch.dylib              0x1a96259d _dispatch_queue_serial_drain + 854
45 libdispatch.dylib              0x1a958b71 _dispatch_queue_invoke + 886
46 libdispatch.dylib              0x1a962a1f _dispatch_queue_override_invoke + 282
47 libdispatch.dylib              0x1a9641b5 _dispatch_root_queue_drain + 326
48 libdispatch.dylib              0x1a96400f _dispatch_worker_thread3 + 106
49 libsystem_pthread.dylib        0x1ab0a87d _pthread_wqthread + 1040
50 libsystem_pthread.dylib        0x1ab0a45c start_wqthread + 8
```

### PR DESCRIPTION
**Pull request by wilhuff**
Track operation in progress FSTDispatchQueue and allow dispatchAsync onto the worker queue even from the same queue if an operation is not in progress. Fixes #753.

This fixes a corner case that happens when users pass us an object and we retain that object in a block submitted to the worker queue for processing. Users are not obligated to retain that object themselves. This can lead to the object's destructor (or dealloc or deinit) being called on the Firestore worker thread. If that destructor makes Firestore API calls (most likely ListenerRegistration.remove but any are possible) this will trigger the assertion.

### CODE REVIEW

**Comment by paulb777** [comment]
I'll cherry-pick it to the release branch and copybara it if @ryanwilson is ok to do another candidate build.

**Comment by ryanwilson** [comment]
Happy to do another candidate when this goes in.

**Comment by paulb777** [comment]
Since there's now conflicts to master, consider redirecting the PR to the release-4.10.0 branch

**Comment by wilhuff** [comment]
We discussed offline in today's sprint planning and we've decided this isn't high enough priority to warrant a cherry pick:

  * There are now two workarounds posted on the issue
  * We're concerned that making Firestore API calls in a deinitializer is a bad practice anyway, that we should perhaps defend against explicitly with a better error message but still fail
  * This may not be the right fix anyway, since it causes this bifurcation in how we handle dispatch onto the worker thread

I'm going to retarget this at master and we'll work through these issues.

**Comment by mikelehen** [comment]
Sorry for sitting on this.  Per previous discussion I'm not wild about allowing user code to run on our queue.   

As I mentioned, I suspect that the actual destruction is happening when the dispatch_queue is draining its NSAutoReleasePool (I believe that whenever a dispatch_queue block is run, it's effectively wrapped in an `@autoreleasepool { ... }` block).  I suspect this since `[FSTQueryListener .cxx_destruct]` is the first frame on the stack with our code (as opposed to whatever code of ours is removing the last reference to the FSTQueryListener), and [this StackOverflow answer](https://stackoverflow.com/a/45429019) claims "When you see a crash with _dispatch_root_queue_drain in the stack trace it means some block has already executed on that queue and the autorelease pool is being drained." which would also match.

I was going to suggest that this means we _could_ use a boolean flag to indicate that we're inside a block we've queued on our dispatch_queue.  i.e. we always do:

```
dispatch_async(self.queue, ^{
  self.executingBlockOnQueue = YES;
  wrappedBlock();
  self.executingBlockOnQueue = NO;
});
```

But that still doesn't handle other code (e.g. GRPC) queuing blocks on our queue. And so we still can't isolate the "user's code is running on our code via a destructor" case... :-/

So I think I'm leaning towards declaring that "users should not call our code from their deinitializers" and updating our error message to be something like, "A Firestore SDK method was called via a deinit method. This is not supported. Please use viewWillDisappear or a similar hook to remove listeners or perform other cleanup. [NOTE for Firestore SDK Internal Developers: This error can also occur if you call distachAsync when already on our worker queue.]" and have a big code comment above the error explaining what's going on...

**Comment by wilhuff** [comment]
I'm not a fan of being really user hostile about this. In particular I'm not a fan of this kind of error because the race conditions required to tickle it are complex enough that a developer may not see the error in development. I'm not sure I'm so allergic to user code running on our queue that I want to potentially fail developer apps after deployment.

Generally we don't want users to run code on our queue because it impacts our ability to be responsive but there's literally nothing we can do to stop it: they can get the queue by name and drop stuff on it if they want. I think we have to remember though that this is *their app* and their code running on our queue isn't going to hurt anything.

So my take is that this is far enough of an edge case that we shouldn't worry about the user code and should instead just preserve the error semantics we originally intended without tripping up on a deinitializer on our queue problem.

To that end I think on our queue and currently executing one of our actions should be the condition that causes a rejection into the async queue. That catches the original class of bugs we were trying to stomp without getting up in the user's face about something they don't have a lot of control over.

**Comment by mikelehen** [comment]
My goal is definitely not to be user hostile. I agree that allowing this specific case (that we know is "safe" because it's not actually running their code inside of our code) would be preferable.

> I think on our queue and currently executing one of our actions should be the condition that causes a rejection into the async queue

I'm a fan of that and that's the direction I was going with the boolean. But I'm not sure how we deal with GRPC running our code on our queue (and I haven't checked if GRPC is the only case of that).  Do we attempt to make that behave as "one of our actions" to make sure we catch it if we accidentally do an extra dispatch?

One solution would be to _not_ have GRPC dispatch onto our queue and do the dispatchAsync manually ourself (as we did until your recent fix for those stream race conditions), but then we need to rework the FSTCallbackFilter to accommodate that.

If we think the error will be too hostile, I'm happy to proceed down the path of differentiating "on our queue" from "executing one of our actions" and allowing the former to dispatch onto our queue but not the latter.

**Comment by wilhuff** [comment]
My plan in a nutshell:

  * `verifyIsCurrentQueue` will fail if an operation is not in progress
  * I will add `[FSTDispatchQueue enterCheckedOperation:]` that does the boolean thing, called by our dispatch_async
  * `enterCheckedOperation` will set the operation in progress flag then `verifyIsCurrentQueue`
  * It becomes incumbent upon any the user of an API that will dispatch directly onto our queue to immediately call `enterCheckedOperation`.

We were pretty religious about sprinkling `verifyIsCurrentQueue` throughout the networking callbacks so I think this enough to ensure that invariant I described is active whenever we're in our code.

**Comment by mikelehen** [comment]
Cool. I think that sounds good to me!

**Comment by wilhuff** [comment]
PTAL

Sorry this took so long, but I added a bunch of tests to validate that the dispatch queue is actually behaving the way we're intending with this change. I couldn't repro the user-described issue directly in an integration test, but it was straightforward to do in `FSTDispatchQueueTests` so I did it there.

File: Firestore/Example/Tests/Integration/FSTStreamTests.mm [hunk 1]
```diff
@@ -286,7 +286,9 @@ - (void)testStreamClosesWhenIdle {
   [_workerDispatchQueue runDelayedCallbacksUntil:FSTTimerIDWriteStreamIdle];
 
   dispatch_sync(_testQueue, ^{
```
Comment (mikelehen) [inline Firestore/Example/Tests/Integration/FSTStreamTests.mm]: FSTDispatchQueue has a dispatchSync method now. Can we just use it instead?

File: Firestore/Source/Util/FSTDispatchQueue.h [hunk 2]
```diff
@@ -74,6 +74,13 @@ typedef NS_ENUM(NSInteger, FSTTimerID) {
  */
 - (void)verifyIsCurrentQueue;
 
+/**
+ * Declares that a dispatch queue operation is already in progress. To be used only when called
```
Comment (mikelehen) [inline Firestore/Source/Util/FSTDispatchQueue.h]: nit: "Operation is already in progress" seems a bit unclear since operationInProgress will /not/ already be true. Perhaps reword to something like:

Declares that we are already executing on the correct dispatch_queue_t and would like to officially execute code on behalf of this FSTDispatchQueue.

File: Firestore/Source/Util/FSTDispatchQueue.h [hunk 3]
```diff
@@ -74,6 +74,13 @@ typedef NS_ENUM(NSInteger, FSTTimerID) {
...
+ * back by some other API directly onto our queue. This allows us to safely dispatch directly onto
+ * the worker queue without destroying the invariants this class helps us maintain.
+ */
+- (void)enterCheckedOperation:(void (^)(void))block;
```
Comment (mikelehen) [inline Firestore/Source/Util/FSTDispatchQueue.h]: FYI- I like "Operation" but so far this code uses "Callback" (whereas web uses "Operation" and Android uses "Task").  This difference is annoying (it pained me to introduce "FSTDelayedCallback", etc.) and I'd be a fan of unifying more on "Operation" or similar. I'm fine with keeping this as enterCheckedOperation, but perhaps add a TODO to unify terminology?

File: Firestore/Source/Util/FSTDispatchQueue.mm [hunk 4]
```diff
@@ -151,6 +153,12 @@ @interface FSTDispatchQueue ()
  */
 @property(nonatomic, strong, readonly) NSMutableArray<FSTDelayedCallback *> *delayedCallbacks;
 
+/**
+ * Flag set while there's an outstanding FSTDispatchQueue operation, used for assertion
```
Comment (mikelehen) [inline Firestore/Source/Util/FSTDispatchQueue.mm]: "Flag set while an FSTDispatchQueue operation is currently executing" ?  (since "outstanding" could be interpreted to mean there are queued operations that haven't run yet)

File: Firestore/Source/Util/FSTDispatchQueue.mm [hunk 5]
```diff
@@ -173,18 +182,37 @@ - (void)verifyIsCurrentQueue {
...
+    [self verifyIsCurrentQueue];
+    block();
+  } @finally {
+    _operationInProgress = NO;
+  }
 }
 
 - (void)dispatchAsync:(void (^)(void))block {
-  FSTAssert(![self onTargetQueue],
+  FSTAssert(!_operationInProgress || ![self onTargetQueue],
```
Comment (mikelehen) [inline Firestore/Source/Util/FSTDispatchQueue.mm]: Hrm...  Why isn't this just `!_operationInProgress` ?  It would be invalid for _operationInProgress to be true when [self onTargetQueue] is not, but this assert makes it appear valid.

File: Firestore/Source/Util/FSTDispatchQueue.mm [hunk 6]
```diff
@@ -173,18 +182,37 @@ - (void)verifyIsCurrentQueue {
...
 }
 
 - (void)dispatchAsyncAllowingSameQueue:(void (^)(void))block {
-  dispatch_async(self.queue, block);
+  dispatch_async(self.queue, ^{
+    [self enterCheckedOperation:block];
+  });
 }
 
 - (void)dispatchSync:(void (^)(void))block {
```
Comment (mikelehen) [inline Firestore/Source/Util/FSTDispatchQueue.mm]: Is there a reason this shouldn't use enterCheckedOperation too?

File: Firestore/Example/Tests/Integration/FSTStreamTests.mm [hunk 7]
```diff
@@ -285,11 +285,11 @@ - (void)testStreamClosesWhenIdle {
 
   [_workerDispatchQueue runDelayedCallbacksUntil:FSTTimerIDWriteStreamIdle];
 
-  dispatch_sync(_testQueue, ^{
+  [_workerDispatchQueue dispatchSync:^{
     [_workerDispatchQueue enterCheckedOperation:^{
```
Comment (mikelehen) [inline Firestore/Example/Tests/Integration/FSTStreamTests.mm]: I think we're double-calling enterCheckedOperation now (which should hopefully be causing the test to fail?).  Here and below.

Comment (wilhuff) [reply Firestore/Example/Tests/Integration/FSTStreamTests.mm]: Yep. Fixed.
