### PR TITLE
Only assign errors if parameter is non-NULL.

### LINKED ISSUE #4164: Functions analyze issues
bundle exec pod lib lint --sources=https://cdn.cocoapods.org/ --analyze --include-podspecs={FirebaseAuthInterop.podspec,FirebaseCore.podspec,GoogleUtilities.podspec,FirebaseCoreDiagnosticsInterop.podspec,FirebaseCoreDiagnostics.podspec,GoogleDataTransportCCTSupport.podspec,GoogleDataTransport.podspec} FirebaseFunctions.podspec
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
 -> FirebaseFunctions (2.5.1)
    - ERROR | build_pod: Static Analysis failed. You can use `--verbose` for more information. You can use `--no-clean` to save a reproducible buid environment.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Capabilities for App may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'App')
    - WARN  | [iOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/Functions/FirebaseFunctions/FUNSerializer.m:156:14: warning: Potential null dereference.  According to coding standards in 'Creating and Returning NSError Objects' the parameter may be null
    - NOTE  | [tvOS] xcodebuild:  warning: Potential null dereference.  According to coding standards in 'Creating and Returning NSError Objects' the parameter may be null
    - WARN  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/Functions/FirebaseFunctions/FUNSerializer.m:172:14: warning: Potential null dereference.  According to coding standards in 'Creating and Returning NSError Objects' the parameter may be null
    - WARN  | [tvOS] xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/Functions/FirebaseFunctions/FUNSerializer.m:205:14: warning: Potential null dereference.  According to coding standards in 'Creating and Returning NSError Objects' the parameter may be null

### PR DESCRIPTION
**Pull request by ryanwilson**
This fixes #4164.

```
pod lib lint --sources=https://cdn.cocoapods.org/ --analyze FirebaseFunctions.podspec

 -> FirebaseFunctions (2.5.1)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

FirebaseFunctions passed validation.
```

### CODE REVIEW

File: Functions/FirebaseFunctions/FUNSerializer.m [hunk 1]
```diff
@@ -153,7 +153,10 @@ - (nullable id)decodeWrappedType:(NSDictionary *)wrapped error:(NSError **)error
     NSNumberFormatter *formatter = [[NSNumberFormatter alloc] init];
     NSNumber *n = [formatter numberFromString:value];
     if (n == nil) {
-      *error = FUNInvalidNumberError(value, wrapped);
+      // Only assign the `error` parameter if it was passed in.
+      if (error != NULL) {
```
Comment (maksymmalyhin) [inline Functions/FirebaseFunctions/FUNSerializer.m]: nit: Defining function like [this](https://github.com/firebase/firebase-ios-sdk/blob/42118c9b1398af076b9a05557b4cb8bb21ddc70a/FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m#L23) in `GoogleUtilities` and using it in client SDKs may save us a couple lines here and there. WDYT?

Comment (ryanwilson) [reply Functions/FirebaseFunctions/FUNSerializer.m]: I don't mind the idea but I'm not sure it's worth it for a few reasons:

- It's obvious what this does at the call site,
- We'll have to remember to use it, which I'm not convinced I'd be able to since it's a very quick `if` check,
- More classes imported, and potentially even a new dependency

I think if it was littered throughout the codebase it'd be worth it (like your example with FIS) but maybe SDKs can decide that for themselves.

Comment (bklimt) [inline Functions/FirebaseFunctions/FUNSerializer.m]: Wouldn't `nil` be more idiomatic than `NULL` in this case?

Comment (maksymmalyhin) [reply Functions/FirebaseFunctions/FUNSerializer.m]: `NULL` represents an "empty" pointer in C, in contrast to `nil` representing an empty Objective-C object. Since we are checking non-empty pointer to an error object `NULL` looks more appropriate literal to use here.

Comment (ryanwilson) [reply Functions/FirebaseFunctions/FUNSerializer.m]: +1 to what @maksymmalyhin said. The analyzer also complained about a missing `NULL` check.

**Comment by ryanwilson** [comment]
> Adding the comments seems excessive, since it's pretty obvious what's happening.

Thanks, removed.
