### PR TITLE
Delete references to deprecated Crash and Invites

### LINKED ISSUE #2339: Deprecated Crash and Invites should be removed from Firebase pod
The deprecated Crash and Invites subspecs should be removed from Firebase pod at the next major release.

### PR DESCRIPTION
**Pull request by paulb777**
FirebaseCrash and FirebaseInvites will be deleted from the Firebase pod in the upcoming major release.

Fix #2339 together with cl/240786961

### CODE REVIEW

File: ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift [hunk 1]
```diff
@@ -360,24 +360,6 @@ struct ZipBuilder {
       fatalError("Could not write README to Zip directory: \(error)")
     }
 
-    // TODO: Remove this manual copy once FirebaseCrash is removed from the Zip file.
-    // Copy over the Crash scripts, if Crash should be installed
-    if subspecsToInstall.contains(.crash) {
-      do {
-        let crashDir = paths.templateDir.appendingPathComponent(Constants.ProjectPath.crashDir)
```
Comment (ryanwilson) [inline ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift]: Nit: there should be a few other things here you can delete: `Constants.ProjectPath.crashDir`, and all the files in [`ZipBuilder/Template/Crash`](https://github.com/firebase/firebase-ios-sdk/tree/master/ZipBuilder/Template/Crash) directory.

Comment (paulb777) [reply ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift]: Done. PTAL
