### PR TITLE
pod_lib_lint.rb improvements

### LINKED ISSUE #3416: Extremely flaky pod lib lint - url: The URL (https://twitter.com/Firebase) is not reachable.
A lot of jobs has been failing recently with error:
`WARN  | url: The URL (https://twitter.com/Firebase) is not reachable.`
e.g. https://travis-ci.org/firebase/firebase-ios-sdk/jobs/562729249

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #3416.

- comment out `social_media_url` in the linted podspec to fix #3416
- make sure the script fails if `pod lib lint` fails (converts silent failures like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/562678041) to visible failures like [this](https://travis-ci.org/firebase/firebase-ios-sdk/jobs/562705029))

### CODE REVIEW

File: scripts/pod_lib_lint.rb [hunk 1]
```diff
@@ -83,6 +88,11 @@ def main(args)
       puts "Still working, running for #{number_of_times_checked / 60}min."
     end
   end
+
+  unless pod_lint_result == true
+    exit(1)
```
Comment (wilhuff) [inline scripts/pod_lib_lint.rb]: Instead maybe capture the status code from the system command and just return that?

i.e. `pod_lint_status = $?` above and then just `exit(pod_lint_status)` here?

File: scripts/pod_lib_lint.rb [hunk 2]
```diff
@@ -162,4 +172,10 @@ def trace(*args)
   STDERR.puts(args.join(' '))
 end
 
+def remove_social_url_from_podspec(spec)
+  podspec_content = File.read(spec)
+  updated_podspec_content = podspec_content.gsub("s.social_media_url = ", "# s.social_media_url = ")
+  File.open(spec, "w") { |file| file.puts updated_podspec_content }
```
Comment (wilhuff) [inline scripts/pod_lib_lint.rb]: This modifies the file in place which dirties the workspace. Wouldn't writing to a temporary file be better?

Also:
  * please use parens in function invocations for consistency with the rest of the file
  * prefer `file.write` over `file.puts`. The latter adds an extra newline
  * line length on the line above (shoot for 80)

Comment (maksymmalyhin) [reply scripts/pod_lib_lint.rb]: Looks like using a temporary file is not really feasible unless we copy entire workspace:
- if I use a file in a temp dir lint fails with errors like:
```
bundle exec pod lib lint --sources=https://cdn.cocoapods.org/ --include-podspecs={FirebaseCore.podspec,GoogleUtilities.podspec,FirebaseCoreDiagnosticsInterop.podspec,FirebaseCoreDiagnostics.podspec,GoogleDataTransportCCTSupport.podspec,GoogleDataTransport.podspec,FirebaseInstanceID.podspec} /var/folders/mf/06z96qvx2rsgdrhhthyj1sn800lvg7/T/FirebaseInstallations.podspec --platforms=ios

 -> FirebaseInstallations (0.1.0)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - WARN  | [iOS] file patterns: The `public_header_files` pattern did not match any file.
    - WARN  | [iOS] license: Unable to find a license file
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  xcodebuild: error: The workspace named "App" does not contain a scheme named "". The "-list" option can be used to find the names of the schemes in the workspace.
```
- even if I use a temp file in the same dir (with intention to remove it afterwards) I get error like
```
bundle exec pod lib lint --sources=https://cdn.cocoapods.org/ --include-podspecs={FirebaseCore.podspec,GoogleUtilities.podspec,FirebaseCoreDiagnosticsInterop.podspec,FirebaseCoreDiagnostics.podspec,GoogleDataTransportCCTSupport.podspec,GoogleDataTransport.podspec,FirebaseInstanceID.podspec} FirebaseInstallations_temp.podspec --platforms=ios

 -> FirebaseInstallations (0.1.0)
    - ERROR | name: The name of the spec should match the name of the file.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:               AppHost-FirebaseInstallations-Unit-Tests.app encountered an error (Failed to install or launch the test runner. (Underlying error: The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)))
```

So, I wonder, it is a big concern to have a dirty workspace during lint? I can add running `git reset --hard ` on the script completion to avoid interference between different runs of `pod_lib_lint.rb`  within a single job.

Comment (paulb777) [reply scripts/pod_lib_lint.rb]: In this case, I think it's fine to dirty the workspace. Every subjob starts with a fresh clone and nothing about our tests care about the social_media specification anyway.

Comment (maksymmalyhin) [reply scripts/pod_lib_lint.rb]: @wilhuff I updated the code style (hope I didn't miss anything).

File: scripts/pod_lib_lint.rb [hunk 3]
```diff
@@ -83,6 +89,8 @@ def main(args)
       puts "Still working, running for #{number_of_times_checked / 60}min."
     end
   end
+
+  exit(pod_lint_status.exitstatus)
```
Comment (wilhuff) [inline scripts/pod_lib_lint.rb]: `1` does not have an `exitstatus` member, so this is somewhat nonsensical given the initial value of `pod_lint_status`. Maybe assign it `$?.exitstatus` above?

File: scripts/pod_lib_lint.rb (hunk 2 above)
Comment (wilhuff) [reply scripts/pod_lib_lint.rb]: Style changes LGTM

I've sent #3421 which avoids dirtying the workspace while avoiding `git reset`, which is problematic because it can discard local edits to the file.

File: scripts/pod_lib_lint.rb (hunk 3 above)
Comment (maksymmalyhin) [reply scripts/pod_lib_lint.rb]: Right, that was the original intention. Thanks!
