### PR TITLE
Fix documentation warning surfaced in Xcode from grpc

### LINKED ISSUE #6340: Documentation Issue: Parameter 'selected_port[out]' not found in the function declaration 6.31.0
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.31.0
  * Firebase Component: Firestore
  * Component version: 1.17.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When you run the application, this message appears

"Parameter 'selected_port[out]' not found in the function declaration"
"Did you mean 'selected_port'?"

Captura de Pantalla 2020-08-26 a la(s) 15 17 05

Captura de Pantalla 2020-08-26 a la(s) 15 19 51

### PR DESCRIPTION
**Pull request by dconeybe**
Fixes #6340

#no-changelog

### CODE REVIEW

File: Firestore/core/src/remote/grpc_connection.cc [hunk 1]
```diff
@@ -32,10 +32,14 @@
 #include "Firestore/core/src/util/log.h"
 #include "Firestore/core/src/util/statusor.h"
 #include "Firestore/core/src/util/string_format.h"
+#include "Firestore/core/src/util/warnings.h"
 #include "absl/memory/memory.h"
 #include "absl/strings/str_cat.h"
 #include "grpcpp/create_channel.h"
+
+SUPPRESS_DOCUMENTATION_WARNINGS_BEGIN()
 #include "grpcpp/grpcpp.h"
```
Comment (wilhuff) [inline Firestore/core/src/remote/grpc_connection.cc:41]: Might as well just surround all the grpcpp includes in the block.

Comment (dconeybe) [reply Firestore/core/src/remote/grpc_connection.cc:41]: Done.
