### PR TITLE
Fix races in lazy initialization of the client in FIRFirestore

### LINKED ISSUE #532: Firestore Crash - FSTFirebaseCredentialsProvider setUserChangeListener
Firebase Component: Firestore

Fatal Exception: NSInternalInconsistencyException
**FIRESTORE INTERNAL ASSERTION FAILED: UserChangeListener set twice!**

Not quite able to figure out a way to reproduce, but this unfortunately is a popular crash in my app :(

Logs
```
Crashed: com.twitter.crashlytics.ios.exception
0  <AppName>                       0x1022f4c00 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  <AppName>                       0x1022f4c00 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  <AppName>                       0x1022f4ab0 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  <AppName>                       0x1022e4948 CLSHandler (CLSHandler.m:26)
4  <AppName>                       0x1022f2bd8 __CLSExceptionRecord_block_invoke (CLSException.mm:199)
5  libdispatch.dylib              0x1827c5048 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1827cdae8 _dispatch_queue_barrier_sync_invoke_and_complete + 56
7  <AppName>                       0x1022f2670 CLSExceptionRecord (CLSException.mm:206)
8  <AppName>                       0x1022f24a8 CLSExceptionRecordNSException (CLSException.mm:102)
9  <AppName>                       0x1022f20bc CLSTerminateHandler() (CLSException.mm:259)
10 libc++abi.dylib                0x18207f54c std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18207eea8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x18209065c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x182e41bd8 +[NSException raise:format:] + 102
14 Foundation                     0x1837d1c24 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
15 <AppName>                       0x1023d7224 -[FSTFirebaseCredentialsProvider setUserChangeListener:] + 4330844708
16 <AppName>                       0x1023d9e24 -[FSTFirestoreClient initWithDatabaseInfo:usePersistence:credentialsProvider:userDispatchQueue:workerDispatchQueue:] + 4330855972
17 <AppName>                       0x1023d9c28 +[FSTFirestoreClient clientWithDatabaseInfo:usePersistence:credentialsProvider:userDispatchQueue:workerDispatchQueue:] + 4330855464
18 <AppName>                       0x1023ccad0 -[FIRFirestore firestoreWithConfiguredClient] + 4330801872
19 <AppName>                       0x1023ccca4 -[FIRFirestore collectionWithPath:] + 4330802340
20 <AppName>                       0x1022c01e0 __47-[HMAPI _updateObject:atEndpoint:onCompletion:]_block_invoke (HMAPI.m:2061)
21 libdispatch.dylib              0x1827c5088 _dispatch_call_block_and_release + 24
22 libdispatch.dylib              0x1827c5048 _dispatch_client_callout + 16
23 libdispatch.dylib              0x1827cc090 _dispatch_queue_override_invoke$VARIANT$mp + 716
24 libdispatch.dylib              0x1827d21c8 _dispatch_root_queue_drain + 596
25 libdispatch.dylib              0x1827d1f10 _dispatch_worker_thread3 + 120
26 libsystem_pthread.dylib        0x182a6b120 _pthread_wqthread + 1268
27 libsystem_pthread.dylib        0x182a6ac20 start_wqthread + 4
```

### PR DESCRIPTION
**Pull request by wilhuff**
Note that lazy initialization is required because we allow the user to
assign to settings after instantiation before any methods are used.

Also bring method naming closer to the android port.

Fixes #532.

### CODE REVIEW

File: Firestore/Source/API/FIRFirestore.m [hunk 1]
```diff
@@ -50,13 +50,14 @@ @interface FIRFirestore ()
 @property(nonatomic, strong) id<FSTCredentialsProvider> credentialsProvider;
 @property(nonatomic, strong) FSTDispatchQueue *workerDispatchQueue;
 
-@property(nonatomic, strong) FSTFirestoreClient *client;
+@property(nonatomic, strong, readonly) FSTFirestoreClient *client;
```
Comment (mikelehen) [inline Firestore/Source/API/FIRFirestore.m]: Hrm. Perhaps we've discussed this before, but isn't it disingenuous to mark something readonly if it is modified after the initializer runs?  Perhaps we should at least add a comment to flag the actual behavior?

File: Firestore/Source/API/FIRFirestore.m [hunk 2]
```diff
@@ -264,11 +276,17 @@ - (void)runTransactionWithBlock:(id _Nullable (^)(FIRTransaction *, NSError **er
...
 - (void)shutdownWithCompletion:(nullable void (^)(NSError *_Nullable error))completion {
-  if (!self.client) {
+  FSTFirestoreClient *client;
+  @synchronized (self) {
+    client = _client;
+    _client = nil;
+  }
+
+  if (!client) {
     completion(nil);
```
Comment (mikelehen) [inline Firestore/Source/API/FIRFirestore.m]: Uh, wow.  We probably shouldn't call their completion block synchronously from this thread.  I know this is existing code and we don't publicly expose shutdown, but maybe add a comment?

// TODO(mikelehen): We should be dispatching to the user queue, but since this isn't publicly exposed, we don't care for now.
