### PR TITLE
Fix pod spec lint and remove extraneous IID refs

### LINKED ISSUE #7834: Nightly Testing Report
# Nightly Testing Report
This issue([log](https://github.com/firebase/firebase-ios-sdk/actions/runs/714358156)) is generated at 04/03/2021 06:08 AM, fetching workflow runs triggered in the last 24 hrs.
| Workflow |04/02|
| -------- | -------- |
| [crashlytics](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/crashlytics.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/713347102) |
| [prerelease](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/prerelease.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/713782668) |

### PR DESCRIPTION
**Pull request by paulb777**
Fix #7834 
 
Fix the nightly test failure caused by missing unspecified header:
    - NOTE  | [watchOS] xcodebuild:  FirebaseMessaging/FirebaseMessaging/Sources/FIRMessaging.m:29:9: note: did not find header 'Source/Library/Public/FirebaseInstallations/FirebaseInstallations.h' in framework 'FirebaseInstallations' (loaded from '/Users/runner/Library/Developer/Xcode/DerivedData/App-egulcarutpujhtfyjnzoycquvdim/Build/Products/Release-watchsimulator/FirebaseInstallations')

Remove IID from the podspec

#no-changelog

### CODE REVIEW

File: FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m [hunk 1]
```diff
@@ -113,12 +113,14 @@ - (void)testBatchSizeReductionAfterSuccessfulTopicUpdate {
...
       [self expectationWithDescription:@"Batch size was reduced after topic suscription"];
 
+  __weak id weakSelf = self;
   self.alwaysReadyDelegate.subscriptionHandler =
       ^(NSString *topic, FIRMessagingTopicAction action,
         FIRMessagingTopicOperationCompletion completion) {
         // Simulate that the handler is generally called asynchronously
         dispatch_async(dispatch_get_main_queue(), ^{
           if (action == FIRMessagingTopicActionUnsubscribe) {
+            __unused id self = weakSelf;  // In Xcode 11, XCTAssertEqual references self.
```
Comment (chliangGoogle) [inline FirebaseMessaging/Tests/UnitTests/FIRMessagingPendingTopicsListTest.m:123]: Thanks paul! I couldn't figure out why this one is failing.

**Review by chliangGoogle — APPROVED** [review]
