### PR TITLE
[#11736] Tests Housekeeping

### LINKED ISSUE #11736: Functions tests crash the testing process because of force unwrapping
### Description

While running Firebase Functions tests locally (using the SPM installation and autocreated test plan), I noticed that a couple tests in `FirebaseFunctions/Tests/Integration/IntegrationTests.swift` (lines 562 and 594), if they fail, crash the entire testing process because of force unwrapping. That is somewhat annoying because it requires rerunning the already passed tests. The tests in question don’t really need `!`s and can safely use `?`s instead. I intend to introduce such a change in a PR that’s coming shortly.

```swift
          XCTAssertEqual(["start": 10 as Int32, "end": 20 as Int32, "long": 30],
                         error.userInfo["details"] as! [String: Int32])
```

Besides, a few other tests can be syntactically updated a bit so they generate fewer compiler warnings.

### Reproducing the issue

_No response_

### Firebase SDK Version

10.14.0

### Xcode Version

14.3.1, 15 beta 6

### Installation Method

Swift Package Manager

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

### PR DESCRIPTION
**Pull request by yakovmanshin**
[Closes #11736]

* Updated Firebase Functions’s `IntegrationTests` to prevent the testing process from crashing in case of test failure
* Updated `RemoteSettingsTests`, `SessionsSettingsTests`, and `FirebaseFirebaseDataEncoderTests` to generate fewer compiler warnings

### CODE REVIEW

File: FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift [hunk 1]
```diff
@@ -65,8 +65,7 @@ class SessionsSettingsTests: XCTestCase {
   func test_NoRemoteAndDefaultsPresent_DefaultConfigsApply() {
     let emptySettings: [String: Any] = [
       "cache_duration": 10,
-      "app_quality": [
-      ],
```
Comment (ncooke3) [inline FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift:69]: IIUC, the value here was incorrect as it's been changed to a dictionary `[:]` in the new diff?

Comment (yakovmanshin) [reply FirebaseSessions/Tests/Unit/SessionsSettingsTests.swift:69]: That’s what I believe. `app_quality` is a dictionary in every other test, plus it’s decoded as a dictionary in production code (`RemoteSettings.swift:43`), so I think it was previously declared as an array here simply by mistake.

**Review by ncooke3 — APPROVED** [review]
Thank you!
