### PR TITLE
FIRStorageUploadTask - fix crash in `isContentToUploadValid`

### LINKED ISSUE #2852: isContentToUploadValid throws NSException when data is nil
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2 (10E125)
  * Firebase SDK version: 5.4.1
  * Firebase Component: Storage
  * Component version: 3.1.1

#### Steps to reproduce:

Creating an `FIRStorageUploadTask` with a `nil` `data` parameter causes an unhandled `NSException` in another thread when trying to run the task, effectively killing the app.

#### Relevant Code:

The problem is discussed at the PR which introduced the lines that failes here: https://github.com/firebase/firebase-ios-sdk/pull/2458#discussion_r276273826

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #2852

### CODE REVIEW

File: Example/Storage/Tests/Unit/FIRStorageReferenceTests.m [hunk 1]
```diff
@@ -187,4 +187,29 @@ - (void)testReferenceWithNonExistentFileFailsWithCompletion {
...
+        metadata:nil
+      completion:^(FIRStorageMetadata *_Nullable metadata, NSError *_Nullable error) {
+        [expectation fulfill];
+        XCTAssertNotNil(error);
+        XCTAssertNil(metadata);
+
+        XCTAssertEqualObjects(error.domain, FIRStorageErrorDomain);
+        XCTAssertEqual(error.code, FIRStorageErrorCodeUnknown);
+        NSString *expectedDescription = [NSString
+            stringWithFormat:@"File at URL: %@ is not reachable.", dummyFileURL.absoluteString];
```
Comment (schmidt-sebastian) [inline Example/Storage/Tests/Unit/FIRStorageReferenceTests.m]: Should we just hardcode this sting to "File at URL: nil is not reachable"?
