### PR TITLE
Transition from NSAssert to GDTAssert in all GDT libraries

### LINKED ISSUE #3747: [GoogleDataTransport][I-GDT001006]
* Xcode version: 10.3
  * Firebase SDK version: 6.7.0
  * Firebase Component: Core, Messaging, DynamicLinks
  * Component version: FirebaseCore = 6.2.1 ; FirebaseAnalytics = 6.1.1 ; FirebaseDynamicLinks 4.0.3 ; FirebaseMessaging = 4.1.3 ; FirebaseAnalytics = 6.1.1

I recently updated my app with the latest firebase version. After launching the app and leaving it in idle for about 20 seconds, the app crashes and this is what I read from the console:

`[GoogleDataTansport][I-GDT001006] There was an error reading extension bytes from disk: Error Domain=NSCocoaErrorDomain Code=260 "Impossible open file “event-2009730023690886256” because there is no file of that type"`

### PR DESCRIPTION
**Pull request by mikehaney24**
Fixes #3747 

- Moves GDTAssert to be a public API
- Always logs to console
- Differentiates between fatal and non-fatal assertions
- Messaging of assertions encourages creating an issue
- Tests assertion use with NS_BLOCK_ASSERTIONS defined and undefined

### CODE REVIEW

File: GoogleDataTransport/GDTLibrary/GDTAssert.m [hunk 1]
```diff
@@ -14,9 +14,9 @@
  * limitations under the License.
  */
 
-#import "GDTLibrary/Private/GDTAssert.h"
+#import "GDTLibrary/Public/GDTAssert.h"
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTAssert.m]: Why Public?

File: GoogleDataTransport/GDTLibrary/GDTStorage.m [hunk 2]
```diff
@@ -86,6 +86,10 @@ - (void)storeEvent:(GDTEvent *)event {
     }];
   }
 
+  if (event == nil) {
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTStorage.m]: Move to top of function?

File: GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h [hunk 3]
```diff
@@ -56,7 +56,12 @@ typedef NS_ENUM(NSInteger, GDTMessageCode) {
   GDTMCETransportBytesError = 1005,
 
   /** For general purpose error messages in a dependency. */
-  GDTMCEGeneralError = 1006
+  GDTMCEGeneralError = 1006,
+
+  /** For fatal errors. Please go to https://github.com/firebase/firebase-ios-sdk/issues and open
+   * an issue if you encounter an error with this code.
+   */
+  GDTMCEFatalAssertion = 1007
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h]: I'd prefer something like "Serious" over "Fatal".  From an app developer perspective, It won't be fatal if GDT fails while doing CoreDiagnostics. 

I think it should be left to the clients to determine if something is fatal or not.

File: GoogleDataTransport/GDTLibrary/GDTAssert.m (hunk 1 above)
Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/GDTAssert.m]: Because it needs to be visible to GDTCCT and I've been trying to avoid module imports in implementation files.

File: GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h (hunk 3 above)
Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h]: This has to do with the operation of GDT, not CoreDiagnostics. Maybe while FIRCD is the only consumer this is true, but soon SDK service data will transit through GDT.

Comment (paulb777) [reply GoogleDataTransport/GDTLibrary/Public/GDTConsoleLogger.h]: Since the comment seems to be intended for anyone who sees a crash, will you clarify in the comment that a fatal error in GDT may not be fatal for the app depending upon what the GDT client is using it for.

**Comment by paulb777** [comment]
Still unresolved comment, but just a nit.

File: GoogleDataTransport/GDTLibrary/GDTStorage.m (hunk 2 above)
Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/GDTStorage.m]: Done.
