### PR TITLE
Fix main thread crashing issue, reenable tests.

### LINKED ISSUE #3973: Re-enable GDT Background Tests
As part of #3896 the background flag was changed, and subsequently harder to test. Two tests were temporarily disabled, but should be re-enabled ASAP.

### PR DESCRIPTION
**Pull request by ryanwilson**
Checking `applicationState` while not on the  main thread results in a crash. Revert to using notifications and a flag to track this, but with a single source of truth.

Fixes #3973.

### CODE REVIEW

File: GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m [hunk 1]
```diff
@@ -37,6 +37,13 @@ BOOL GDTCORReachabilityFlagsContainWWAN(SCNetworkReachabilityFlags flags) {
 #endif  // TARGET_OS_IOS
 }
 
+@interface GDTCORApplication () {
+  /** Private flag to match the existing `readonly` public flag. */
+  BOOL _isRunningInBackground;
```
Comment (maksymmalyhin) [inline GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: We don't write it from different threads (only read), but it may make sense to add `volatile` just in case.

Comment (maksymmalyhin) [reply GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: or declare it as an atomic property (which is a bit more common way to declare thread-safe variables)

File: GoogleDataTransport/GDTCORTests/Lifecycle/GDTCORLifecycleTest.m [hunk 2]
```diff
@@ -105,10 +108,8 @@ - (void)DISABLED_testBackgrounding {
       },
       5.0);
 
-  // TODO(#3973): This notification no longer triggers the `isRunningInBackground` flag. Find
-  // another way to test it.
   NSNotificationCenter *notifCenter = [NSNotificationCenter defaultCenter];
-  [notifCenter postNotificationName:kGDTCORApplicationDidEnterBackgroundNotification object:nil];
+  [notifCenter postNotificationName:UIApplicationDidEnterBackgroundNotification object:nil];
```
Comment (mikehaney24) [inline GoogleDataTransport/GDTCORTests/Lifecycle/GDTCORLifecycleTest.m]: Why change from the abstracted notification to an iOS-specific one?

Comment (ryanwilson) [reply GoogleDataTransport/GDTCORTests/Lifecycle/GDTCORLifecycleTest.m]: We previously used the abstract one because it triggered each classes' `foreground/background` flags, but now since the flag moved it's set before the abstracted notification is fired. Meaning: the abstract notification no longer triggers the flag to change, only the iOS specific one does.

File: .travis.yml [hunk 3]
```diff
@@ -570,3 +570,4 @@ jobs:
 branches:
   only:
     - master
+    - rw-gdt-background-mainthread
```
Comment (paulb777) [inline .travis.yml]: Remove

Comment (ryanwilson) [reply .travis.yml]: Thanks, done with the latest commit.
