### PR TITLE
Disable deprecation warning

### LINKED ISSUE #6502: Deprecations: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12
  * Firebase SDK version: 6.32.2
  * Firebase Component: Database
  * Component version: 6.6.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Warning for Deprecations shows up:

/Users/{$CURRENT_USER}/{$PROJECT_FOLDER}/Pods/FirebaseDatabase/FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:169:50: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead

#### Steps to reproduce:

- Updated to Xcode version 12
- Install/Update pods in working project
- Update pods to Swift 5.0 framework
- Applications Builds and Runs on iOS version 14
- Warning for Deprecations shows up for FirebaseDatabase pod

#### Relevant Code:

- Path to file: /Users/{$CURRENT_USER}/{$PROJECT_FOLDER}/Pods/FirebaseDatabase/FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m

- File name: FLevelDBStorageEngine.m

- Line number of error: 169:50

```
id pendingPut = [NSKeyedUnarchiver unarchiveObjectWithData:data];
```

### PR DESCRIPTION
**Pull request by paulb777**
Fix #6502

### CODE REVIEW

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m [hunk 1]
```diff
@@ -166,7 +166,11 @@ - (void)runLegacyMigration:(FRepoInfo *)info {
             // it'll go fine :P
             [writes enumerateKeysAndValuesAsData:^(NSString *key, NSData *data,
                                                    BOOL *stop) {
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
+              // Update the deprecated API when minimum iOS version is 11+.
               id pendingPut = [NSKeyedUnarchiver unarchiveObjectWithData:data];
```
Comment (maksymmalyhin) [inline FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: I don't think it's a great idea to silence this particular deprecation warning. I would go with it only if refactoring to use [GULSecureCoding](https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/Environment/Private/GULSecureCoding.h) is too complicated.

Comment (paulb777) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: Good point, but I'm not sure it's worth the time to update and test this rarely executed code. @schmidt-sebastian any thoughts?

Comment (schmidt-sebastian) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: Is the concern that we need to specify a class type (which would be FPendingPut)? 

https://github.com/linkedin/cassette/pull/18 has a wrapper that uses slightly different APIs that allows to drop usage of this method while continuing to use untyped types.

Comment (paulb777) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: @maksymmalyhin Correct me if I'm wrong, but my understanding of the concern is using the old unarchive API that doesn't check for NSError's. And GULSecureCoding wraps up the pre and post iOS 11 API nicely.

Comment (maksymmalyhin) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: Paul, there are two concerns here - the one you described and using `NSCoding`  instead of `NSSecureCoding` which implies the concern mentioned by Sebastian. So ideal fix will be updating `FPendingPut` and related classes to adopt `NSSecureCoding` and use `GULSecureCoding` to avoid code duplication related to deprecated methods and error handling.

Comment (paulb777) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:172]: None of the unit or integration tests exercise this line of code, so I'm hesitant to do more than add the `pragma clang diagnostic ignored`.

**Review by schmidt-sebastian — APPROVED** [review]

**Review by maksymmalyhin — APPROVED** [review]

**Comment by KevinVladG** [comment]
Thank you!! @paulb777
