### PR TITLE
Initializes the shared FIRAuthAppDelegateProxy instance in the main ...

### LINKED ISSUE #122: Update Auth ApiTests for Xcode 9
The tests crash at start up accessing the UI from a background thread

### PR DESCRIPTION
**Pull request by XiangtianDai**
…thread because it needs access to UIApplication.

This should fix #122 .

### CODE REVIEW

File: Firebase/Auth/Source/FIRAuth.m [hunk 1]
```diff
@@ -388,6 +388,8 @@ - (instancetype)initWithAPIKey:(NSString *)APIKey appName:(NSString *)appName {
     _firebaseAppName = [appName copy];
     #if TARGET_OS_IOS
     UIApplication *application = [UIApplication sharedApplication];
+    // Initailize the shared FIRAuthAppDelegateProxy instance in the main thread if not already.
```
Comment (paulb777) [inline Firebase/Auth/Source/FIRAuth.m]: spelling - Initialize

Comment (XiangtianDai) [inline Firebase/Auth/Source/FIRAuth.m]: Done.
