### PR TITLE
Crashlytics watchOS support

### LINKED ISSUE #4558: FR: Crashlytics support on watchOS
Please add Crashlytics support to watchOS, so that we can get crash reports from Firebase Crashlytics for watchOS apps just like we can for iOS apps.

### PR DESCRIPTION
**Pull request by jostster**
This PR resolves #4558 and adds crashlytics support for watchOS 6.0 +

### CODE REVIEW

**Comment by jostster** [comment]
@googlebot I signed it!

File: Crashlytics/Crashlytics/Components/FIRCLSApplication.m [hunk 1]
```diff
@@ -44,6 +44,8 @@
   return @"mac";
 #elif TARGET_OS_TV
   return @"tvos";
+#elif TARGET_OS_WATCH
+  return @"ios"; // TODO: temporarily use iOS until Firebase can add watchos to the backend
```
Comment (paulb777) [inline Crashlytics/Crashlytics/Components/FIRCLSApplication.m:48]: I suspect an extra space is needed before the comment to resolve the clang-format issue.  See https://github.com/firebase/firebase-ios-sdk#code-formatting

File: .github/workflows/crashlytics.yml [hunk 2]
```diff
@@ -77,7 +77,7 @@ jobs:
     runs-on: macos-latest
     strategy:
       matrix:
-        target: [ios, tvos, macos] # The macos and tvos tests can hang
+        target: [ios, tvos, macos, watchos --skip-tests] # The macos and tvos tests can hang
```
Comment (paulb777) [inline .github/workflows/crashlytics.yml:80]: Same change at line 24 for PRs

File: Crashlytics/Crashlytics/Components/FIRCLSProcess.c [hunk 3]
```diff
@@ -485,6 +485,9 @@ bool FIRCLSProcessRecordAllThreads(FIRCLSProcess *process, FIRCLSFile *file) {
 
     FIRCLSSDKLogInfo("recording thread %d data\n", i);
     if (!FIRCLSProcessRecordThread(process, thread, file)) {
+      FIRCLSFileWriteArrayEnd(file);
```
Comment (samedson) [inline Crashlytics/Crashlytics/Components/FIRCLSProcess.c:488]: Just one suggestion here: could you add an error SDK Log Error, eg:

`FIRCLSSDKLogError("Failed to record thread state. Closing threads JSON to prevent malformed crash report.")`

Comment (jostster) [reply Crashlytics/Crashlytics/Components/FIRCLSProcess.c:488]: Sure, since watchOS doesn't support thread states, should I wrap that if in a supported macro? Otherwise it will always log that error message for watchOS.

Comment (samedson) [reply Crashlytics/Crashlytics/Components/FIRCLSProcess.c:490]: I think it's ok to leave as-is. This will remind folks in the future that this is something we can improve upon 👍

**Comment by jostster** [comment]
@samedson looks like one check failed and was because of teamid during the build. I assume that is fine?

**Comment by paulb777** [comment]
@jostster That build failure is addressed by #6263. I'll merge this one here. Thanks!
