### PR TITLE
[Auth] Fix async/await crash from implicitly unwrapped nil error

### LINKED ISSUE #13470: AuthAPNSTokenManager.getToken() fatal error unwrapping nil
### Description

When performing `PhoneAuthProvider.provider().verifyPhoneNumber` and getting a timeout, the app crashes since `AuthAPNSTokenManager` runs into a nil unwrapping fatal error.

To my understanding, there is an issue in the commit **[auth-swift] Finish Transition to async-await for RPC calls (#11557)** from 19 Jul 2023.

Indeed the design of the callback in `getTokenInternal(callback: @escaping (AuthAPNSToken?, Error?) -> Void)` lacks consistency in my opinion.
It takes a tuple of two optional `(AuthAPNSToken?, Error?)` instead of using more appropriate structures such as `Result<AuthAPNSToken, Error>`.

It is probably envisioned by the developer that "it will never happen that both are nil at the same time", and thus we come with the implementation of `getToken() async throws AuthAPNSToken` which force unwraps `error` in the case of `token` being `nil`. See `AuthAPNSTokenManager` lines 76 to 86.

What strikes me is that in the case of a timeout, this callback (through the call of `self.callback` which gets over all the pending callbacks in the array which was set line 61) is called with `(nil, nil)` !

So it comes with not so much surprise that line 82 leads to a fatal error by force unwrapping a nil value.

Screenshot 2024-08-08 at 15 39 31

### Reproducing the issue

1. configure Firebase
2. call PhoneAuthProvider.provider().verifyPhoneNumber
3. get a timeout after 5 sec
4. app crashes

### Firebase SDK Version

11.0.0

### Xcode Version

15.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Not applicable.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Not applicable.

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
Issue reproducible by changing unit test like so:

Screenshot 2024-08-08 at 12 50 21 PM

--- 

In the Objective-C implementation, `(nil, nil)` was being passed back by
getToken during timeouts.

https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/SystemService/FIRAuthAPNSTokenManager.m#L89-L95

This didn't cause issue though because the API calling getToken only checked for
the presence of a non-nil token:

https://github.com/firebase/firebase-ios-sdk/blob/eca84fd638116dd6adb633b5a3f31cc7befcbb7d/FirebaseAuth/Sources/AuthProvider/Phone/FIRPhoneAuthProvider.m#L613-L618

In Swift though, the catch block will implicitly unwrap error, leading to the
crash when error is nil due to the timeout:

https://github.com/firebase/firebase-ios-sdk/blob/a5c253d1b4409eb8aef4346015ba000f9935cb2d/FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift#L320-L326

Since the error doesn't bubble up, how we handle this is an implementation
detail and I think we could either (1) remove the catch block and use `try?`,
and trigger the catch block's code if the `try? await` results in nil. Or, (2)
pass an error in the timeout case so a non-nil error is unwrapped. I think (2)
is more future proof so I went with that in this PR. 

Fix #13470

### CODE REVIEW

File: FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift
Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift:1]: Migrating to Result type for internal completion handlers to remove the need to force unwrap an error in the checked continuation.

File: FirebaseAuth/CHANGELOG.md [hunk 1]
```diff
@@ -3,6 +3,8 @@
 - [added] Added custom provider support to `AuthProviderID`. Note that this change will be breaking
   to any code that implemented an exhaustive `switch` on `AuthProviderID` in 11.0.0 - the `switch`
   will need expansion. (#13429)
+- [fixed] Fix crash in phone authentication flow from implicitly unwrapping
```
Comment (paulb777) [inline FirebaseAuth/CHANGELOG.md:6]: How about 

```
- [fixed] Fix crash introduced in 11.0.0 in phone authentication flow from implicitly unwrapping
  `nil` error after a token timeout. (#13470)
```

**Review by paulb777 — APPROVED** [review]
Great fix. Thanks!

File: FirebaseAuth/CHANGELOG.md (hunk 1 above)
Comment (ncooke3) [reply FirebaseAuth/CHANGELOG.md]: Done, thanks!

File: FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift [hunk 2]
```diff
@@ -68,18 +68,19 @@
       kAuthGlobalWorkQueue.asyncAfter(deadline: deadline) {
         // Only cancel if the pending callbacks remain the same, i.e., not triggered yet.
         if applicableCallbacks.count == self.pendingCallbacks.count {
-          self.callback(withToken: nil, error: nil)
+          self.callback(.failure(AuthErrorUtils.missingAppTokenError(underlyingError: nil)))
```
Comment (snapxo) [inline FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift:71]: With this `AuthErrorUtils.missingAppTokenError(underlyingError: nil)`, the user of the SDK has no means to know that the request timed out, apart from implementing a timeout logic on their side, right?

Would it be a solution to add an underlying timeout Error?

Comment (ncooke3) [reply FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift:71]: Hi @snapxo, that's correct that the timeout error doesn't bubble up. This `getToken` API is called internally and in the case of an error (e.g. like from timeout), it actually attempts the recaptcha flow rather than bubble the error up to the user:

https://github.com/firebase/firebase-ios-sdk/blob/e76d7460aa3d19c5503a072f3117f69e2c443b11/FirebaseAuth/Sources/Swift/AuthProvider/PhoneAuthProvider.swift#L321-L326

Comment (snapxo) [reply FirebaseAuth/Sources/Swift/SystemService/AuthAPNSTokenManager.swift:71]: Makes sense if the fallback upon every `missingToken` error is the recaptcha 👌
