### PR TITLE
[RTDB] Fix Fatal Exception: FirebaseDatabasePersistenceFailure

### LINKED ISSUE #4493: Fatal Exception: FirebaseDatabasePersistenceFailure
* Xcode version: 11.1, iOS 13
  * Firebase SDK version: 6.10.0
  * Firebase Component: Analytics, Database, RemoteConfig

We're getting crashe almost immediately at startup since updating to 6.10.0. We use background bluetooth and it appears the crashes all were launches were due to bluetooth restoration.

```
Fatal Exception: FirebaseDatabasePersistenceFailure
0  CoreFoundation                 0x18dc3580c __exceptionPreprocess
1  libobjc.A.dylib                0x18d95dfa4 objc_exception_throw
2  MyFirebaseFramework    0x100e5df5c -[FLevelDBStorageEngine saveUserOverwrite:atPath:writeId:]
3  MyFirebaseFramework    0x100e5d92c -[FLevelDBStorageEngine openDatabases]
4  MyFirebaseFramework    0x100e5ceb8 -[FLevelDBStorageEngine initWithPath:]
5  MyFirebaseFramework    0x100e77f88 -[FRepo deferredInit]
6  libdispatch.dylib              0x18d902610 _dispatch_call_block_and_release
7  libdispatch.dylib              0x18d903184 _dispatch_client_callout
8  libdispatch.dylib              0x18d8af404 _dispatch_lane_serial_drain$VARIANT$mp
9  libdispatch.dylib              0x18d8afdf8 _dispatch_lane_invoke$VARIANT$mp
10 libdispatch.dylib              0x18d8b9314 _dispatch_workloop_worker_thread
11 libsystem_pthread.dylib        0x18d952f88 _pthread_wqthread
12 libsystem_pthread.dylib        0x18d955ad4 start_wqthread
```

```
Error initializing persistence: Error Domain=APLevelDBErrorDomain Code=0 "IO error: /var/mobile/Containers/Data/Application/B6E374D0-D5FD-478F-9CBB-26E73BA794C3/Documents/firebase/log/xxxxx.firebaseio.com_xxxxx/server_data/MANIFEST-000001: Operation not permitted" UserInfo={NSLocalizedDescription=IO error: /var/mobile/Containers/Data/Application/B6E374D0-D5FD-478F-9CBB-26E73BA794C3/Documents/firebase/log/xxxxx.firebaseio.com_xxxxx/server_data/MANIFEST-000001: Operation not permitted}
```

### PR DESCRIPTION
**Pull request by paulb777**
Fix #4493

### CODE REVIEW

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m
Comment (ncooke3) [inline FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:1]: When the directory already exists, it doesn't sound like the file protection attribute will be updated: ***true if createIntermediates is set and the directory already exists*** (from [docs](https://developer.apple.com/documentation/foundation/filemanager/createdirectory(atpath:withintermediatedirectories:attributes:)?language=objc:)).

To handle this case, I think we need to instead set the attribute via this API: https://developer.apple.com/documentation/foundation/filemanager/setattributes(_:ofitematpath:)?language=objc

File: FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m [hunk 1]
```diff
@@ -685,4 +688,49 @@ - (void)testRemoveTrackedQueryRemovesTrackedQueryKeys {
...
+  XCTAssertTrue([fileManager createDirectoryAtPath:testPath
+                       withIntermediateDirectories:YES
+                                        attributes:initialAttributes
+                                             error:&error],
+                @"Failed to create directory for update test: %@", error);
+
+  [FLevelDBStorageEngine ensureDir:testPath markAsDoNotBackup:NO];
+
+  attributes = [fileManager attributesOfItemAtPath:testPath error:&error];
+  XCTAssertNil(error, @"Failed to get attributes after update: %@", error);
```
[the remark this answers is not in the document]
Comment (paulb777) [reply FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m:728]: Asserts are already confirming it's nil

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m
Comment (paulb777) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:1]: Updated. PTAL

**Review by ncooke3 — APPROVED** [review]

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m [hunk 2]
```diff
@@ -977,18 +977,46 @@ - (id)deserializePrimitive:(NSData *)data {
...
+                         @"path" : path,
+                         @"error" : error ?: [NSNull null]
+                     }];
+    }
+
+#if TARGET_OS_IOS || TARGET_OS_TV || TARGET_OS_VISION || TARGET_OS_OSX ||      \
+    TARGET_OS_MACCATALYST
+    // Now, ensure the file protection attribute is set. This will apply it
+    // whether the directory was just created or already existed. This attribute
+    // is ignored on systems that do not support it.
```
Comment (ncooke3) [inline FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m]: It seems like it's supported everywhere: https://developer.apple.com/documentation/foundation/fileprotectiontype/completeuntilfirstuserauthentication?language=objc

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m [hunk 3]
```diff
@@ -977,18 +977,46 @@ - (id)deserializePrimitive:(NSData *)data {
...
+    NSDictionary *attributes = @{
+        NSFileProtectionKey :
+            NSFileProtectionCompleteUntilFirstUserAuthentication
+    };
+    success = [fileManager setAttributes:attributes
+                            ofItemAtPath:path
+                                   error:&error];
+    if (!success) {
+        // This is not a fatal error, as file protection may not be supported on
+        // all OS versions.
```
Comment (ncooke3) [inline FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m]: See above comment.

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m (hunk 2 above)
Comment (ncooke3) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m]:
```
iOS 5.0+ | iPadOS 5.0+ | Mac Catalyst 13.1+ | macOS 10.6+ | tvOS 9.0+ | visionOS 1.0+ | watchOS 2.0+
```

File: FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m
Comment (ncooke3) [reply FirebaseDatabase/Sources/Persistence/FLevelDBStorageEngine.m:1]: Thanks!

File: FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m [hunk 4]
```diff
@@ -685,4 +688,49 @@ - (void)testRemoveTrackedQueryRemovesTrackedQueryKeys {
                         ([NSSet setWithArray:@[ @"b", @"c" ]]));
 }
 
+- (void)testEnsureDirSetsCorrectFileProtection {
```
Comment (ncooke3) [inline FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m:691]: This test doesn't do anything on simulator, and I was unsuccessful at testing on a real device (ran into signing issues with CocoaPods and SwiftPM target needs a host app).

**Review by ncooke3 — APPROVED** [review]

File: FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m (hunk 4 above)
Comment (ncooke3) [reply FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m:691]: No action needed.

Comment (paulb777) [reply FirebaseDatabase/Tests/Unit/FLevelDBStorageEngineTests.m:691]: I verified on mac
