### PR TITLE
[Infra] Release testing should grab latest tag on any branch

### LINKED ISSUE #13737: Nightly Testing Report
# Nightly Testing Report
This issue([log](https://github.com/firebase/firebase-ios-sdk/actions/runs/11083719525)) is generated at 09/28/2024 05:03 AM, fetching workflow runs triggered in the last 24 hrs.
| Workflow |09/27|
| -------- | -------- |
| [storage](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/storage.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/11082301458) |
| [crashlytics](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/crashlytics.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/11080314717) |
| [sessions](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/sessions.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/11079950708) |

### PR DESCRIPTION
**Pull request by ncooke3**
Fix #13737

### CODE REVIEW

File: scripts/release_testing_setup.sh [hunk 1]
```diff
@@ -25,8 +25,12 @@ git fetch --tags --quiet origin main
...
 
 # The chunk below is to determine the latest version by searching
-# Get the latest released tag Cocoapods-X.Y.Z for release and prerelease testing, beta version will be excluded.
-test_version=$(git tag -l --sort=-version:refname --merged main 'CocoaPods-*[0-9]' | head -n 1)
+# Get the latest released tag Cocoapods-X.Y.Z for release and prerelease
+# testing, beta version will be excluded.
+# Note: If a long running release branch's tags are keeping the next tagged
+# release on main from being tested, add `--merged main` to the below git tag
+# command. Doing so will exclude tags that don't exist on main.
+test_version=$(git tag -l --sort=-version:refname 'CocoaPods-*[0-9]' | head -n 1)
```
Comment (paulb777) [inline scripts/release_testing_setup.sh:33]: My preference would be to keep `--merged main` along with a suggestion that if the nightly tag isn't updated to check that the CocoaPods tag is on the main branch.

Comment (ncooke3) [reply scripts/release_testing_setup.sh]: I see, thanks. Done.

File: scripts/release_testing_setup.sh [hunk 2]
```diff
@@ -25,8 +25,12 @@ git fetch --tags --quiet origin main
 git checkout main
 
 # The chunk below is to determine the latest version by searching
-# Get the latest released tag Cocoapods-X.Y.Z for release and prerelease testing, beta version will be excluded.
+# Get the latest released tag Cocoapods-X.Y.Z for release and prerelease
+# testing, beta version will be excluded.
+# Note: If the nightly tag was not updated, check that the next release's tag
+# is on the main branch.
 test_version=$(git tag -l --sort=-version:refname --merged main 'CocoaPods-*[0-9]' | head -n 1)
+
```
Comment (ncooke3) [inline scripts/release_testing_setup.sh:33]:
```suggestion
```

**Review by paulb777 — APPROVED** [review]
