### PR TITLE
Mute FCM deprecated warnings with Xcode 11 and min iOS >= 10

### LINKED ISSUE #3856: scheduleLocalNotification is deprecated
Environment

  * Xcode version: 11 GM
  * Firebase SDK version: 6.8.1
  * Firebase Component: Messaging
  * Component version: 4.1.4

Describe the problem

#### Steps to reproduce:

During compiling this warning appears:
```
'scheduleLocalNotification:' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNUserNotificationCenter addNotificationRequest:withCompletionHandler:]
```

#### Relevant Code:

[FIRMessagingContextManagerService.m:178](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Messaging/FIRMessagingContextManagerService.m#L178)

```
UIApplication *application = [GULAppDelegateSwizzler sharedApplication];
if (!application) {
    return;
}
[application scheduleLocalNotification:notification];
```

### PR DESCRIPTION
**Pull request by paulb777**
Fix #3856

### CODE REVIEW

File: Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m [hunk 1]
```diff
@@ -83,8 +83,10 @@ - (void)testMessageWithFutureStartTime {
   XCTAssertTrue([FIRMessagingContextManagerService handleContextManagerMessage:message]);
 
   XCTAssertEqual(self.scheduledLocalNotifications.count, 1);
-
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wdeprecated-declarations"
   UILocalNotification *notification = [self.scheduledLocalNotifications firstObject];
+#pragma pop
```
Comment (morganchen12) [inline Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m]: Should these all be `#pragma clang diagnostic pop`?

Comment (paulb777) [reply Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m]: Yep. And a few others. Thanks!
