### PR TITLE
Fix an issue that notification open is not logged when app is closed

### LINKED ISSUE #8128: open_notification event not being triggered when app is not in background.
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: [8.0.0](url)
  * Installation method: SPM
  * Firebase Component: Messaging

#### Steps to reproduce:

1. Force quit the app
2. Send a push notification to the app
3. Tap on the push notification
4. Observe Debug View

Expected: notification_open event gets triggered
Actual: No notification_event gets triggered

We are noticing that iOS is severely undercounting the push notification open rate. On Android, our open rate is around 12%. On iOS, our open rate is around 0.29%. However, evidence suggests that users ARE receiving push notifications and opening them on iOS (we see similar surges in traffic as Android), but just that the notification_open event is not getting triggered.

We have confirmed that swizzling is ON.

We have tested the following scenarios, each 5 times, and each reproduced 100%

- App is in the background, notification is received, notification_open is triggered
- App is closed, notification is received, notification_open is NOT triggered
- App is open in foreground, notification is received, notification_foreground is triggered correctly

We are monitoring the events via the DebugView.

Note that we recently updated to v8.0.0. However, we saw the same issue in the previous version of the SDK which was manually integrated.

### PR DESCRIPTION
**Pull request by chliangGoogle**
This fixes #8128 and #7707. Internal bug: b/157964197.

When app is completely closed and user taps on notification to open the app, the client SDK does not correctly capture the state to log notification open.

Also add analytics to sample app.

Added unit test and tested sending when app is closed, now notification_open is logged on analytics debug view console.

### CODE REVIEW

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m [hunk 1]
```diff
@@ -212,11 +216,34 @@ + (void)logMessage:(NSDictionary *)notification
...
++ (BOOL)isDisplayNotification:(NSDictionary *)notification {
+  NSDictionary *aps = notification[kApsKey];
+  if (!aps || ![aps isKindOfClass:[NSDictionary class]]) {
+    return NO;
+  }
+  NSDictionary *alert = aps[kApsAlertKey];
+  if (!alert) {
+    return NO;
+  }
+  if ([alert isKindOfClass:[NSDictionary class]]) {
```
Comment (paulb777) [inline FirebaseMessaging/Sources/FIRMessagingAnalytics.m:239]: How is it determined that the next two cases are the only ones that we want to log analytics for?

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m [hunk 2]
```diff
@@ -201,9 +202,12 @@ + (void)logMessage:(NSDictionary *)notification
...
   switch (applicationState) {
     case UIApplicationStateInactive:
-      // App was either in background(suspended) or inactive and user tapped on a display
-      // notification.
-      [self logOpenNotification:notification toAnalytics:analytics];
+      // App was in background and in transition to open when user tapped
+      // on a display notification.
+      // Needs to check notification is displayed.
+      if ([[self class] isDisplayNotification:notification]) {
+        [self logOpenNotification:notification toAnalytics:analytics];
```
Comment (paulb777) [inline FirebaseMessaging/Sources/FIRMessagingAnalytics.m:209]: From #8128, it sounds like we're not logging enough notifications to analytics.  Won't adding the conditional make the log count even less?

File: FirebaseMessaging/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,6 @@
+# unreleased
+- [fixed] Fixed an issue that notification open is not logged correctly when app is completely shut off. (#7707, #8128).
```
Comment (paulb777) [inline FirebaseMessaging/CHANGELOG.md:2]: "not logged to Analytics"

**Review by paulb777 — COMMENTED** [review]
Thanks!

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m [hunk 4]
```diff
@@ -212,11 +216,34 @@ + (void)logMessage:(NSDictionary *)notification
...
+      }
       break;
   }
 #endif
 }
 
++ (BOOL)isDisplayNotification:(NSDictionary *)notification {
```
Comment (maksymmalyhin) [inline FirebaseMessaging/Sources/FIRMessagingAnalytics.m:230]: Would you mind adding a comment to describe the expected dictionary format e.g. a link to docs or with a format like `@{ kApsKey : @{ kApsAlertKey : @"alert" } }`. I think it will be useful for future us.

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m [hunk 5]
```diff
@@ -212,11 +216,34 @@ + (void)logMessage:(NSDictionary *)notification
       break;
 
     default:
-      // Only a silent notification (i.e. 'content-available' is true) can be received while the app
-      // is in the background. These messages aren't loggable anyway.
+      // App was either in background state or in transition from closed
```
Comment (maksymmalyhin) [inline FirebaseMessaging/Sources/FIRMessagingAnalytics.m:219]: Would it be possible to add tests for the new logic to guard against regressions in the future?

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m [hunk 6]
```diff
@@ -212,11 +216,34 @@ + (void)logMessage:(NSDictionary *)notification
...
+      // to open.
+      // Needs to check notification is displayed.
+      if ([[self class] isDisplayNotification:notification]) {
+        [self logOpenNotification:notification toAnalytics:analytics];
+      }
```
Comment (maksymmalyhin) [inline FirebaseMessaging/Sources/FIRMessagingAnalytics.m:224]: Would it be possible to add tests for the new logic to guard against regressions in the future?

**Review by maksymmalyhin — APPROVED** [review]
LGTM, thank you for the fix! 

I'll be happy to help with additional tests if needed.

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m (hunk 1 above)
Comment (chliangGoogle) [reply FirebaseMessaging/Sources/FIRMessagingAnalytics.m:239]: We want to differentiate display notifications from hidden ones, so the field "alert" must exist and have at least one value in it.

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m (hunk 2 above)
Comment (chliangGoogle) [reply FirebaseMessaging/Sources/FIRMessagingAnalytics.m:209]: The reason that we are not logging enough notification open is we are missing the default condition below:
When app is open from shutdown state, this condition is no longer true but the default condition below, which is the background state. (btw, this is weird cuz we haven't changed the code for a long time)


Because of that, only the notifications open when app is in background is logged, not when it's shutdown state. The Application State names here are confusing but the condition did get hit to default state when app is open from shutdown state.

File: FirebaseMessaging/CHANGELOG.md (hunk 3 above)
Comment (chliangGoogle) [reply FirebaseMessaging/CHANGELOG.md:2]: Good call.

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m (hunk 6 above)
Comment (chliangGoogle) [reply FirebaseMessaging/Sources/FIRMessagingAnalytics.m:224]: I've added unit tests for isDisplayNotifications. 
Btw we have not changed this code for a long time, so I don't know if UIApplicationState has changed because I remember we used to be able to log with UIApplicationStateInactive state. We can mock the UIApplicationState, but for this scenario, we can't prevent regressions if system has some weird shift between these UIApplicationStates, but yeah feel free to add more tests if you see fit!

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m (hunk 2 above)
Comment (paulb777) [reply FirebaseMessaging/Sources/FIRMessagingAnalytics.m:209]: Thanks for the explanation!

**Review by paulb777 — APPROVED** [review]

File: FirebaseMessaging/Sources/FIRMessagingAnalytics.m (hunk 6 above)
Comment (chliangGoogle) [reply FirebaseMessaging/Sources/FIRMessagingAnalytics.m:224]: I will add in another PR to ensure we release in time.
