### PR TITLE
Fix Xcode 15 runtime warning

### LINKED ISSUE #11821: Runtime warning in FPRNSURLSessionInstrument when running on iOS 17 RC built with Xcode 15 RC
### Description

Similar to https://github.com/firebase/firebase-ios-sdk/issues/11536, a runtime warning as below occurs when running on iOS 17 RC built with Xcode 15 RC.

Warning:
```
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```
Code:
```c
/** Instruments -uploadTaskWithRequest:fromData:.
 *
 *  @param instrument The FPRNSURLSessionInstrument instance.
 *  @param instrumentor The FPRClassInstrumentor to add the selector instrumentor to.
 */
FOUNDATION_STATIC_INLINE
NS_EXTENSION_UNAVAILABLE("Firebase Performance is not supported for extensions.")
void InstrumentUploadTaskWithRequestFromData(FPRNSURLSessionInstrument *instrument,
                                             FPRClassInstrumentor *instrumentor) {
    ...
    NSURLSessionUploadTask *uploadTask =
        ((OriginalImp)currentIMP)(session, selector, request, bodyData); // This line causes the warning
    if (uploadTask.originalRequest) {
      FPRNetworkTrace *trace =
          [[FPRNetworkTrace alloc] initWithURLRequest:uploadTask.originalRequest];
      [trace start];
      trace.requestSize = bodyData.length;
      [trace checkpointState:FPRNetworkTraceCheckpointStateInitiated];
      [FPRNetworkTrace addNetworkTrace:trace toObject:uploadTask];
    }
    return uploadTask;
  }];
}
```

### Reproducing the issue

Run an app and check the runtime warnings on Xcode.

### Firebase SDK Version

10.9.0 (also occurred with 10.15.0)

### Xcode Version

15.0 (15A240d)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, App Distribution, Authentication, Crashlytics, DynamicLinks, Performance

### Targeted Platforms

iOS

### Relevant Log Output

```shell
The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by paulb777**
Fix #11821

### CODE REVIEW

File: FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m [hunk 1]
```diff
@@ -405,8 +405,12 @@ void InstrumentUploadTaskWithRequestFromData(FPRNSURLSessionInstrument *instrume
       ThrowExceptionBecauseInstrumentHasBeenDeallocated(selector, instrumentor.instrumentedClass);
     }
     typedef NSURLSessionUploadTask *(*OriginalImp)(id, SEL, NSURLRequest *, NSData *);
+    // To avoid a runtime warning in Xcode 15, the given `URLRequest`
+    // should have a nil `HTTPBody`. To workaround this, the `HTTPBody` data is removed.
+    NSMutableURLRequest *requestWithoutHTTPBody = [request mutableCopy];
+    requestWithoutHTTPBody.HTTPBody = nil;
```
Comment (visumickey) [inline FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:411]: Are we assuming that there would not be an HTTPBody? Since this is an upload request, I'm concerned that there could be an upload content in the HTTP request. Can we make it to be NIL only when the request does not contain a body?

Comment (visumickey) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:411]: Especially for the backward compatibility scenarios.

Comment (paulb777) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m]: Is the latest change what you mean?  Does it mean anything if both are non-nil?

Note the comparable fix from July https://github.com/google/GoogleUtilities/pull/114

Comment (visumickey) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m]: Yes, the feedback was on the latest change. But the new fix makes more sense to me. Thanks for changing it.

**Review by visumickey — APPROVED** [review]
