### PR TITLE
[storage] Migrate to actor to fix a potential data race in initialization

### LINKED ISSUE #13369: Potential data race in Storage method
### Description

image

### Reproducing the issue

Define a storage instance and call `storage.reference(forURL: String)` from multiple threads and sometimes the warn in Xcode happened.
image

```
 let task = Task {
            try await withCheckedThrowingContinuation { continuation in
                let storageReference = self.storage.reference(forURL: referencePath)
                storageReference.getData() { data, error in
                    if let error {
                        continuation.resume(throwing: error)
                        return
                    }
                    guard let data, !data.isEmpty else {
                        continuation.resume(throwing: Error.error)
                        return
                    }
                    continuation.resume(returning: data)
                }
            } as Data
        }

 return await task.value

```

### Firebase SDK Version

10.25.0

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by paulb777**
Fix #13369

Moves fetcherService to an actor

Not only should it fix the issue, the code and tests are more compact and readable.

Removed unnecessary `availability` checks that were incorrectly setting watchOS to 8

### CODE REVIEW

File: FirebaseStorage/Sources/StorageDownloadTask.swift [hunk 1]
```diff
@@ -93,99 +97,98 @@ open class StorageDownloadTask: StorageObservableTask, StorageTaskManagement {
...
 
   func cancel(withError error: NSError) {
     dispatchQueue.async { [weak self] in
       guard let self = self else { return }
       self.state = .cancelled
       self.fetcher?.stopFetching()
+      print("stopped fetching")
       self.error = error
       self.fire(for: .failure, snapshot: self.snapshot)
+      self.removeAllObservers()
```
Comment (paulb777) [inline FirebaseStorage/Sources/StorageDownloadTask.swift:191]: The integration tests had a success after cancel event. I believe this was a bug before.

File: FirebaseStorage/Sources/Storage.swift [hunk 2]
```diff
@@ -286,57 +273,13 @@ import FirebaseCore
     maxUploadRetryInterval = Storage.computeRetryInterval(fromRetryTime: maxUploadRetryTime)
   }
 
-  /// Map of apps to a dictionary of buckets to GTMSessionFetcherService.
-  private static let fetcherServiceLock = NSObject()
-  private static var fetcherServiceMap: [String: [String: GTMSessionFetcherService]] = [:]
-  private static var retryWhenOffline: GTMSessionFetcherRetryBlock = {
```
Comment (paulb777) [inline FirebaseStorage/Sources/Storage.swift:292]: Migrated  unchanged to the actor

**Review by ncooke3 — APPROVED** [review]

File: FirebaseStorage/Sources/Internal/StorageInternalTask.swift [hunk 3]
```diff
@@ -27,35 +27,35 @@ class StorageInternalTask: StorageTask {
...
 
     // Prepare a task and begins execution.
     dispatchQueue.async { [self] in
       self.state = .queueing
-      var request = request ?? self.baseRequest
-      request.httpMethod = httpMethod
-      request.timeoutInterval = self.reference.storage.maxOperationRetryTime
+      Task {
+        let fetcherService = await reference.storage.fetcherService
+          .fetcherService(reference.storage)
```
Comment (ncooke3) [inline FirebaseStorage/Sources/Internal/StorageInternalTask.swift:42]: optional/not urgent: This line makes me consider if `Storage` should even have a `fetcherService` property since it passes right through. I couldn't think of an obvious option, but a few to consider. Maybe an async var on one of the `StorageTask` class (or subclass) since they have has access to a `StorageReference`. It also may be worth making `StorageFetcherService` accessible via a singleton to prevent two classes from doing `StorageFetcherService()` and mirroring instance dictionaries.

File: FirebaseStorage/Sources/Internal/StorageFetcherService.swift [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+      fetcherService?.maxRetryInterval = storage.maxOperationRetryInterval
+      fetcherService?.testBlock = testBlock
+      let authorizer = StorageTokenAuthorizer(
+        googleAppID: app.options.googleAppID,
+        callbackQueue: storage.callbackQueue,
+        authProvider: storage.auth,
+        appCheck: storage.appCheck
+      )
+      fetcherService?.authorizer = authorizer
+      bucketMap?[storage.storageBucket] = fetcherService
```
[the remark this answers is not in the document]
Comment (paulb777) [reply FirebaseStorage/Sources/Internal/StorageFetcherService.swift:53]: Good catch! This has likely been an issue at least since the Swift migration. Fixed.

File: FirebaseStorage/Sources/Internal/StorageInternalTask.swift (hunk 3 above)
Comment (paulb777) [reply FirebaseStorage/Sources/Internal/StorageInternalTask.swift:42]: Interesting thought. I was trying to keep the behavior of a `fetcherService` per FirebaseApp, but not sure that's necessary.

Do you see a problem with multiple different instances of `StorageFetcherService`?

File: FirebaseStorage/Sources/Internal/StorageFetcherService.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (ncooke3) [reply FirebaseStorage/Sources/Internal/StorageFetcherService.swift:53]: Did you push the commit for this fix? The last one I see is da5e338

File: FirebaseStorage/Sources/Internal/StorageInternalTask.swift (hunk 3 above)
Comment (ncooke3) [reply FirebaseStorage/Sources/Internal/StorageInternalTask.swift:42]: > I was trying to keep the behavior of a fetcherService per FirebaseApp, but not sure that's necessary.

That SGTM. I was suggesting something like:

```suggestion
        let fetcherService = await reference.fetcherService
```
where in `StorageReference.swift`:
```swift
extension StorageReference {
   var fetcherService: GTMSessionFetcherService {
        get async {
            StorageFetcherService.shared.fetcherService(self.storage)
        }
    }
}
```
or maybe it fits better in `StorageTask.swift`:
```swift
extension StorageTask {
    var fetcherService: GTMSessionFetcherService {
        get async {
            StorageFetcherService.shared.fetcherService(self.reference.storage)
        }
    }
}
```

> Do you see a problem with multiple different instances of StorageFetcherService?

In practice, probably not, but IIUC multiple instances of an actor do not share synchronization so the static instance cache could have data races.

Comment (paulb777) [reply FirebaseStorage/Sources/Internal/StorageInternalTask.swift:42]: Oops, I left the Sources out of my last `git add`. Addressed in 6f2229dca

I'll do some more research, but we made need separate fetchers if there some of the FirebaseApps are running on the emulator and some on projects.

The static instance cache race is a possibility though ...

**Review by ncooke3 — APPROVED** [review]

**Comment by paulb777** [comment]
I'll merge here as incremental progress - and plan to address the `static`s in the new actor in a subsequent PR.
