### PR TITLE
Fix checking the result of malloc

### LINKED ISSUE #4871: VeraCode issues on GDTCCTNanopbHelpers.m
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version:  6.13.0
  * Firebase Component: GoogleDataTransportCCTSupport (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 1.2.1
  * Installation method: `CocoaPods ` 

#### Steps to reproduce:

VeraCode has found a low severity issues in GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m, called "Unchecked error condition ". The issue states that return value from malloc() is not been checked before been used in subsequent call.

#### Relevant Code:

<code>
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTEncodeData, line 41 (1 step)]
GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTConstructBatchedLogRequest, line 74 (1 step)]
GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m [Path 1: GDTCCTConstructLogRequest, line 104 (1 step)]
</code>

### LINKED ISSUE #4872: VeraCode issue in FIRCoreDiagnostics.m
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.13.0
  * Firebase Component: FirebaseCoreDiagnostics (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: (~> 1.0)
  * Installation method: `CocoaPods ` 

#### Steps to reproduce:

VeraCode has found a low severity issues in FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m, called **"Unchecked error condition "** and **"Use after Free".** 
Unchecked error condition issue states that return value from malloc() is not been checked before been used in subsequent call. 
Use after free issue states that variable reference occurs after its memory allocation has been freed. 

#### Relevant Code:

Unchecked error condition 
<code>
FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m [Path 1: FIREncodeData, line 269 (1 step)]
FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m    [Path 1: FIRPopulateProtoWithInstalledServices, line 541 (1 step)]  
</code>

Use after free 
<code>
FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m [Path 1: FIRPopulateProtoWithNumberOfLinkedFrameworks, line 573 (1 step)]
FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m [Path 1: FIRPopulateProtoWithNumberOfLinkedFrameworks, line 574 (1 step)]
</code>

### PR DESCRIPTION
**Pull request by mikehaney24**
Also make FIRCoreDiagnostics project generable again

Fixes #4871 
Fixes #4872

### CODE REVIEW

File: Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m [hunk 1]
```diff
@@ -510,6 +512,9 @@ void FIRPopulateProtoWithInstalledServices(logs_proto_mobilesdk_ios_ICoreConfigu
   logs_proto_mobilesdk_ios_ICoreConfiguration_ServiceType *servicesInstalled =
       malloc(sizeof(logs_proto_mobilesdk_ios_ICoreConfiguration_ServiceType) *
              sdkServiceInstalledArray.count);
+  if (servicesInstalled == NULL) {
+    return servicesInstalled;
```
Comment (morganchen12) [inline Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m]: tiniest of nits: It may be simpler here to explicitly return `logs_proto_mobilesdk_ios_ICoreConfiguration_ServiceType_UNKNOWN_SDK_SERVICE` instead of `servicesInstalled`.

Comment (mikehaney24) [reply Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m]: The failure isn't because the sdk service is unknown, it's because we couldn't allocate memory to serialize the sdkService array to a proto in memory. Also, I messed up and there shouldn't have been  a return value.
