### PR TITLE
Delete stale Firestore instances after FIRApp is deleted.

### LINKED ISSUE #683: Deleted App's Firestore Database Never Released
This is related to issue #160 which I believe was not fixed.

After getting a database reference and deleting the associated app, Firebase will always return the same instance to the initial database for an app's lifecycle. The instances array will hold an outdated reference of the database. This causes the database's authentication chain to break and the user will not be able to use the database even though it was created after deletion.

- Xcode version: Version 9.2 (9C40b)
- Swift version: Swift 4
- Firebase SDK version: 4.8.0
- Firestore version: 0.9.4
- Firebase Product: Firestore

**Steps to Reproduce**
1.) Create a Firebase app with a specific name.
2.) Print Firebase database reference.
3.) Delete the Firebase app.
4.) Wait until deletion completes
5.) Create a Firebase app using the same name used in step 1.
6.) Print Firebase database reference which will match step 2 but should be different.
7.) Try authenticating against database in step 5 and fails permissions.

**Code to Reproduce**
```
DispatchQueue.main.async {
  FirebaseApp.configure(name: "abc123", options: options)
  let app = FirebaseApp.app(name: "abc123")
  print("Firebase app: \(app!)") //<FIRApp: 0x600000a42760> **GOOD
  print("Firebase database: \(Firestore.firestore(app: app!))") //<FIRFirestore: 0x6040008880c0> **GOOD
  app!.delete { _ in print("Done delete") }
}
        
DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
  FirebaseApp.configure(name: "abc123", options: options)
  let app = FirebaseApp.app(name: "abc123")
  print("Firebase app: \(app!)") //<FIRApp: 0x600000456e60> **GOOD
  print("Firebase database: \(Firestore.firestore(app: app!))") //<FIRFirestore: 0x6040008880c0> **BAD!!
}
```

Notice the Firebase database memory location printed before and after deletion is the same, even though it was recreated. The database isn't usable again until the app is killed and restarted.

After running `app.delete`, it should remove the database reference so it will be recreated fresh the next time.

### PR DESCRIPTION
**Pull request by ryanwilson**
This fixes #683.

### CODE REVIEW

File: Firestore/Source/API/FIRFirestore.mm [hunk 1]
```diff
@@ -80,6 +80,35 @@ @implementation FIRFirestore {
   return instances;
 }
 
++ (void)load {
```
Comment (wilhuff) [inline Firestore/Source/API/FIRFirestore.mm]: This would likely be better off in `+initialize` rather than `+load`. If a user never calls Firestore we shouldn't register.

File: Firestore/Example/Tests/API/FIRFirestoreTests.mm [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+  XCTestExpectation *defaultAppDeletedExpectation =
+      [self expectationWithDescription:
+                @"Deleting the default app should invalidate the default "
+                @"Firestore instance."];
+  [app deleteApp:^(BOOL success) {
+    // Recreate the FIRApp with the same name, fetch a new Firestore instance and make sure it's
+    // different than the other one.
+    [FIRApp configureWithName:appName options:options];
+    FIRApp *newApp = [FIRApp appNamed:appName];
+    FIRFirestore *newInstance = [FIRFirestore firestoreForApp:newApp];
```
Comment (wilhuff) [inline Firestore/Example/Tests/API/FIRFirestoreTests.mm]: Please add a check that verifies `[FIRFirestore firestoreForApp:app]` returns the same instance above.

File: Firestore/Source/API/FIRFirestore.mm [hunk 3]
```diff
@@ -80,6 +80,35 @@ @implementation FIRFirestore {
...
+                    if (appName == nil) return;
+
+                    NSMutableDictionary *instances = [self instances];
+                    @synchronized(instances) {
+                      // Since the key for instances isn't just the app name, iterate over all the
+                      // keys to get the one(s) we have to delete. There could be multiple in case
+                      // the user calls firestoreForApp:database:.
+                      NSMutableArray *keysToDelete = [[NSMutableArray alloc] init];
+                      for (NSString *key in instances.allKeys) {
+                        if ([key hasPrefix:appName]) {
```
Comment (wilhuff) [inline Firestore/Source/API/FIRFirestore.mm]: Please add a comment to the key construction code that notes that the app name must be the prefix for the key or deletion will break.

Also, this is broken if you have delete an app whose name is a prefix of another app name.

**Comment by paulb777** [comment]
Why is delete special for Firestore?   Wouldn't other components want the same thing and there be a FIRApp implementation?

File: Firestore/Example/Tests/API/FIRFirestoreTests.mm (hunk 2 above)
Comment (ryanwilson) [reply Firestore/Example/Tests/API/FIRFirestoreTests.mm]: I'm not quite sure what you mean - do you mean call `[FIRFirestore firestoreForApp:]` twice and ensure the same instance is returned?

File: Firestore/Source/API/FIRFirestore.mm (hunk 1 above)
Comment (ryanwilson) [reply Firestore/Source/API/FIRFirestore.mm]: Good call, will change.

File: Firestore/Source/API/FIRFirestore.mm (hunk 3 above)
Comment (ryanwilson) [reply Firestore/Source/API/FIRFirestore.mm]: Good idea, fixed the prefix issue too.

**Comment by ryanwilson** [comment]
@paulb777 right now FIRApp just fires a notification for other SDKs to handle - [Database](https://github.com/firebase/firebase-ios-sdk/blob/aa6f1ae0993ed948fb0b39283561bb3321eea5e9/Firebase/Database/Api/FIRDatabase.m#L52) and [Auth](https://github.com/firebase/firebase-ios-sdk/blob/aa6f1ae0993ed948fb0b39283561bb3321eea5e9/Firebase/Auth/Source/FIRAuth.m#L293) do similar things as well.

Once Core takes over the management of instances, this code should be able to go away.

File: Firestore/Example/Tests/API/FIRFirestoreTests.mm (hunk 2 above)
Comment (wilhuff) [reply Firestore/Example/Tests/API/FIRFirestoreTests.mm]: Yes that's what I mean (at line ~40). It makes it possible to know that the `XCTAssertNotEqualObjects(newInstance, firestore)` is meaningful here because `XCTAssertEqualObjects(newInstance, firestore)` was true absent this work.
