### PR TITLE
release-6.6.0 fix #2 for GDTUploadCoordinator crashes

### LINKED ISSUE #2: Add robot webook
URL:
https://us-central1-ossbot-f0cad.cloudfunctions.net/githubWebhook

Content type:
application/json

Secret: 
N/A

Select individual events:
  * Issues
  * Pull request
  * Issue comment

### PR DESCRIPTION
**Pull request by mikehaney24**

### CODE REVIEW

**Comment by mikehaney24** [comment]
> Would you like to bump the pod version in this PR as well?

Yes. <curses myself>

File: GoogleDataTransport/GDTLibrary/GDTStorage.m [hunk 1]
```diff
@@ -246,10 +246,25 @@ - (instancetype)initWithCoder:(NSCoder *)aDecoder {
...
+  }
+  dispatch_sync(storageQueue, ^{
+    NSMutableOrderedSet<GDTStoredEvent *> *storedEvents = sharedInstance->_storedEvents;
+    if (storedEvents) {
+      [aCoder encodeObject:storedEvents forKey:kGDTStorageStoredEventsKey];
+    }
+    NSMutableDictionary<NSNumber *, NSMutableSet<GDTStoredEvent *> *> *targetToEventSet =
+        sharedInstance->_targetToEventSet;
+    if (targetToEventSet) {
+      [aCoder encodeObject:sharedInstance->_targetToEventSet forKey:kGDTStorageTargetToEventSetKey];
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTStorage.m]: s/sharedInstance->_targetToEventSet/targetToEventSet/

File: GoogleDataTransport/GDTLibrary/GDTStorage.m [hunk 2]
```diff
@@ -246,10 +246,25 @@ - (instancetype)initWithCoder:(NSCoder *)aDecoder {
...
+    }
+    GDTUploadCoordinator *uploadCoordinator = sharedInstance->_uploadCoordinator;
+    if (uploadCoordinator) {
+      [aCoder encodeObject:sharedInstance->_uploadCoordinator
+                    forKey:kGDTStorageUploadCoordinatorKey];
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTStorage.m]: uploadCoordinator

File: GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m [hunk 3]
```diff
@@ -208,32 +208,54 @@ - (void)appWillTerminate:(GDTApplication *)application {
 #pragma mark - GDTUploadPackageProtocol
 
 - (void)packageDelivered:(GDTUploadPackage *)package successful:(BOOL)successful {
-  dispatch_async(_coordinationQueue, ^{
+  dispatch_queue_t coordinationQueue = _coordinationQueue;
+  if (!_coordinationQueue) {
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m]: I don't understand this one - since it's synchronous in an instance method

File: GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m [hunk 4]
```diff
@@ -208,32 +208,54 @@ - (void)appWillTerminate:(GDTApplication *)application {
...
+      }
     }
     [self.storage removeEvents:package.events];
   });
 }
 
 - (void)packageExpired:(GDTUploadPackage *)package {
-  dispatch_async(_coordinationQueue, ^{
+  dispatch_queue_t coordinationQueue = _coordinationQueue;
+  if (!_coordinationQueue) {
```
Comment (paulb777) [inline GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m]: same

File: GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m (hunk 3 above)
Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m]: it could probably be replaced with just a check to see if non-nil.

Comment (mikehaney24) [reply GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m]: the check here was also wrong.
