### PR TITLE
Use sign up endpoint for link with email password

### LINKED ISSUE #11911: Anonymous Auth Verify Can't Connect Account for Email / Password
### Description

# Expected
Using Firebase anonymous authentication, and allowing a user to sign up with email / password to create their "permanent account"

# Actual
Using Firebase anonymous authentication I am able to have an anonymous user, but then using Email / Password sign up and connecting the anonymous user to this info, it fails with the error "Please verify the new email before changing email"

### Reproducing the issue

I was mostly following this example Firebase code, the `auth-account-linking` example, but when trying to sign in I would get the error "Please verify the new email before changing email" Sorry I don't have a full test project at the moment.

I was only doing anonymous auth and Email / password, not using Sign in With Apple or Google

[Favourites.zip](https://github.com/firebase/firebase-ios-sdk/files/12838400/Favourites.zip)

### Firebase SDK Version

10.15

### Xcode Version

15.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by renkelvin**
Fix #11911

### CODE REVIEW

**Comment by renkelvin** [comment]
Working on fixing the ci.

File: FirebaseAuth/Sources/User/FIRUser.m [hunk 1]
```diff
@@ -1098,15 +1104,107 @@ - (void)linkWithCredential:(FIRAuthCredential *)credential
...
-        [self updateEmail:emailPasswordCredential.email
-                 password:emailPasswordCredential.password
-                 callback:^(NSError *error) {
-                   if (error) {
-                     callInMainThreadWithAuthDataResultAndError(completion, nil, error);
-                   } else {
-                     callInMainThreadWithAuthDataResultAndError(completion, result, nil);
-                   }
-                 }];
+        [self internalGetTokenWithCallback:^(NSString *_Nullable accessToken,
```
Comment (paulb777) [inline FirebaseAuth/Sources/User/FIRUser.m:1107]: Can you explain a bit why so much code has to change here? I thought we only needed to call a different backend API?

Comment (renkelvin) [reply FirebaseAuth/Sources/User/FIRUser.m:1107]: Sure. Basically `updateEmail` is used in other places (like profile change) as well, so we can't just update its underlying backend API. Here, I reimplement the full flow to switch to`signUp` endpoint.

File: FirebaseAuth/Sources/User/FIRUser.m [hunk 2]
```diff
@@ -145,6 +147,11 @@
  */
 static NSString *const kMissingUsersErrorMessage = @"users";
 
+/** @var kMissingRecaptchaTokenErrorPrefix
+    @brief The prefix of the error message of missing recaptcha token during authenticating.
+ */
+static NSString *const kMissingRecaptchaTokenErrorPrefix = @"MISSING_RECAPTCHA_TOKEN";
```
Comment (prameshj) [inline FirebaseAuth/Sources/User/FIRUser.m:153]: Can we reuse https://github.com/firebase/firebase-ios-sdk/blob/760d449145a4eb7b860c5b8bf5f199c91419e8a4/FirebaseAuth/Sources/Auth/FIRAuth.m#L171?

File: FirebaseAuth/Sources/User/FIRUser.m (hunk 1 above)
Comment (prameshj) [reply FirebaseAuth/Sources/User/FIRUser.m:1107]: Can we pull this into an internal "linkWithEmailCredential" method? Or can we reuse the signUp method in https://github.com/firebase/firebase-ios-sdk/blob/0c8d1433b84e0c81e19f4987568c7b80027111a9/FirebaseAuth/Sources/Auth/FIRAuth.m#L1990 to pass the new callback and make that method accept idToken as an optional param?

Since this method already has several cases (emailAuthCredential (with and without password), other types of credentials), i think making/reusing a helper method would be great.

File: FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m [hunk 3]
```diff
@@ -60,6 +60,16 @@
...
 
+/** @var kIDTokenKey
+    @brief the name of the "kIDTokenKey" property in the request.
+ */
+static NSString *const kIDTokenKey = @"idToken";
+
+/** @var kTestIDToken
+    @brief Testing id token.
+ */
+static NSString *const kTestIDToken = @"IDToken";
```
Comment (prameshj) [inline FirebaseAuth/Tests/Unit/FIRSignUpNewUserRequestTests.m:71]: super nit: Make the value as "testIDToken"?

**Review by paulb777 — APPROVED** [review]
Please add a changelog.

Can this PR be marked as fixing #11911?

File: FirebaseAuth/Sources/User/FIRUser.m (hunk 1 above)
Comment (renkelvin) [reply FirebaseAuth/Sources/User/FIRUser.m:1107]: Pulled in to a helper method. Gonna create a helper method to handle the recaptcha related flows in a separate pr like what we plan to do in web.

It's hard to reuse the signUp method since linking is a user method while sign up is an auth method so there are many differences .

**Comment by renkelvin** [comment]
> Please add a changelog.
> 
> Can this PR be marked as fixing #11911?

Yeah.

File: FirebaseAuth/Sources/User/FIRUser.m (hunk 1 above)
Comment (paulb777) [reply FirebaseAuth/Sources/User/FIRUser.m]: I was able to use a helper method for most of the recaptcha flows in Swift in https://github.com/firebase/firebase-ios-sdk/pull/11942/files#diff-df7cc3b7882f0d0525d338279d734310f97c320a9af8e86265d2d7430b8086fa. It will be trickier in ObjC, but some of the ideas might apply.

**Review by prameshj — APPROVED** [review]
Please include any end to end testing that was done. Thanks!

File: FirebaseAuth/Sources/User/FIRUser.m (hunk 1 above)
Comment (renkelvin) [reply FirebaseAuth/Sources/User/FIRUser.m]: Cool, thanks Paul!
