### PR TITLE
Fix #14273: Prevent race condition crash in FPRTraceBackgroundActivityTracker

### LINKED ISSUE #14273: Crash at FPRTraceBackgroundActivityTracker.m
### Crash at FPRTraceBackgroundActivityTracker.m

Here is stacktrace

```
          Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x9748 objc_moveWeak + 196
1  CoreFoundation                 0x50a94 _CFXNotificationRegistrarAddObserver + 392
2  CoreFoundation                 0x4f864 CFXNotificationRegistrarAdd + 580
3  CoreFoundation                 0x4f040 _CFXNotificationRegisterObserver + 248
4  FirebasePerformance            0x1c9f4 __41-[FPRTraceBackgroundActivityTracker init]_block_invoke + 44 (FPRTraceBackgroundActivityTracker.m:44)
5  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
7  libdispatch.dylib              0x125a4 _dispatch_main_queue_drain + 988
8  libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF + 44
9  CoreFoundation                 0x56710 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10 CoreFoundation                 0x53914 __CFRunLoopRun + 1996
11 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
12 GraphicsServices               0x11a8 GSEventRunModal + 164
13 UIKitCore                      0x40a90c -[UIApplication _run] + 888
14 UIKitCore                      0x4be9d0 UIApplicationMain + 340
15 App                          0x844f4 main + 36 (KAAppDelegate.swift:36)
16 ???                            0x1c3b51e4c (Missing)
```

### Reproducing the issue

We don't know a 100% way to reproduce it, but looks like the crash happens when user moves app to background and then back to the foreground

### Firebase SDK Version

11.6.0

### Xcode Version

16.1

### Installation Method

CocoaPods

### Firebase Product(s)

Performance, Crashlytics, Remote Config, Analytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by JesusRojass**
Replace async notification observer registration with synchronous registration
to eliminate timing-dependent crashes when objects are deallocated quickly.

Fixes #14273 ([Link](https://github.com/firebase/firebase-ios-sdk/issues/14273))

### Discussion

The FPRTraceBackgroundActivityTracker class had a race condition during initialization where notification observers were registered asynchronously using dispatch_async(dispatch_get_main_queue()). This created a timing window where the tracker object could be deallocated before the async block executed, causing crashes when the block tried to call addObserver: with a deallocated self reference.

The crash occurred when:
- FPRTraceBackgroundActivityTracker is created
- Async observer registration is queued to main thread
- Object is deallocated before async block executes
- Async block runs with dangling self pointer → EXC_BAD_ACCESS

My solution involves to replace the asynchronous observer registration with synchronous registration to eliminate the race condition entirely

### Testing

- Added testRapidCreationAndDeallocation_noRaceCondition to verify fix
- Added thread safety tests for background thread initialization
- Added crash reproduction test class to demonstrate original bug
- All existing tests continue to pass

### API Changes

  * No API Changes

### CODE REVIEW

**Comment by JesusRojass** [comment]
@visumickey Created PR Here

File: FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m [hunk 1]
```diff
@@ -35,21 +35,29 @@ - (instancetype)init {
...
+    } else {
+      dispatch_sync(dispatch_get_main_queue(), ^{
+        [self registerNotificationObservers];
+      });
+    }
   }
   return self;
 }
 
+- (void)registerNotificationObservers {
```
[the remark this answers is not in the document]
Comment (JesusRojass) [reply FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m:51]: /gemini review

I added suggestion

**Comment by JesusRojass** [comment]
@visumickey you can review from here, I added some of the Gemini suggestions (though idk if they where any good)

lmk if anything!

File: FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m [hunk 2]
```diff
@@ -35,21 +37,29 @@ - (instancetype)init {
...
-
-      [[NSNotificationCenter defaultCenter] addObserver:self
-                                               selector:@selector(applicationDidEnterBackground:)
-                                                   name:UIApplicationDidEnterBackgroundNotification
-                                                 object:[UIApplication sharedApplication]];
-    });
+    if ([NSThread isMainThread]) {
+      [self registerNotificationObservers];
+    } else {
+      dispatch_sync(dispatch_get_main_queue(), ^{
```
Comment (visumickey) [inline FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m]: I'm worried about a potential deadlock situation here. If we are already in the main thread and doing a dispatch_sync, that is going to cause a deadlock. I think we should protect against that.

File: FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m [hunk 3]
```diff
@@ -61,4 +61,82 @@ - (void)testBackgroundTracking {
...
+  tracker = nil;
+  XCTAssertNil(tracker);
+  XCTAssertNoThrow([notificationCenter postNotificationName:UIApplicationDidBecomeActiveNotification
+                                                     object:[UIApplication sharedApplication]]);
+  XCTAssertNoThrow([notificationCenter
+      postNotificationName:UIApplicationDidEnterBackgroundNotification
+                    object:[UIApplication sharedApplication]]);
+}
+
+/** Tests rapid creation and deallocation to verify race condition fix. */
```
Comment (eBlender) [inline FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m]: NIT: Remove "fix" since this is supposed to be a permanent test.

File: FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m (hunk 2 above)
Comment (eBlender) [reply FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m]: x2, my understating of this issue is not on the threads but if the observers are still alive when the app transition from states, I was proposing something like 

If (observers != nil){
//don't do anything 
}  
esle {
//Create them
}

WDYT @visumickey ??

File: FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m [hunk 4]
```diff
@@ -61,4 +61,82 @@ - (void)testBackgroundTracking {
...
+  XCTAssertTrue([NSThread isMainThread]);
+
+  FPRTraceBackgroundActivityTracker *tracker = [[FPRTraceBackgroundActivityTracker alloc] init];
+
+  [[NSNotificationCenter defaultCenter]
+      postNotificationName:UIApplicationDidBecomeActiveNotification
+                    object:[UIApplication sharedApplication]];
+
+  XCTAssertEqual(tracker.traceBackgroundState, FPRTraceStateForegroundOnly);
+}
```
[the remark this answers is not in the document]
Comment (eBlender) [reply FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m]: NIT:We usually don't want to duplicate code, if possible try to make it a single tests, so we don't have to maintain extra tests.

File: FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m (hunk 3 above)
Comment (JesusRojass) [reply FirebasePerformance/Tests/Unit/FPRTraceBackgroundActivityTrackerTest.m]: done

File: FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m (hunk 2 above)
Comment (JesusRojass) [reply FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m]: @visumickey @eBlender

I have made a new commit addressing this block of code 

The approach is to capture strong self during async observer registration so we can avoid messaging deallocated tracker instances when observers are registered asynchronously on the main queue

Just so self lives long enough to prevent another EXC_BAD_ACCESS crash

lmk what you think

**Comment by JesusRojass** [comment]
@visumickey Made new changes and added commit, I also re tested everything and it seems fine

Screenshot 2025-10-06 at 4 43 59 p m

File: FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m [hunk 5]
```diff
@@ -35,21 +37,26 @@ - (instancetype)init {
...
-      [[NSNotificationCenter defaultCenter] addObserver:self
-                                               selector:@selector(applicationDidBecomeActive:)
-                                                   name:UIApplicationDidBecomeActiveNotification
-                                                 object:[UIApplication sharedApplication]];
-
-      [[NSNotificationCenter defaultCenter] addObserver:self
-                                               selector:@selector(applicationDidEnterBackground:)
-                                                   name:UIApplicationDidEnterBackgroundNotification
-                                                 object:[UIApplication sharedApplication]];
+      [strongSelf registerNotificationObservers];
```
Comment (visumickey) [inline FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m]: Just add a check before making the call to the registerNotificationObservers.

For eg;
`
if (strongSelf) {
  [strongSelf registerNotificationObservers];
}
`

Comment (JesusRojass) [reply FirebasePerformance/Sources/AppActivity/FPRTraceBackgroundActivityTracker.m]: Done and addressed lmk what you think
