### PR TITLE
Fix assign default on fetcherCompletion

### LINKED ISSUE #1565: fetcherCompletion is assign
`@property(readonly) GTMSessionFetcherCompletionHandler fetcherCompletion;`

This property is using default assign, so fetcherCompletion will may be released to case a wild pointer and `EXC_BAD_ACCESS` crash.

In the file `FIRStorageDownloadTask.m`, there is a assignment for `fetcherCompletion` :
```
_fetcherCompletion = ^(NSData *data, NSError *error) {
      ......
};
```

And at the end of this scope, there is a fetch: 
```
[self.fetcher beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
    weakSelf.fetcherCompletion(data, error);
  }];
```
Because this fetch is async, when ` weakSelf.fetcherCompletion` calls, the temporary scope in which fetcherCompletion is assigned has gone. `fetcherCompletion` become a bad memory.

### PR DESCRIPTION
**Pull request by morganchen12**
Fixes #1565.

### CODE REVIEW

**Comment by paulb777** [comment]
From travis: Run scripts/style.sh and git add the result.

File: Firebase/Storage/FIRStorageDeleteTask.m [hunk 1]
```diff
@@ -51,20 +51,21 @@ - (void)enqueue {
...
-#pragma clang diagnostic ignored "-Warc-retain-cycles"
+  __weak FIRStorageDeleteTask *weakSelf = self;
   _fetcherCompletion = ^(NSData *_Nullable data, NSError *_Nullable error) {
-    if (!self.error) {
-      self.error = [FIRStorageErrors errorWithServerError:error reference:self.reference];
-    }
-    if (callback) {
-      callback(self.error);
+    __strong FIRStorageDeleteTask *strongSelf = weakSelf;
+    if (strongSelf != nil) {
```
Comment (schmidt-sebastian) [inline Firebase/Storage/FIRStorageDeleteTask.m]: Nit: I don't feel strongly, but rest of the code mostly uses `if(var)` for nil checks.
