### PR TITLE
Fix threading issue with ivar access in GDTCORUploadCoordinator

### LINKED ISSUE #4019: GDTCORUploadCoordinator uploadTargets
* Xcode version: 10.2
  * Firebase SDK version: 6.9.0
Using FirebaseAnalytics (6.1.2)
Using FirebaseAuth (6.2.3)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.3.0)
Using FirebaseCoreDiagnostics (1.1.0)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseDatabase (6.1.0)
Using FirebaseInstanceID (4.2.5)
Using FirebaseStorage (3.4.1)
Using GoogleDataTransport (2.0.0)
Using GoogleDataTransportCCTSupport (1.1.0)

User have started to have crashes on:
GDTCORUploadCoordinator.m line 111
__52-[GDTCORUploadCoordinator uploadTargets:conditions:]_block_invoke

Here is Crashlytics report:
[com.firstduesizeup.fdsu_issue_crash_0b591ccc63a844cf961b2f9c23709081_DNE_0_v2.txt](https://github.com/firebase/firebase-ios-sdk/files/3702751/com.firstduesizeup.fdsu_issue_crash_0b591ccc63a844cf961b2f9c23709081_DNE_0_v2.txt)

### PR DESCRIPTION
**Pull request by mikehaney24**
Fixes #4019 

Also fixes a main-thread access issues in the test app.

### CODE REVIEW

File: GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m [hunk 1]
```diff
@@ -163,23 +163,27 @@ + (BOOL)supportsSecureCoding {
 
 - (instancetype)initWithCoder:(NSCoder *)aDecoder {
   GDTCORUploadCoordinator *sharedCoordinator = [GDTCORUploadCoordinator sharedInstance];
-  @try {
-    sharedCoordinator->_targetToInFlightPackages =
-        [aDecoder decodeObjectOfClass:[NSMutableDictionary class]
-                               forKey:ktargetToInFlightPackagesKey];
+  dispatch_sync(sharedCoordinator->_coordinationQueue, ^{
```
Comment (maksymmalyhin) [inline GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m]: I remember we had a case when using  `dispatch_sync` in coder methods led to a deadlock. It looks safe here, but just would like to double check if you can see a case when the deadlock may occur?

Comment (mikehaney24) [reply GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m]: I looked in the history and didn't think this was one of the affected places. I tested using test apps and it generally looked ok.
