### PR TITLE
[Auth] Forward secure coding calls for TOTPMultiFactorInfo

### LINKED ISSUE #13591: Critical bug FirebaseAuth.TOTPMultiFactorInfo in v11.0.0 - v11.1.0
### Description

I get this error when I login with TOTP -> 

`Class 'FirebaseAuth.TOTPMultiFactorInfo' has a superclass that supports secure coding, but 'FirebaseAuth.TOTPMultiFactorInfo' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant.`

I tested it in versions 11.0.0 - 11.1.0 and I use Google Authenticator. I had to downgrade to 10.29.0 in order to login with TOTP.

### Reproducing the issue

Install v11.0.0 and sign in with TOTPMultiFactorInfo (Authenticator app). 

### Firebase SDK Version

11.0.0-11.1.0

### Xcode Version

15.4

### Installation Method

CocoaPods

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Class 'FirebaseAuth.TOTPMultiFactorInfo' has a superclass that supports secure coding, but 'FirebaseAuth.TOTPMultiFactorInfo' overrides -initWithCoder: and does not override +supportsSecureCoding. The class must implement +supportsSecureCoding and return YES to verify that its implementation of -initWithCoder: is secure coding compliant.
```

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

- Firebase/AnalyticsWithoutAdIdSupport (11.0.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 11.0.0)
  - Firebase/CoreOnly (11.0.0):
    - FirebaseCore (= 11.0.0)
  - FirebaseABTesting (11.1.0):
    - FirebaseCore (~> 11.0)
  - FirebaseAnalytics/WithoutAdIdSupport (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleAppMeasurement/WithoutAdIdSupport (= 11.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAppCheckInterop (11.1.0)
  - FirebaseAuth (11.0.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseCoreExtension (~> 11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GTMSessionFetcher/Core (~> 3.4)
    - RecaptchaInterop (~> 100.0)
  - FirebaseAuthInterop (11.1.0)
  - FirebaseCore (11.0.0):
    - FirebaseCoreInternal (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Logger (~> 8.0)
  - FirebaseCoreExtension (11.1.0):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.1.0):
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseCrashlytics (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSessions (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - FirebaseInstallations (11.1.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebasePerformance (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfig (~> 11.0)
    - FirebaseSessions (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebaseRemoteConfig (11.1.0):
    - FirebaseABTesting (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSharedSwift (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseRemoteConfigInterop (11.1.0)
  - FirebaseSessions (11.1.0):
    - FirebaseCore (~> 11.0)
    - FirebaseCoreExtension (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesSwift (~> 2.1)
  - FirebaseSharedSwift (11.1.0)

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
Fix #13591

- Remove unneeded `totpInfo` property because it's not used. The property on `AuthProtoMFAEnrollment` is enough (e.g. `git grep "\.totpInfo" -- FirebaseAuth/Sources/Swift`. https://github.com/firebase/firebase-ios-sdk/blob/ed4269b40ceb932f82132032722fa2f6fd91c0d1/FirebaseAuth/Sources/Swift/Backend/RPC/Proto/AuthProtoMFAEnrollment.swift#L19

---

```console
nickcooke@nickcooke-mac firebase-3 % git grep "\.totpInfo" -- FirebaseAuth/Sources/Swift
FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:          } else if let _ = enrollment.totpInfo {
FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift:        } else if enrollment.totpInfo != nil {
```

### CODE REVIEW

File: FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift
Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift:1]: need changelog

Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift:1]: Despite being marked unavailable, this class's `init?(coder:)` is actually called when totp is registered: https://github.com/firebase/firebase-ios-sdk/blob/60b6dd591e1e24ede5a82b8e1b2fa44c807da4c8/FirebaseAuth/Sources/Swift/MultiFactor/MultiFactor.swift#L289

**Review by paulb777 — APPROVED** [review]
Thanks!

Will need to be cherry-picked to 11.2 branch as well.

**Comment by ncooke3** [comment]
I'm not sure now is the time to address it, but `TOTPMultiFactorInfo` is not public but `PhoneMultiFactorInfo` is. This also applies to 10.29.0.

File: FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift [hunk 1]
```diff
@@ -22,19 +22,22 @@ import Foundation
   ///
   /// This class is available on iOS only.
   class TOTPMultiFactorInfo: MultiFactorInfo {
-    /// This is the totp info for the second factor.
-    let totpInfo: NSObject?
```
Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/MultiFactor/TOTP/TOTPMultiFactorInfo.swift:26]: Typing this with a more specific type (dictionary) added a more code to cast it during encoding and decoding. I stepped back and see that this property is never read from (it's only read from from the `AuthProtoMFAEnrollment.swift` class). I think it's better to just remove it as it's addition is more confusing.

File: FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift [hunk 2]
```diff
@@ -71,7 +71,7 @@ class FakeBackendRPCIssuer: NSObject, AuthBackendRPCIssuer {
   var respondBlock: (() throws -> Void)?
   var nextRespondBlock: (() throws -> Void)?
 
-  var fakeGetAccountProviderJSON: [[String: AnyHashable]]?
+  var fakeGetAccountProviderJSON: [[String: Any]]?
```
Comment (ncooke3) [inline FirebaseAuth/Tests/Unit/Fakes/FakeBackendRPCIssuer.swift:74]: Needed for FirebaseAuth/Tests/Unit/UserTests.swift to compile.

**Comment by ncooke3** [comment]
I was able to successfully enroll via TOTP in the sample app using these changes.
