### PR TITLE
Fix Xcode 13 beta 3 build issues

### LINKED ISSUE #6548: Build errors w.r.t FIRDynamicLinks
Xcode: 11.3
Swift Version 4.0

Cocoapods:
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'    

Successfully integrated the firebase sdk via cocoapods.

But on compiling the project getting the following error.

1. Semantic Issue:
Path/Pods/FirebaseDynamicLinks/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m:517:66: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
2. Lexical or Preprocessor Issue:
Path/Pods/FirebaseDynamicLinks/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m:20:9: 'FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h' file not found

Can you please check.

### LINKED ISSUE #8401: [Breaking][Xcode 13.0 b3]: "error: 'shared' is unavailable in application extensions for iOS:"
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 b3
  * Firebase SDK version: 8.3.1
  * Installation method: Swift Package Manager
  * Firebase Component: App Distribution
  
### [REQUIRED] Step 2: Describe the problem
Hello,

When compiling our application, I see an error like:

```
error: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
            if let windowScene = UIApplication.shared.activeScene {
```
Note that this was not happening in our app with Xcode 13.0 beta 2, it started happening today when I updated to Xcode 13.0 beta 3). Apple requires the library itself to be annotated like so:
```
@available(iOSApplicationExtension, unavailable)
```
See: https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11 

This is related to a change in Xcode made by Apple deliberately and for which they provided annotation library authors have to add when declaring methods that would trigger that compilation error.

Thank you in advance for your help :)!

Kind Regards,

Goffredo Marocchi

**Notes**
* I reported the bug on Apple's Feedback Reporter tool (it affects lots of libraries and I have no way to let SwiftPM know we do not have any App Extension targets...): FB9337463
* Reported a thread in the dev forums too: https://developer.apple.com/forums/thread/685103 

#### Steps to reproduce:

What happened? How can we make the problem occur?
Download Xcode 13.0 b3, compile a project that imports Firebase iOS SDK (including App Distribution too) using Swift PM (cocoapods works for this library for now).

#### Relevant Code:
The compilation issue occurs in Firebase's code as the SwiftPM package is imported.

### PR DESCRIPTION
**Pull request by paulb777**
Fix #8401
Fix #6548

### CODE REVIEW

**Comment by paulb777** [comment]
Note the travis CI failure is dealt with separately in #8404

**Review by maksymmalyhin — APPROVED** [review]
LGTM, thank you Paul

File: FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift [hunk 1]
```diff
@@ -170,20 +170,20 @@ final class AppCheckAPITests {
             // ...
           }
         }
-      }
```
Comment (ryanwilson) [inline FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift:173]: Was this intended to close here and add an extra indentation level?

File: FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h [hunk 2]
```diff
@@ -33,6 +33,8 @@ NS_ASSUME_NONNULL_BEGIN
  * @class FIRDynamicLinks
  * @abstract A class that checks for pending Dynamic Links and parses URLs.
  */
+
+NS_EXTENSION_UNAVAILABLE_IOS("Firebase Dynamic Links is not supported for iOS extensions.")
```
Comment (ryanwilson) [inline FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h:37]: @eldhosembabu or @chliangGoogle  can you think of any situations where this would break existing iOS users?

File: FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h [hunk 3]
```diff
@@ -42,6 +42,8 @@ NS_ASSUME_NONNULL_BEGIN
  *   2. Set `FirebaseInAppMessagingAutomaticDataCollectionEnabled` to false in the app's plist file.
  *   3. Global Firebase data collection setting.
  **/
+
+NS_EXTENSION_UNAVAILABLE_IOS("Firebase In App Messaging is not supported for iOS extensions.")
```
Comment (ryanwilson) [inline FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h:46]: cc @eldhosembabu same question

File: FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift [hunk 4]
```diff
@@ -14,6 +14,8 @@
 
 import FirebaseInAppMessaging
 
+@available(iOS 13, tvOS 13, *)
+@available(iOSApplicationExtension, unavailable)
```
Comment (ryanwilson) [inline FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift:18]: I'm going to have troubles cherry-picking this since this was added post code freeze as far as I recall

**Review by ryanwilson — COMMENTED** [review]
Overall LGTM, thanks for the fix. A couple questions for product owners and comment about cherry-picking to the release.

File: FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift (hunk 1 above)
Comment (paulb777) [reply FirebaseAppCheck/Tests/Unit/Swift/AppCheckAPITests.swift:173]: Yes, it fixes an Xcode 13 build beta 2 (and beta 3) build issue. See #8402

File: FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h (hunk 2 above)
Comment (paulb777) [reply FirebaseDynamicLinks/Sources/Public/FirebaseDynamicLinks/FIRDynamicLinks.h:37]: This has always failed on extension builds. See #6548

File: FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h (hunk 3 above)
Comment (paulb777) [reply FirebaseInAppMessaging/Sources/Public/FirebaseInAppMessaging/FIRInAppMessaging.h:46]: Presumably extension builds have never worked for FIAM.

File: FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift (hunk 4 above)
Comment (paulb777) [reply FirebaseInAppMessaging/Swift/Source/SwiftUIPreviewHelpers.swift:18]: I can merge a cherry-pick if we decide to do so.

**Comment by paulb777** [comment]
Merging without full CI since only CHANGELOGs changed.
