### PR TITLE
[Config] Mark two `RCNConfigSettings` properties `atomic`

### LINKED ISSUE #13898: RemoteConfig crashes on __53-[RCNConfigRealtime createRequestBodyWithCompletion:]_block_invoke
### Description

Faced a couple of crashes on our production app

Stack trace can be found here
https://dashboard.instabug.com/crashes/ic8RhZBLwggzfz_KcV_C9w

### Reproducing the issue

cannot reproduce it

### Firebase SDK Version

11.0.0

### Xcode Version

15.3

### Installation Method

Zip

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS, watchOS

### Relevant Log Output

```shell
data:text/text;charset=utf-8,
# Cause: Crash due to signal: SIGSEGV(SEGV_MAPERR) at b051b80e8
# Reported at: 2024-09-26 04:40:57 UTC

Thread 0 Queue 1: com.apple.main-thread (serial):

0    libsystem_malloc.dylib                   0x19c690594     _xzm_free + 776
1    Realm                                    0x10402c650     0x103f28000
2    Realm                                    0x10403ba98     0x103f28000
3    Realm                                    0x10402c650     0x103f28000
4    Realm                                    0x10403ba98     0x103f28000
5    Realm                                    0x104006500     0x103f28000
6    Realm                                    0x1041ca770     0x103f28000
7    Realm                                    0x1041c93c8     0x103f28000
8    Realm                                    0x1041f5c20     0x103f28000
9    Realm                                    0x1041efd4c     0x103f28000
10   Realm                                    0x1041f230c     0x103f28000
11   Realm                                    0x1041f25d4     0x103f28000
12   Realm                                    0x10439c6b8     0x103f28000
13   RealmSwift                               0x1048e44d8     0x104864000
14   RealmSwift                               0x1048e8c68     0x104864000
15   DataLayerProduction                      0x100ae7a20     PreferenceServiceV2.Production.legacyPreferenceFor(resourceId:type:) (PreferenceServiceV2+Production.swift:73)
16   DataLayerProduction                      0x100ae9568     protocol witness for AnyPreferenceServiceV2.preferenceFor(resourceId:type:) in conformance PreferenceServiceV2.Production (<compiler-generated>:52)
17   DataLayerProduction                      0x100ac9b18     ExercisePreferenceServiceV2.Production.unit(for:unitType:) (ExercisePreferenceServiceV2+Production.swift:49)
18   DataLayerProduction                      0x100acacd0     protocol witness for AnyExercisePreferenceServiceV2.unit(for:unitType:) in conformance ExercisePreferenceServiceV2.Production (<compiler-generated>:0)
19   DataLayerProduction                      0x100b27418     UnitConversionServiceV2.Production.preferredWeightUnit(_:) (UnitConversionService+Production.swift:90)
20   DataLayerProduction                      0x100b27714     UnitConversionServiceV2.Production.unitString(for:value:exerciseId:) (UnitConversionService+Production.swift:114)
21   DataLayerProduction                      0x100b291b4     protocol witness for AnyUnitConversionService.unitString(for:value:exerciseId:) in conformance UnitConversionServiceV2.Production (<compiler-generated>:0)
22   FlexStats                                0x1032083a0     StatsController.ViewModel.StatCardHelper.statValue(_:) (StatControllerViewModel+StatCardHelper.swift:91)
23   FlexStats                                0x103209c20     specialized Collection.map<A>(_:) (<compiler-generated>:0)
24   FlexStats                                0x1032080e0     StatsController.ViewModel.StatCardHelper.exercisesData(_:_:_:) (StatControllerViewModel+StatCardHelper.swift:46)
25   FlexStats                                0x10320325c     StatsController.ViewModel.handleStateUpdate(_:_:_:_:_:) (StatsController+ViewModel.swift:150)
26   FlexStats                                0x103202f00     closure #1 in StatsController.ViewModel.subscribe() (StatsController+ViewModel.swift:116)
27   FlexStats                                0x103205144     partial apply for closure #1 in StatsController.ViewModel.subscribe() (<compiler-generated>:0)
28   FlexStats                                0x103203840     thunk for @escaping @callee_guaranteed (@guaranteed [ExerciseStatsCardService.StatsCard], @guaranteed [LeaderboardCenterService.LeaderboardBriefItem], @in_guaranteed StreakService.StreakInfo?, @unowned StepTrackingService.StepsData, @guaranteed [WeightSample], @in_guaranteed UserService.User) -> () (<compiler-generated>:0)
29   Combine                                  0x195798ec0     Subscribers.Sink.receive(_:) + 91
30   Combine                                  0x195798e54     protocol witness for Subscriber.receive(_:) in conformance Subscribers.Sink<A, B> + 23
31   Combine                                  0x1957ecd7c     closure #1 in Publishers.Debounce.Inner.receive(_:) + 2815
32   Foundation                               0x18b1d9f0c     partial apply for closure #1 in NSRunLoop.schedule(options:_:) + 27
33   Foundation                               0x18b21bc6c     thunk for @escaping @callee_guaranteed @Sendable (@guaranteed NSTimer) -> () + 55
34   Foundation                               0x18b21bbf4     __NSFireTimer + 95
35   CoreFoundation                           0x18c51f3f8     __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 31
36   CoreFoundation                           0x18c51f09c     __CFRunLoopDoTimer + 1011
37   CoreFoundation                           0x18c51ebf0     __CFRunLoopDoTimers + 287
38   CoreFoundation                           0x18c4bd0fc     __CFRunLoopRun + 1855
39   CoreFoundation                           0x18c4bc5b8     CFRunLoopRunSpecific + 571
40   GraphicsServices                         0x1d7f521c4     GSEventRunModal + 163
41   UIKitCore                                0x18f0125f0     -[UIApplication _run] + 815
42   UIKitCore                                0x18f0c110c     UIApplicationMain + 339
43   App                                      0x1002bb880     main (AppDelegate.swift:44)

Thread 1 Queue 640: com.google.firebase.firestore.rpc (serial):

0    libsystem_kernel.dylib                   0x1dc314ee0     poll + 8
1    FlexNetworkingProduction                 0x1019aace8     pollset_work(grpc_pollset*, grpc_pollset_worker**, grpc_core::Timestamp) + 87
2    FlexNetworkingProduction                 0x1019769ec     cq_next(grpc_completion_queue*, gpr_timespec, void*) + 395
3    FlexNetworkingProduction                 0x101bdede0     grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) + 59
4    FlexNetworkingProduction                 0x1015a46fc     firebase::firestore::remote::Datastore::PollGrpcQueue() + 83
5    FlexNetworkingProduction                 0x1016cb340     firebase::firestore::util::Task::ExecuteAndRelease() + 187
6    libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
7    libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
8    libdispatch.dylib                        0x19416e1e0     _dispatch_lane_invoke + 379
9    libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
10   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
11   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
12   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 2 com.apple.uikit.eventfetch-thread:

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    CoreFoundation                           0x18c4bd7cc     __CFRunLoopServiceMachPort + 159
4    CoreFoundation                           0x18c4bce78     __CFRunLoopRun + 1211
5    CoreFoundation                           0x18c4bc5b8     CFRunLoopRunSpecific + 571
6    Foundation                               0x18b152f00     -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
7    Foundation                               0x18b152d50     -[NSRunLoop(NSRunLoop) runUntilDate:] + 63
8    UIKitCore                                0x18f025a44     -[UIEventFetcher threadMain] + 419
9    Foundation                               0x18b164058     __NSThread__start__ + 723
10   libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
11   libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 3 com.google.firebase.crashlytics.MachExceptionServer:

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    FlexNetworkingProduction                 0x1015488bc     FIRCLSMachExceptionServer + 103
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 4 com.apple.NSURLConnectionLoader:

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    CoreFoundation                           0x18c4bd7cc     __CFRunLoopServiceMachPort + 159
4    CoreFoundation                           0x18c4bce78     __CFRunLoopRun + 1211
5    CoreFoundation                           0x18c4bc5b8     CFRunLoopRunSpecific + 571
6    CFNetwork                                0x18da34f44     +[__CFN_CoreSchedulingSetRunnable _run:] + 415
7    Foundation                               0x18b164058     __NSThread__start__ + 723
8    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
9    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 5 Unknown:

0    Instabug                                 0x103b41c1c     mach_exception_callback + 160
1    Instabug                                 0x103b50e34     exception_server_thread + 323
2    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
3    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 6 com.apple.CoreMotion.MotionThread:

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    CoreFoundation                           0x18c4bd7cc     __CFRunLoopServiceMachPort + 159
4    CoreFoundation                           0x18c4bce78     __CFRunLoopRun + 1211
5    CoreFoundation                           0x18c4bc5b8     CFRunLoopRunSpecific + 571
6    CoreFoundation                           0x18c528850     CFRunLoopRun + 63
7    CoreMotion                               0x1998db1e4     CFDataCreateMutable + 6713012707
8    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
9    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 7 Realm notification listener:

0    libsystem_kernel.dylib                   0x1dc30746c     kevent + 8
1    Realm                                    0x1041aa8f4     0x103f28000
2    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
3    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 8 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1beec     gpr_cv_wait + 159
2    FlexNetworkingProduction                 0x1019b376c     grpc_core::Executor::ThreadMain(void*) + 191
3    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 9 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1beec     gpr_cv_wait + 159
2    FlexNetworkingProduction                 0x1019b376c     grpc_core::Executor::ThreadMain(void*) + 191
3    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 10 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b33980     timer_thread(void*) + 519
3    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 11 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b32868     grpc_event_engine::experimental::TimerManager::WaitUntil(grpc_core::Timestamp) + 279
3    FlexNetworkingProduction                 0x101b33150     void absl::lts_20240116::internal_any_invocable::RemoteInvoker<false, void, grpc_event_engine::experimental::TimerManager::MainLoop()::$_0&>(absl::lts_20240116::internal_any_invocable::TypeErasedState*) + 39
4    FlexNetworkingProduction                 0x1018deb68     grpc_event_engine::experimental::SelfDeletingClosure::Run() + 31
5    FlexNetworkingProduction                 0x101b55000     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 127
6    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
7    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
8    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
9    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
10   libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 12 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b55408     grpc_event_engine::experimental::WorkStealingThreadPool::WorkSignal::WaitWithTimeout(grpc_core::Duration) + 123
3    FlexNetworkingProduction                 0x101b5510c     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 395
4    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
5    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
6    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 13 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b55408     grpc_event_engine::experimental::WorkStealingThreadPool::WorkSignal::WaitWithTimeout(grpc_core::Duration) + 123
3    FlexNetworkingProduction                 0x101b5510c     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 395
4    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
5    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
6    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 14 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b55408     grpc_event_engine::experimental::WorkStealingThreadPool::WorkSignal::WaitWithTimeout(grpc_core::Duration) + 123
3    FlexNetworkingProduction                 0x101b5510c     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 395
4    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
5    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
6    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 15 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b55408     grpc_event_engine::experimental::WorkStealingThreadPool::WorkSignal::WaitWithTimeout(grpc_core::Duration) + 123
3    FlexNetworkingProduction                 0x101b5510c     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 395
4    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
5    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
6    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 16 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b55408     grpc_event_engine::experimental::WorkStealingThreadPool::WorkSignal::WaitWithTimeout(grpc_core::Duration) + 123
3    FlexNetworkingProduction                 0x101b5510c     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::Step() + 395
4    FlexNetworkingProduction                 0x101b54d18     grpc_event_engine::experimental::WorkStealingThreadPool::ThreadState::ThreadBody() + 147
5    FlexNetworkingProduction                 0x101b555d4     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::StartThread()::$_0::__invoke(void*) + 19
6    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 17 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1bedc     gpr_cv_wait + 143
2    FlexNetworkingProduction                 0x101b547c8     grpc_core::Notification::WaitForNotificationWithTimeout(absl::lts_20240116::Duration) + 219
3    FlexNetworkingProduction                 0x101b54698     grpc_event_engine::experimental::WorkStealingThreadPool::WorkStealingThreadPoolImpl::Lifeguard::LifeguardMain() + 311
4    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
5    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
6    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 18 com.apple.CFStream.LegacyThread:

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    CoreFoundation                           0x18c4bd7cc     __CFRunLoopServiceMachPort + 159
4    CoreFoundation                           0x18c4bce78     __CFRunLoopRun + 1211
5    CoreFoundation                           0x18c4bc5b8     CFRunLoopRunSpecific + 571
6    CoreFoundation                           0x18c5261fc     _legacyStreamRunLoop_workThread + 299
7    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
8    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 19 com.apple.CFSocket.private:

0    libsystem_kernel.dylib                   0x1dc3082d4     __select + 8
1    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
2    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 20 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    FlexNetworkingProduction                 0x101b1beec     gpr_cv_wait + 159
2    FlexNetworkingProduction                 0x101b33980     timer_thread(void*) + 519
3    FlexNetworkingProduction                 0x101b2d240     grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*) + 139
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 21 Unknown:

0    libsystem_kernel.dylib                   0x1dc306030     __psynch_cvwait + 8
1    libc++.1.dylib                           0x19ca06584     std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 27
2    FlexNetworkingProduction                 0x101bf0ab0     leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadEntryPoint(leveldb::(anonymous namespace)::PosixEnv*) + 79
3    FlexNetworkingProduction                 0x101bf0b4c     void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(leveldb::(anonymous namespace)::PosixEnv*), leveldb::(anonymous namespace)::PosixEnv*> >(void*) + 51
4    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
5    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 22 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 23 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 24 Queue 295: com.google.GoogleConfigService.FIRRemoteConfig (serial) [Crashed]:

0    libobjc.A.dylib                          0x1897da370     objc_release_x0 + 16
1    CoreFoundation                           0x18c495394     __CFBasicHashReplaceValue + 415
2    CoreFoundation                           0x18c493d04     CFDictionarySetValue + 207
3    CFNetwork                                0x18d9409bc     HTTPHeaderDict::setValue(HTTPHeaderKeyMixedValue const&, HTTPHeaderValueMixedValue const&) + 143
4    CFNetwork                                0x18d94082c     HTTPMessage::setHeaderFieldStringValue(__CFString const*, __CFString const*) + 99
5    CFNetwork                                0x18d93fbcc     CFURLRequestSetHTTPHeaderFieldValue + 127
6    FlexNetworkingProduction                 0x101729cb4     __53-[RCNConfigRealtime createRequestBodyWithCompletion:]_block_invoke + 183
7    libdispatch.dylib                        0x194164370     _dispatch_call_block_and_release + 31
8    libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
9    libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
10   libdispatch.dylib                        0x19416e1e0     _dispatch_lane_invoke + 379
11   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
12   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
13   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
14   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 25 Queue 324: com.mixpanel.6f85ead19b5cc0b3d378c31c1512413d.tracking) (serial):

0    libsystem_kernel.dylib                   0x1dc300c1c     pread + 8
1    libsqlite3.dylib                         0x1b98b93c8     sqlite3_snprintf + 7807
2    libsqlite3.dylib                         0x1b98cc4bc     sqlite3_log + 3419
3    libsqlite3.dylib                         0x1b994d52c     sqlite3_sourceid + 48863
4    libsqlite3.dylib                         0x1b9959e98     sqlite3_sourceid + 100427
5    libsqlite3.dylib                         0x1b98e8fe8     sqlite3_step + 48223
6    libsqlite3.dylib                         0x1b995a8a8     sqlite3_sourceid + 103003
7    libsqlite3.dylib                         0x1b98e2cd4     sqlite3_step + 22859
8    libsqlite3.dylib                         0x1b98dd748     sqlite3_step + 959
9    App                                      0x1005322a8     closure #1 in MPDB.insertRow(_:data:flag:) + 447
10   App                                      0x10053207c     MPDB.insertRow(_:data:flag:) + 843
11   App                                      0x100550730     Track.track(event:properties:timedEvents:superProperties:mixpanelIdentity:epochInterval:) + 3087
12   App                                      0x10053d98c     closure #1 in MixpanelInstance.track(event:properties:) + 635
13   App                                      0x1004042d4     thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>:0)
14   libdispatch.dylib                        0x194164370     _dispatch_call_block_and_release + 31
15   libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
16   libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
17   libdispatch.dylib                        0x19416e214     _dispatch_lane_invoke + 431
18   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
19   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
20   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
21   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 26 Queue 223: com.google.fira.worker (serial):

0    libsystem_kernel.dylib                   0x1dc300c1c     pread + 8
1    libsqlite3.dylib                         0x1b98b93c8     sqlite3_snprintf + 7807
2    libsqlite3.dylib                         0x1b98cc4bc     sqlite3_log + 3419
3    libsqlite3.dylib                         0x1b994d52c     sqlite3_sourceid + 48863
4    libsqlite3.dylib                         0x1b9959e98     sqlite3_sourceid + 100427
5    libsqlite3.dylib                         0x1b98e8fe8     sqlite3_step + 48223
6    libsqlite3.dylib                         0x1b98deb98     sqlite3_step + 6159
7    libsqlite3.dylib                         0x1b98dd748     sqlite3_step + 959
8    FlexNetworkingProduction                 0x10183f660     -[APMSqliteStore recordsForQuery:parameterValues:error:withFilter:] + 303
9    FlexNetworkingProduction                 0x1017bb86c     -[APMDatabase conditionalUserPropertiesWithCondition:parameterValues:error:] + 179
10   FlexNetworkingProduction                 0x1017bb3e8     -[APMDatabase timedOutConditionalUserPropertiesWithError:] + 147
11   FlexNetworkingProduction                 0x1017af388     -[APMConditionalUserPropertyController(Private) removeTimedOutCUPWithTimedOutEvents:] + 127
12   FlexNetworkingProduction                 0x1017af208     __75-[APMConditionalUserPropertyController(Private) processEventOnWorkerQueue:]_block_invoke + 43
13   FlexNetworkingProduction                 0x10183faac     -[APMSqliteStore performTransactionWithError:block:] + 159
14   FlexNetworkingProduction                 0x1017b3678     -[APMDatabase performTransaction:] + 39
15   FlexNetworkingProduction                 0x1017aeff4     -[APMConditionalUserPropertyController(Private) processEventOnWorkerQueue:] + 295
16   FlexNetworkingProduction                 0x1017ecae0     -[APMMeasurement(Event) writeEventOnWorkerQueue:] + 315
17   FlexNetworkingProduction                 0x1017ec768     -[APMMeasurement(Event) handleEventOnWorkerQueue:] + 711
18   FlexNetworkingProduction                 0x1017e0d6c     -[APMMeasurement logEventOnWorkerQueue:notifyEventListeners:] + 63
19   FlexNetworkingProduction                 0x1017e0bf8     -[APMMeasurement logEventOnWorkerQueueWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:] + 295
20   FlexNetworkingProduction                 0x1017e0a70     __151-[APMMeasurement logEventWithOrigin:isPublicEvent:name:parameters:timestamp:enabled:ignoreEnabled:ignoreInterceptor:interceptor:addedScreenParameters:]_block_invoke + 59
21   FlexNetworkingProduction                 0x101836b68     __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 43
22   libdispatch.dylib                        0x194164370     _dispatch_call_block_and_release + 31
23   libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
24   libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
25   libdispatch.dylib                        0x19416e1e0     _dispatch_lane_invoke + 379
26   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
27   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
28   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
29   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 27 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 28 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 29 Queue 298: com.apple.network.boringssl.metrics_queue (serial):

0    libsystem_kernel.dylib                   0x1dc300728     mach_msg2_trap + 8
1    libsystem_kernel.dylib                   0x1dc303d50     mach_msg_overwrite + 423
2    libsystem_kernel.dylib                   0x1dc303b9c     mach_msg + 23
3    libdispatch.dylib                        0x194180f14     _dispatch_mach_send_and_wait_for_reply + 543
4    libdispatch.dylib                        0x1941812b4     dispatch_mach_send_with_result_and_wait_for_reply + 59
5    libxpc.dylib                             0x2138ae9a0     xpc_connection_send_message_with_reply_sync + 255
6    Security                                 0x194acf990     security_fw_send_message_with_reply_sync_inner + 91
7    Security                                 0x194acf30c     securityd_send_sync_and_do + 87
8    Security                                 0x194ae3a5c     SecTrustReportNetworkingAnalytics + 491
9    libboringssl.dylib                       0x1c2a5fcc0     __boringssl_metrics_log_metric_block_invoke + 27
10   libdispatch.dylib                        0x194164370     _dispatch_call_block_and_release + 31
11   libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
12   libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
13   libdispatch.dylib                        0x19416e1e0     _dispatch_lane_invoke + 379
14   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
15   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
16   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
17   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 30 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 31 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 32 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 33 Queue 132: com.apple.network.connections (serial):

0    libquic.dylib                            0x21a94d3b8     quic_conn_process_frame + 72
1    libquic.dylib                            0x21a94c698     quic_conn_process_inbound + 1903
2    Network                                  0x18ca18878     nw_protocol_data_access_buffer + 931
3    libquic.dylib                            0x21a9417e4     __quic_conn_handle_inbound_block_invoke + 167
4    libquic.dylib                            0x21a9415a8     quic_conn_handle_inbound + 123
5    Network                                  0x18cee6834     ___ZL45nw_protocol_implementation_get_input_internalP31NWConcrete_nw_protocol_instanceP11nw_protocolmjjj_block_invoke + 135
6    Network                                  0x18cee581c     nw_protocol_implementation_read(NWConcrete_nw_protocol_instance*, nw_protocol*) + 611
7    Network                                  0x18cee4d38     nw_protocol_implementation_input_available(nw_protocol*, nw_protocol*) + 119
8    Network                                  0x18d5d30e0     nw_channel_add_input_frames(nw_channel*, nw_protocol*) + 8023
9    Network                                  0x18ca16770     nw_channel_update_input_source(nw_channel*, nw_protocol*, bool) + 327
10   Network                                  0x18d5d10b8     __ZL17nw_channel_createP10nw_contextPhjPvjbbPb_block_invoke.39 + 71
11   libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
12   libdispatch.dylib                        0x194169580     _dispatch_continuation_pop + 595
13   libdispatch.dylib                        0x19417d53c     _dispatch_source_latch_and_call + 419
14   libdispatch.dylib                        0x19417c104     _dispatch_source_invoke + 835
15   libdispatch.dylib                        0x19416f670     _dispatch_workloop_invoke + 1731
16   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
17   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
18   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
19   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 34 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 35 Unknown:

0    libsystem_kernel.dylib                   0x1dc3004b0     __workq_kernreturn + 8
1    libsystem_pthread.dylib                  0x213854488     start_wqthread + 7

Thread 36 AudioSession - RootQueue:

0    libsystem_kernel.dylib                   0x1dc3006bc     semaphore_timedwait_trap + 8
1    libdispatch.dylib                        0x194166ce8     _dispatch_semaphore_wait_slow + 75
2    libdispatch.dylib                        0x194177b60     _dispatch_worker_thread + 323
3    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
4    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Thread 37 AudioSession - RootQueue:

0    libsystem_kernel.dylib                   0x1dc3006bc     semaphore_timedwait_trap + 8
1    libdispatch.dylib                        0x194166ce8     _dispatch_semaphore_wait_slow + 75
2    libdispatch.dylib                        0x194177b60     _dispatch_worker_thread + 323
3    libsystem_pthread.dylib                  0x21385937c     _pthread_start + 135
4    libsystem_pthread.dylib                  0x213854494     thread_start + 7

Binary Images:

0x19c68c000     libsystem_malloc.dylib                       arm64e     F6B67EF2-6F3D-34CF-AD14-A1E5C5E16CE5 
0x103f28000     Realm                                        arm64e     57C1C784-2163-3617-AF04-C79AF423289C 
0x104864000     RealmSwift                                   arm64e     D7783557-564A-340D-9D3F-9FC04378AA59 
0x100ab0000     DataLayerProduction                          arm64e     2C6A3072-3042-38FA-ACBD-E837E4F5AA59 
0x103188000     FlexStats                                    arm64e     7C77C80B-531D-3925-B3D4-C13217D38141 
0x19578e000     Combine                                      arm64e     D076C6DC-E3DF-331A-9CE8-1CB9C8D689BD 
0x18b09c000     Foundation                                   arm64e     12E17A7A-B65F-35EE-82D7-CBC31004E223 
0x18c469000     CoreFoundation                               arm64e     47427277-EE15-3C17-AD68-6886B0380B5E 
0x1d7f51000     GraphicsServices                             arm64e     227122EB-72FD-3ECB-9F66-986ADDD8E048 
0x18ec34000     UIKitCore                                    arm64e     5BD027B1-0EC9-35FD-B9F0-6288A525693A 
0x100288000     App                                          arm64e     4620C6CF-69C7-324B-BE81-23D81CD8F56F 
0x1dc2ff000     libsystem_kernel.dylib                       arm64e     8D929B3B-D4D6-39BF-ADBB-BE59E928B332 
0x101338000     FlexNetworkingProduction                     arm64e     50ABC7FB-68C7-3774-B848-44A1C660CEE0 
0x194162000     libdispatch.dylib                            arm64e     B8C15E69-D076-317D-9296-1279500738FC 
0x213853000     libsystem_pthread.dylib                      arm64e     FCC77EB0-558F-3703-9267-5419C4D33AE7 
0x18d937000     CFNetwork                                    arm64e     FA95B718-E8EB-34BD-90FA-8FB1AFE016D6 
0x1037b4000     Instabug                                     arm64e     AC649B82-4730-3213-8494-C1E14259E666 
0x1998cb000     CoreMotion                                   arm64e     7AEB7B09-26D1-36B0-B3A8-C7A5EB06DB42 
0x19c9e5000     libc++.1.dylib                               arm64e     21502392-1CEC-3A57-8B48-43BD79BC264B 
0x1897d8000     libobjc.A.dylib                              arm64e     1A127D44-47A3-3947-BC4D-9A51C4C4E157 
0x1b98b2000     libsqlite3.dylib                             arm64e     27D9421E-C13A-3E09-A2C4-A5033278CBC4 
0x21389e000     libxpc.dylib                                 arm64e     6E0A4093-FA26-301F-800D-35BFF83E79A0 
0x194aaf000     Security                                     arm64e     89C9D134-3A7F-312A-AE12-697D15A8C747 
0x1c2a39000     libboringssl.dylib                           arm64e     EC361757-5EAA-37B0-A8F7-322841FAA840 
0x21a93a000     libquic.dylib                                arm64e     6F1BD883-663E-3DF1-BF61-2B7025DEAA2D 
0x18c9af000     Network                                      arm64e     050243FB-018C-39DA-987C-DCD558CCB8D7
```

### If using Swift Package Manager, the project's Package.resolved

n/a

### If using CocoaPods, the project's Podfile.lock

n/a

### PR DESCRIPTION
**Pull request by ncooke3**
The crashing frame is on `objc_release_x0` so I'm thinking that that the instance is being over-released.
```
Thread 24 Queue 295: com.google.GoogleConfigService.FIRRemoteConfig (serial) [Crashed]:

0    libobjc.A.dylib                          0x1897da370     objc_release_x0 + 16
1    CoreFoundation                           0x18c495394     __CFBasicHashReplaceValue + 415
2    CoreFoundation                           0x18c493d04     CFDictionarySetValue + 207
3    CFNetwork                                0x18d9409bc     HTTPHeaderDict::setValue(HTTPHeaderKeyMixedValue const&, HTTPHeaderValueMixedValue const&) + 143
4    CFNetwork                                0x18d94082c     HTTPMessage::setHeaderFieldStringValue(__CFString const*, __CFString const*) + 99
5    CFNetwork                                0x18d93fbcc     CFURLRequestSetHTTPHeaderFieldValue + 127
6    FlexNetworkingProduction                 0x101729cb4     __53-[RCNConfigRealtime createRequestBodyWithCompletion:]_block_invoke + 183
7    libdispatch.dylib                        0x194164370     _dispatch_call_block_and_release + 31
8    libdispatch.dylib                        0x1941660d0     _dispatch_client_callout + 19
9    libdispatch.dylib                        0x19416d6d8     _dispatch_lane_serial_drain + 743
10   libdispatch.dylib                        0x19416e1e0     _dispatch_lane_invoke + 379
11   libdispatch.dylib                        0x194179258     _dispatch_root_queue_drain_deferred_wlh + 287
12   libdispatch.dylib                        0x194178aa4     _dispatch_workloop_worker_thread + 539
13   libsystem_pthread.dylib                  0x213857c7c     _pthread_wqthread + 287
14   libsystem_pthread.dylib                  0x213854488     start_wqthread + 7
```

These properties are never sent in `RCNConfigSettings`'s initialization but rather on one of two different queues:

https://github.com/firebase/firebase-ios-sdk/blob/8328630971a8fdd8072b36bb22bef732eb15e1f0/FirebaseRemoteConfig/Sources/RCNConfigFetch.m#L302-L311

https://github.com/firebase/firebase-ios-sdk/blob/8328630971a8fdd8072b36bb22bef732eb15e1f0/FirebaseRemoteConfig/Sources/RCNConfigRealtime.m#L263-L272

Screenshot 2024-10-17 at 4 19 08 PM

Screenshot 2024-10-17 at 4 19 25 PM

They are currently marked `nonatomic`, so my hypothesis is that concurrent sets lead to an object with an invalid retain count, and when the property is later accessed here. It causes a crash when trying to over-release the invalid instance.

I did some searching and [`atomic`](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocProperties.html) seemed to be an acceptable solution. Others were to add a queue inside `RCNConfigSettings` which seemed too heavyweight, as well as overwriting the getter and setter to use `@synchronized` which seemed reasonable but adding atomic was less LOC.

Fix #13898

### CODE REVIEW

File: FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h [hunk 1]
```diff
@@ -41,9 +41,11 @@
 /// Device data version of checkin information.
 @property(nonatomic, copy) NSString *deviceDataVersion;
 /// InstallationsID.
-@property(nonatomic, copy) NSString *configInstallationsIdentifier;
+/// @note The property is atomic because it is access across multiple threads.
```
Comment (ncooke3) [inline FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h:44]:
```suggestion
/// @note The property is atomic because it is accessed across multiple threads.
```

File: FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h [hunk 2]
```diff
@@ -41,9 +41,11 @@
...
+@property(atomic, copy) NSString *configInstallationsIdentifier;
 /// Installations token.
-@property(nonatomic, copy) NSString *configInstallationsToken;
+/// @note The property is atomic because it is access across multiple threads.
```
Comment (ncooke3) [inline FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h:47]:
```suggestion
/// @note The property is atomic because it is accessed across multiple threads.
```

**Review by paulb777 — APPROVED** [review]

**Review by andrewheard — APPROVED** [review]
