### PR TITLE
Fix: Preserve caller stack trace and timestamp for queued Crashlytics API calls

### LINKED ISSUE #16106: Crashlytics no longer reporting non-fatal call line
### Description

After upgrading to 12.12.1 from 11.6.0, we noticed that our non-fatals stopped reporting the line where it's called. For instance

12.12.1 non-fatal stack trace:
```
     Non-fatal: Error
0  MyApp.debug.dylib        0xda6ec FIRCLSUserLoggingRecordError + 407 (FIRCLSUserLogging.m:407)
1  MyApp.debug.dylib        0xec2f4 __39-[FIRCrashlytics recordError:userInfo:]_block_invoke + 432 (FIRCrashlytics.m:432)
2  MyApp.debug.dylib        0xeca64 __46-[FIRCrashlytics waitForContextInit:callback:]_block_invoke + 488 (FIRCrashlytics.m:488)
3  MyApp.debug.dylib        0xa2e5c __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.33 + 273 (FBLPromise.m:273)
4  MyApp.debug.dylib        0xa2800 __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke.28 + 239 (FBLPromise.m:239)
5  libdispatch.dylib              0x4544 _dispatch_call_block_and_release
6  libdispatch.dylib              0x1dccc _dispatch_client_callout
7  libdispatch.dylib              0x3f864 _dispatch_main_queue_drain.cold.6
8  libdispatch.dylib              0x14204 _dispatch_main_queue_drain
9  libdispatch.dylib              0x14144 _dispatch_main_queue_callback_4CF
10 CoreFoundation                 0xa1a64 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
11 CoreFoundation                 0x2f288 __CFRunLoopRun
12 CoreFoundation                 0x2e1d0 _CFRunLoopRunSpecificWithOptions
13 GraphicsServices               0x1498 GSEventRunModal
14 UIKitCore                      0x1212c4 (Missing UUID 32c1b300a6013e148b533419a2d2f234)
15 UIKitCore                      0x8c158 (Missing UUID 32c1b300a6013e148b533419a2d2f234)
16 SwiftUI                        0x30570 (Missing UUID 609448a043903c2dbcd82543e48b6960)
17 SwiftUI                        0x2d0f4 (Missing UUID 609448a043903c2dbcd82543e48b6960)
18 SwiftUI                        0x2cc48 (Missing UUID 609448a043903c2dbcd82543e48b6960)
19 MyApp.debug.dylib        0x83f78 static MyApp.$main() (<compiler-generated>)
20 MyApp.debug.dylib        0x84024 __debug_main_executable_dylib_entry_point (MyApp.swift)
21 MyApp.debug.dylib        0x84024 main (MyApp.swift)
22 ???                            0x193b3dc1c (Missing)
```

11.6.0 stack trace:
```
          Non-fatal: Error
0  MyApp.debug.dylib        0xd6590 FIRCLSUserLoggingRecordError + 402 (FIRCLSUserLogging.m:402)
1  MyApp.debug.dylib        0xe7f78 -[FIRCrashlytics recordError:userInfo:] + 407 (FIRCrashlytics.m:407)
2  MyApp.debug.dylib        0xe7ee0 -[FIRCrashlytics recordError:] + 402 (FIRCrashlytics.m:402)
3  MyApp.debug.dylib        0x76094 CrashService.logError(error:sendToSentry:) + 33 (CrashService.swift:33)
4  MyApp.debug.dylib        0x7611c protocol witness for CrashLoggerProvider.logError(error:sendToSentry:) in conformance CrashService (<compiler-generated>)
5  MyApp.debug.dylib        0x234dc MenuRouter.handleAction(for:) + 107 (MenuRouter.swift:107)
6  MyApp.debug.dylib        0x30018 closure #1 in MenuView.row(for:) + 130 (MenuView.swift:130)
7  SwiftUI                        0x700e98 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
8  SwiftUI                        0xe0e580 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
9  SwiftUI                        0xdd7904 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
10 SwiftUI                        0xb4660 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
11 SwiftUI                        0x290810 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
12 SwiftUI                        0x550bf4 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
13 SwiftUI                        0x55de7c (Missing UUID c25cb71ea5363b44b7aef12b03900444)
14 SwiftUI                        0x290810 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
15 SwiftUI                        0x290810 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
16 SwiftUICore                    0x4513a0 (Missing UUID d4ea0d91466b398299f12b256c2e515c)
17 SwiftUICore                    0x450474 (Missing UUID d4ea0d91466b398299f12b256c2e515c)
18 SwiftUICore                    0x4501b0 (Missing UUID d4ea0d91466b398299f12b256c2e515c)
19 SwiftUI                        0x792030 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
20 SwiftUI                        0x3ee490 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
21 UIKitCore                      0x80f7e8 (Missing UUID 5f9d305da2123499960a631da0884e42)
22 UIKitCore                      0x841034 (Missing UUID 5f9d305da2123499960a631da0884e42)
23 UIKitCore                      0x8412e0 (Missing UUID 5f9d305da2123499960a631da0884e42)
24 UIKitCore                      0x1248234 (Missing UUID 5f9d305da2123499960a631da0884e42)
25 UIKitCore                      0x1248234 (Missing UUID 5f9d305da2123499960a631da0884e42)
26 UIKitCore                      0x1248234 (Missing UUID 5f9d305da2123499960a631da0884e42)
27 UIKitCore                      0x1248234 (Missing UUID 5f9d305da2123499960a631da0884e42)
28 UIKitCore                      0x58a360 (Missing UUID 5f9d305da2123499960a631da0884e42)
29 UIKitCore                      0xc8c344 (Missing UUID 5f9d305da2123499960a631da0884e42)
30 Gestures                       0x54e38 (Missing UUID 0f730a17f52d394894e622304db27d0c)
31 Gestures                       0x7b43c (Missing UUID 0f730a17f52d394894e622304db27d0c)
32 UIKitCore                      0xc88b18 (Missing UUID 5f9d305da2123499960a631da0884e42)
33 UIKitCore                      0x12595c0 (Missing UUID 5f9d305da2123499960a631da0884e42)
34 UIKitCore                      0x1235e88 (Missing UUID 5f9d305da2123499960a631da0884e42)
35 UIKitCore                      0x10d4dbc (Missing UUID 5f9d305da2123499960a631da0884e42)
36 UIKitCore                      0x10d7bc0 (Missing UUID 5f9d305da2123499960a631da0884e42)
37 UIKitCore                      0x10cffa4 (Missing UUID 5f9d305da2123499960a631da0884e42)
38 UIKitCore                      0x67a000 (Missing UUID 5f9d305da2123499960a631da0884e42)
39 UIKitCore                      0x112c060 (Missing UUID 5f9d305da2123499960a631da0884e42)
40 UpdateCycle                    0x12c0 (Missing UUID bcddf425d58c3b819275853e40f249b0)
41 CoreFoundation                 0x93988 (Missing UUID 60b1c02506f035b49149fe4b24bd02d1)
42 CoreFoundation                 0x938d0 (Missing UUID 60b1c02506f035b49149fe4b24bd02d1)
43 CoreFoundation                 0x93060 (Missing UUID 60b1c02506f035b49149fe4b24bd02d1)
44 CoreFoundation                 0x92234 (Missing UUID 60b1c02506f035b49149fe4b24bd02d1)
45 CoreFoundation                 0x8d330 (Missing UUID 60b1c02506f035b49149fe4b24bd02d1)
46 GraphicsServices               0x29c0 (Missing UUID 55830c0bfa633323910b4dc23d8cc6a6)
47 UIKitCore                      0x121b4c8 (Missing UUID 5f9d305da2123499960a631da0884e42)
48 UIKitCore                      0x1915850 (Missing UUID 5f9d305da2123499960a631da0884e42)
49 SwiftUI                        0x7bbbd4 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
50 SwiftUI                        0x7bb948 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
51 SwiftUI                        0x54cd34 (Missing UUID c25cb71ea5363b44b7aef12b03900444)
52 MyApp.debug.dylib        0x7f84c static MyApp.$main() (<compiler-generated>)
53 MyApp.debug.dylib        0x7f8f8 main (MyApp.swift)
54 MyApp.debug.dylib        0x7f8f8 __debug_main_executable_dylib_entry_point (MyApp.swift)
55 ???                            0x102d230b4 (Missing)
56 ???                            0x102fc7da4 (Missing)
```

In 11.6.0, we see that the error originates in MenuView, but that completely disappears in 12.12.1. Nothing about my setup has changed.

I did notice however that if if I update my function in CrashService (where we call `Crashlytics.crashlytics().record(error:)` to the following:

```
        let returnAddresses = Thread.callStackReturnAddresses
        let nsError = error as NSError
        let model = ExceptionModel(
            name: nsError.domain,
            reason: "Code \(nsError.code): \(nsError.localizedDescription)"
        )
        model.stackTrace = returnAddresses.map { StackFrame(address: $0.uintValue) }

        let crashlytics = Crashlytics.crashlytics()
        for (key, value) in nsError.userInfo {
            crashlytics.setCustomValue(value, forKey: "\(key)")
        }

        crashlytics.record(exceptionModel: model)
```

Then we get the actual call sites again, but it's kind of annoying that we have to add in that extra. Does anyone have any insights into this?

### Reproducing the issue

Using 12.12.1, I was simply calling

`Crashlytics.crashlytics().record(error: NSError(domain: "This is a test", code: -111))`

### Firebase SDK Version

12.12.1

### Xcode Version

26.4.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "4ba05bf563a9f0a13904d63635a7381784c68a77ea0ab5b7fb08a93fd7f1c70a",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bbe8b69694d7873315fd3a4ad41efe043e1c07c5",
        "version" : "1.2024072200.0"
      }
    },
    {
      "identity" : "alamofire",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Alamofire/Alamofire",
      "state" : {
        "revision" : "3f99050e75bbc6fe71fc323adabb039756680016",
        "version" : "5.11.1"
      }
    },
    {
      "identity" : "anycodable",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Flight-School/AnyCodable",
      "state" : {
        "revision" : "862808b2070cd908cb04f9aafe7de83d35f81b05",
        "version" : "0.6.7"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "61b85103a1aeed8218f17c794687781505fbbef5",
        "version" : "11.2.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "fdc352fabaf5916e7faa1f96ad02b1957e93e5a5",
        "version" : "11.15.0"
      }
    },
    {
      "identity" : "google-ads-on-device-conversion-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googleads/google-ads-on-device-conversion-ios-sdk",
      "state" : {
        "revision" : "a2d0f1f1666de591eb1a811f40b1706f5c63a2ed",
        "version" : "2.3.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "45ce435e9406d3c674dd249a042b932bee006f60",
        "version" : "11.15.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "617af071af9aa1d6a091d59a202910ac482128f9",
        "version" : "10.1.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "60da361632d0de02786f709bdc0c4df340f7613e",
        "version" : "8.1.0"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "75b31c842f664a0f46a2e590a570e370249fd8f6",
        "version" : "1.69.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "c756a29784521063b6a1202907e2cc47f41b667c",
        "version" : "4.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "040d087ac2267d2ddd4cca36c757d1c6a05fdbfe",
        "version" : "101.0.0"
      }
    },
    {
      "identity" : "ios-maps-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googlemaps/ios-maps-sdk",
      "state" : {
        "revision" : "037b29b55ee9ac4d93b6a686b292e75ba4c50fe5",
        "version" : "10.10.0"
      }
    },
    {
      "identity" : "ios-places-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/googlemaps/ios-places-sdk",
      "state" : {
        "revision" : "2960dc2278a84e1daf1f16b417c978a96920ecdd",
        "version" : "10.10.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },   
    {
      "identity" : "swift-case-paths",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-case-paths",
      "state" : {
        "revision" : "6989976265be3f8d2b5802c722f9ba168e227c71",
        "version" : "1.7.2"
      }
    },
    {
      "identity" : "swift-clocks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-clocks",
      "state" : {
        "revision" : "cc46202b53476d64e824e0b6612da09d84ffde8e",
        "version" : "1.0.6"
      }
    },
    {
      "identity" : "swift-cmark",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/swiftlang/swift-cmark",
      "state" : {
        "revision" : "5d9bdaa4228b381639fff09403e39a04926e2dbe",
        "version" : "0.7.1"
      }
    },
    {
      "identity" : "swift-collections",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-collections",
      "state" : {
        "revision" : "6675bc0ff86e61436e615df6fc5174e043e57924",
        "version" : "1.4.1"
      }
    },
    {
      "identity" : "swift-composable-architecture",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-composable-architecture",
      "state" : {
        "revision" : "adf6e52161f293fe4ab957dd732e214aca7031d2",
        "version" : "1.25.2"
      }
    },
    {
      "identity" : "swift-concurrency-extras",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-concurrency-extras",
      "state" : {
        "revision" : "5a3825302b1a0d744183200915a47b508c828e6f",
        "version" : "1.3.2"
      }
    },
    {
      "identity" : "swift-custom-dump",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-custom-dump",
      "state" : {
        "revision" : "06c57924455064182d6b217f06ebc05d00cb2990",
        "version" : "1.5.0"
      }
    },
    {
      "identity" : "swift-dependencies",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-dependencies",
      "state" : {
        "revision" : "c79f72b3e67a1eb64f66f76704c22ed6a5c1ed84",
        "version" : "1.11.0"
      }
    },
    {
      "identity" : "swift-identified-collections",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-identified-collections",
      "state" : {
        "revision" : "322d9ffeeba85c9f7c4984b39422ec7cc3c56597",
        "version" : "1.1.1"
      }
    },
    {
      "identity" : "swift-markdown-ui",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/gonzalezreal/swift-markdown-ui",
      "state" : {
        "revision" : "5f613358148239d0292c0cef674a3c2314737f9e",
        "version" : "2.4.1"
      }
    },
    {
      "identity" : "swift-navigation",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-navigation",
      "state" : {
        "revision" : "e7441dc4dfec6a4ae929e614e3c1e67c6639d164",
        "version" : "2.7.0"
      }
    },
    {
      "identity" : "swift-perception",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-perception",
      "state" : {
        "revision" : "4f47ebafed5f0b0172cf5c661454fa8e28fb2ac4",
        "version" : "2.0.9"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "81558271e243f8f47dfe8e9fdd55f3c2b5413f68",
        "version" : "1.37.0"
      }
    },
    {
      "identity" : "swift-sharing",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/swift-sharing",
      "state" : {
        "revision" : "3bfc408cc2d0bee2287c174da6b1c76768377818",
        "version" : "2.7.4"
      }
    },
    {
      "identity" : "swift-syntax",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/swiftlang/swift-syntax",
      "state" : {
        "revision" : "4799286537280063c85a32f09884cfbca301b1a1",
        "version" : "602.0.0"
      }
    },
    {
      "identity" : "xctest-dynamic-overlay",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/pointfreeco/xctest-dynamic-overlay",
      "state" : {
        "revision" : "dfd70507def84cb5fb821278448a262c6ff2bbad",
        "version" : "1.9.0"
      }
    }
  ],
  "version" : 3
}
```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by mghaznav**
#### **Description**

This PR fixes a regression introduced in `12.11.0` where custom logged errors (via `recordError:`) captured the incorrect execution frame and timestamp, resulting in inaccurate stack traces in the Firebase Console.

**Background & Context:**
When Crashlytics migrated to asynchronous initialization, API calls made immediately after `FirebaseApp.configure()` were being dropped because the SDK had not finished initializing. To resolve this, [[PR #15879](https://github.com/firebase/firebase-ios-sdk/pull/15879)](https://github.com/firebase/firebase-ios-sdk/pull/15879) introduced a promise-based queue (`waitForContextInit:`) to hold execution of API calls until Crashlytics was ready.

**The Bug (Side Effect):**
While PR #15879 successfully stopped API calls from dropping, it shifted the execution context of the underlying C-level logging functions. Because methods like `FIRCLSUserLoggingRecordError` were now being invoked inside the promise callback, the stack trace and timestamp were being captured at the time of the *promise resolution*, rather than the moment the user actually called the API. 

**The Fix:**
We now snapshot the stack trace synchronously using `[NSThread callStackReturnAddresses]` and grab the timestamp via `time(NULL)` directly on the caller's thread. This is how it used to be before the asynchronous change.

#### **Stack Trace**
**Before this PR**

image

Calling frame is missing from the stack.

**After**

image

Calling frame is present in the stack.

*Note: With this update there is one change in the recorded stack as compared to the stacks recorded in 12.10.0 and before. The stack has one less frame since the nesting of the call to record the stack frame has reduced by 1. This has no effect on how the events are grouped.*

#### **Testing**
- [x] All existing unit tests pass.
- [x] Updated unit tests to verify the explicit passing of the mocked stack trace arrays.
- [x] Audited and tested other Crashlytics API methods (such as `recordExceptionModel:` and custom logging) to ensure no similar async side effects exist.
- [x] Ran `./scripts/check.sh` locally to verify formatting and linting.

### CODE REVIEW

File: Crashlytics/Crashlytics/FIRCrashlytics.m [hunk 1]
```diff
@@ -426,9 +426,17 @@ - (void)recordError:(NSError *)error {
 
 - (void)recordError:(NSError *)error userInfo:(NSDictionary<NSString *, id> *)userInfo {
   NSString *rolloutsInfoJSON = [_remoteConfigManager getRolloutAssignmentsEncodedJsonString];
+
+  // Capture the stack and time before the async queue.
+  // Capturing inside the callback, results in the promise
+  // thread being recorded rather than the caller thread.
+  NSArray *addresses = [NSThread callStackReturnAddresses];
```
[the remark this answers is not in the document]
Comment (mghaznav) [reply Crashlytics/Crashlytics/FIRCrashlytics.m:437]: Added the check.

**Review by mrober — APPROVED** [review]

File: Crashlytics/Crashlytics/FIRCrashlytics.m [hunk 2]
```diff
@@ -425,10 +425,22 @@ - (void)recordError:(NSError *)error {
 }
 
 - (void)recordError:(NSError *)error userInfo:(NSDictionary<NSString *, id> *)userInfo {
+  if (!error) {
+    return;
+  }
```
Comment (tejasd) [inline Crashlytics/Crashlytics/FIRCrashlytics.m:430]: nit: this is already called in `FIRCLSUserLoggingRecordError`.

File: Crashlytics/Crashlytics/FIRCrashlytics.m [hunk 3]
```diff
@@ -425,10 +425,22 @@ - (void)recordError:(NSError *)error {
...
+
   NSString *rolloutsInfoJSON = [_remoteConfigManager getRolloutAssignmentsEncodedJsonString];
+
+  // Capture the stack and time before the async queue.
+  // Capturing inside the callback, results in the promise
+  // thread being recorded rather than the caller thread.
+  NSArray *addresses = [NSThread callStackReturnAddresses];
+  uint64_t timestamp = time(NULL);
+
   [self waitForContextInit:@"recordError"
```
Comment (tejasd) [inline Crashlytics/Crashlytics/FIRCrashlytics.m:440]: While this change LGTM, if possible I'd explore refactoring this as follows:
- Create a function (likely in `FIRCrashlytics.m`) that generates the necessary artifacts for logging the non fatal error (potentially even a wrapper class called `FIRCLSNonFatalError`)
- Update `FIRCLSUserLoggingRecordError` to accept that as a parameter, and call that (or another existing method like `FIRCLSUserLoggingWriteError` from within `waitForContextInit`).

This would also allow https://github.com/firebase/firebase-ios-sdk/pull/16045 to be included in a future release.

File: Crashlytics/UnitTests/FIRCLSLoggingTests.m
Comment (tejasd) [inline Crashlytics/UnitTests/FIRCLSLoggingTests.m:226]: Please fix.

**Review by tejasd — APPROVED** [review]

File: Crashlytics/UnitTests/FIRCLSLoggingTests.m
Comment (mghaznav) [reply Crashlytics/UnitTests/FIRCLSLoggingTests.m:226]: I'm not sure why that comment is showing on the file, all tests have passed. Even if you click on `View Details` it shows all tests passing. I think its a glitch from an outdated run.

File: Crashlytics/Crashlytics/FIRCrashlytics.m (hunk 3 above)
Comment (mghaznav) [reply Crashlytics/Crashlytics/FIRCrashlytics.m:440]: Acknowledged

File: Crashlytics/Crashlytics/FIRCrashlytics.m (hunk 2 above)
Comment (mghaznav) [reply Crashlytics/Crashlytics/FIRCrashlytics.m:430]: I put this here as well to avoid capturing the entire stack trace for null errors. We don't need to do all that extra work when not necessary.
