### PR TITLE
Fix bitcode generation for Swift frameworks

### LINKED ISSUE #6349: Zip builder binary framework generation does not support bitcode
- Xcode version: 11.6
- Firebase SDK version: 6.27.0

I use Carthage and would like to build FirebaseFirestoreSwift. As mentioned in [#5287 ](https://github.com/firebase/firebase-ios-sdk/issues/5287) I am trying to use ZipBuilder.
Everything works great but when I try to create an archive build I get an error to bitcode support. So my question is how to support bitcode, when I build a binary framework with Zip builder?

Here's the command I used:
`swift run ReleasePackager -templateDir $(pwd)/Template -zipPods pods.json`

And this is the zipPods files pods.json:

```
[
  {
    "name": "FirebaseFirestoreSwift"
  }
]
```

Here is the error message:
```
bitcode bundle could not be generated because '/Users/erno/Library/Developer/Xcode/DerivedData/HorseRider-cmwsijeipqkrmbdpxmmyvqjbivnh/Build/Intermediates.noindex/ArchiveIntermediates/HorseRiderRelease/BuildProductsPath/Release-iphoneos/FirebaseFirestoreSwift.framework/FirebaseFirestoreSwift(CodableErrors.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/erno/Library/Developer/Xcode/DerivedData/HorseRider-cmwsijeipqkrmbdpxmmyvqjbivnh/Build/Intermediates.noindex/ArchiveIntermediates/HorseRiderRelease/BuildProductsPath/Release-iphoneos/FirebaseFirestoreSwift.framework/FirebaseFirestoreSwift' for architecture arm64 
```

### PR DESCRIPTION
**Pull request by paulb777**
Fix #6349 

Thanks to https://stackoverflow.com/a/53759319/556617

### CODE REVIEW

File: ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift [hunk 1]
```diff
@@ -23,32 +23,6 @@ enum Architecture: String, CaseIterable {
...
-        // For device, we want to enable bitcode.
-        return ["-fembed-bitcode"]
-      default:
-        // No extra arguments are required for simulator builds.
-        return []
-      }
-    }
-
-    /// Arguments that should be included as part of the build process for each target platform.
-    func extraArguments() -> [String] {
```
Comment (paulb777) [inline ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift:40]: Deleting unused function here.

File: ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift [hunk 2]
```diff
@@ -23,32 +23,6 @@ enum Architecture: String, CaseIterable {
     case device = "iphoneos"
     case simulator = "iphonesimulator"
     case catalyst = "macosx"
-
-    /// Extra C flags that should be included as part of the build process for each target platform.
```
Comment (paulb777) [inline ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift:27]: Replaced by bitcode if test below with updated option
