### PR TITLE
[Infra] Attempt to fix some Crashlytics flakes

### LINKED ISSUE #13431: Nightly Testing Report
# Nightly Testing Report
This issue([log](https://github.com/firebase/firebase-ios-sdk/actions/runs/10179793268)) is generated at 07/31/2024 05:03 AM, fetching workflow runs triggered in the last 24 hrs.
| Workflow |07/30|
| -------- | -------- |
| [storage](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/storage.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/10176359125) |
| [crashlytics](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/crashlytics.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/10172843545) |
| [functions](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/functions.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/10177324181) |
| [sessions](https://github.com/firebase/firebase-ios-sdk/blob/main/.github/workflows/sessions.yml) | [failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/10172402898) |

### PR DESCRIPTION
**Pull request by ncooke3**
`FIRCLSReportManagerTests.m` flakes pretty consistently for macCatalyst. I'm experimenting with making things a bit more stable.

Fix #13431

### CODE REVIEW

File: Crashlytics/UnitTests/FIRCLSReportManagerTests.m [hunk 1]
```diff
@@ -201,17 +203,10 @@ - (NSArray *)uploadReportArray {
 #pragma mark - File/Directory Handling
 - (void)testCreatesNewReportOnStart {
   FBLPromise<NSNumber *> *promise = [self->_reportManager startWithProfiling];
+  FBLWaitForPromisesWithTimeout(1.0);
```
Comment (ncooke3) [inline Crashlytics/UnitTests/FIRCLSReportManagerTests.m:206]: This `FBLWaitForPromisesWithTimeout` seems to be more robust then other API for testing purposes. I think we may be able to cut down on flakes by adding this accordingly after more nightly runs. 

An alternative approach to addressing the chronic flakes would probably be to refactor all of the dependencies of this class to offer a testing API that drains the operation/dispatch queues that are used.

**Comment by ncooke3** [comment]
CI failure looks to be unrelated to the file touched in this PR

**Review by paulb777 — APPROVED** [review]
