### PR TITLE
Use FIRInstallations SDK to fetch FID and FIS token, send those values in requests to FIAM backend

### LINKED ISSUE #3887: InAppMessaging - Failed restful api request to fetch in-app messages 400
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.20.2
  * Firebase Component: InAppMessaging + InAppMessagingDisplay
  * Component version: 0.13.0 + 0.13.1

### [REQUIRED] Step 3: Describe the problem

Reopening #2816 - I cannot receive test messages on device or simulator.

#### Steps to reproduce:

Add the following to your Podfile:
```
  pod 'Firebase'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'Firebase/Analytics'
```
- Run `pod install`
- Build and run the app in the simulator or on a device.
- Open Firebase Console and create a new In-App Messaging campaign with style: _Modal_.
- Under options select Test on Device, add your `InstanceID`, and click Test.
- Background the running app, then open it again.

The following error is logged to the Xcode console:
```
2019-09-19 15:17:02.421473+0200 My App[6754:458265] 5.20.0 - [Firebase/InAppMessaging][I-IAM130004] Failed restful api request to fetch in-app messages: seeing http status code as 400 with body as {
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
``` 

#### Relevant Code:

None

### PR DESCRIPTION
**Pull request by christibbs**
This is an initial FIS integration step, using FID and the FIS token in place of where we are currently using IID and the IID token.

Will follow up with another PR to replace all usages of `iid` or `instanceID` to avoid confusion-- this one has already gotten fairly large.

Next step is to only use FIS token in the server request, see internal bug #148729615.

#fixes #3887

### CODE REVIEW

File: FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h [hunk 1]
```diff
@@ -18,9 +18,13 @@
...
 
+@class FIRInstallations;
+
 @protocol FIRInAppMessagingInstanceProvider;
 @protocol FIRLibrary;
+@protocol FIRAnalyticsInterop;
 
 @interface FIRInAppMessaging () <FIRInAppMessagingInstanceProvider, FIRLibrary>
 @property(nonatomic, readwrite, strong) id<FIRAnalyticsInterop> _Nullable analytics;
+@property(nonatomic, readwrite, strong) FIRInstallations* _Nonnull installations;
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h]: Technically it is `nullable`. 

Another question - what's the difference between specifying nullability inside property (like `@property(nullable, strong) ...` and  current `_Nullable` annotation?

File: FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h [hunk 2]
```diff
@@ -18,9 +18,13 @@
 #import "FIRCore+InAppMessaging.h"
 #import "FIRInAppMessaging.h"
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h]: Nit: It is recommended to annotate ObjC headers with `NS_ASSUME_NONNULL_BEGIN` / `NS_ASSUME_NONNULL_END` to provide a default nullability annotations for parameters. Just a note, it doesn't have to be changed at this PR.

File: FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m [hunk 3]
```diff
@@ -16,52 +16,44 @@
...
+                                           NSError *_Nullable error) {
+    if (error) {
+      FIRLogWarning(kFIRLoggerInAppMessaging, @"I-IAM190006", @"Error in fetching FIS token: %@",
+                    error.localizedDescription);
+      completion(nil, nil, error);
+    } else {
+      FIRLogDebug(kFIRLoggerInAppMessaging, @"I-IAM190007", @"Successfully generated FIS token");
+
+      [installations
+          installationIDWithCompletion:^(NSString *_Nullable identifier, NSError *_Nullable error) {
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m]: Once backend is updated to accept only `FISToken` for authorization this could be simplified.

File: FirebaseInAppMessaging/Sources/Private/Analytics/FIRIAMClientInfoFetcher.h [hunk 4]
```diff
@@ -16,17 +16,18 @@
...
 
-// A class for wrapping the interactions for retrieving client side info to be used in request
-// parameter for interacting with Firebase iam servers.
+// A class for wrapping the interactions for retrieving client side info to be used in
+// request parameter for interacting with Firebase iam servers.
 
 NS_ASSUME_NONNULL_BEGIN
 @interface FIRIAMClientInfoFetcher : NSObject
-// Fetch the up-to-date Firebase instance id and token data. Since it involves a server interaction,
+// Fetch the up-to-date FID and FIS token data. Since it involves a server interaction,
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Sources/Private/Analytics/FIRIAMClientInfoFetcher.h]: I suspect that FID and FIS acronyms are not really common and may be misleading without additional context. I would suggest being a bit more verbose in comments, e.g. `Fetch the up-to-date Firebase Installations ID (FID) and token (FIStoken) data...`

File: FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h (hunk 1 above)
Comment (christibbs) [reply FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h]: There's no difference (see 2nd section in this [doc](https://developer.apple.com/swift/blog/?id=25))-- but I changed this to nullable and handled the nil case in 72f47b6.

File: FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h (hunk 2 above)
Comment (christibbs) [reply FirebaseInAppMessaging/Sources/FIRInAppMessagingPrivate.h]: Added these in 72f47b6.

File: FirebaseInAppMessaging/Sources/Private/Analytics/FIRIAMClientInfoFetcher.h (hunk 4 above)
Comment (christibbs) [reply FirebaseInAppMessaging/Sources/Private/Analytics/FIRIAMClientInfoFetcher.h]: Improved docs in 53bce58.

**Comment by maksymmalyhin** [comment]
I think we should also add `x-goog-firebase-installations-auth` header with FIS token in this PR as it described in b/148729615

**Comment by christibbs** [comment]
> I think we should also add `x-goog-firebase-installations-auth` header with FIS token in this PR as it described in b/148729615

Done in 0155dea.

**Comment by christibbs** [comment]
> I think we should also add `x-goog-firebase-installations-auth` header with FIS token in this PR as it described in b/148729615

Done in b530ed5.

File: FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m [hunk 5]
```diff
@@ -16,52 +16,70 @@
...
+  }
+  return self;
+}
+
+- (void)fetchFirebaseInstallationDataWithProjectNumber:(NSString *)projectNumber
+                                        withCompletion:
+                                            (void (^)(NSString *_Nullable FID,
+                                                      NSString *_Nullable FISToken,
+                                                      NSError *_Nullable error))completion {
+  // FIRInstallations *installations = [FIRInAppMessaging inAppMessaging].installations;
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Sources/Flows/FIRIAMClientInfoFetcher.m]: Nit: Remove commented line?

File: FirebaseInAppMessaging/Tests/Unit/FIRIAMClientInfoFetcherTests.m [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+
+@interface FIRIAMClientInfoFetcherTests : XCTestCase
+
+@property(nonatomic, strong) FIRIAMClientInfoFetcher *clientInfoFetcher;
+
+@end
+
+@implementation FIRIAMClientInfoFetcherTests
+
+- (NSDate *)future {
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Tests/Unit/FIRIAMClientInfoFetcherTests.m]: Nit: If you don't need a specific time interval but juts a time in the future you may consider using [NSDate.distantFuture](https://developer.apple.com/documentation/foundation/nsdate/1415385-distantfuture?language=objc) property.

File: FirebaseInAppMessaging/Tests/Unit/FIRIAMClientInfoFetcherTests.m [hunk 7]
```diff
@@ -0,0 +1,152 @@
...
+  FIRInstallationsAuthTokenResult *tokenResult =
+      [[FIRInstallationsAuthTokenResult alloc] initWithToken:@"mock_token"
+                                              expirationDate:[self future]];
+  id mockInstallations = [self mockInstanceIDMethodForTokenAndIdentity:tokenResult
+                                                            tokenError:nil
+                                                              identity:@"mock_id"
+                                                         identityError:nil];
+
+  self.clientInfoFetcher =
+      [[FIRIAMClientInfoFetcher alloc] initWithFirebaseInstallations:mockInstallations];
```
Comment (maksymmalyhin) [inline FirebaseInAppMessaging/Tests/Unit/FIRIAMClientInfoFetcherTests.m]: Nit: if we store `mockInstallations`  to a property we will be able to create `self.clientInfoFetcher` once and stub the mock as we need in each test (I guess the default stub in setUp method may not be needed then).
