### PR TITLE
Do not continue with fetch if we do not get a valid IID.

### LINKED ISSUE #4622: Crash: Dozen of crashes inside RCNFetch.m line 221 __81-[RCNConfigFetch refreshInstanceIDTokenAndFetchCheckInInfoWithCompletionHandler:]
###  Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version and Firebase Component: 
```
 - FirebaseRemoteConfig (4.4.3):
    - FirebaseABTesting (~> 3.1)
    - FirebaseAnalyticsInterop (~> 1.4)
    - FirebaseCore (~> 6.2)
    - FirebaseInstanceID (~> 4.2)
    - GoogleUtilities/Environment (~> 6.2)
    - "GoogleUtilities/NSData+zlib (~> 6.2)"
    - Protobuf (>= 3.9.2, ~> 3.9)

```

### Describe the problem

We are receiving dozen of crashes after updating Pods ->
image

#### Steps to reproduce:

1. What happened? 
Crashes occur randomly and we are not able to reproduce it in debug.

Around 4% of users have this crash.

#### Relevant Code:

image

```
Crashed: com.apple.main-thread
0  **                       0x104fd81f4 __81-[RCNConfigFetch refreshInstanceIDTokenAndFetchCheckInInfoWithCompletionHandler:]_block_invoke_2 + 221 (RCNFetch.m:221)
1  libdispatch.dylib              0x18ae8a610 _dispatch_call_block_and_release + 24
2  libdispatch.dylib              0x18ae8b184 _dispatch_client_callout + 16
3  libdispatch.dylib              0x18ae3d190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1044
4  CoreFoundation                 0x18b13c5e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
5  CoreFoundation                 0x18b1375d8 __CFRunLoopRun + 2004
6  CoreFoundation                 0x18b136adc CFRunLoopRunSpecific + 464
7  GraphicsServices               0x1950bc328 GSEventRunModal + 104
8  UIKitCore                      0x18f231ae0 UIApplicationMain + 1936
9  ***                     0x104845308 main + 22 (**.swift:22)
10 libdyld.dylib                  0x18afc0360 start + 4
```

### PR DESCRIPTION
**Pull request by dmandar**
Fixes #4622

### CODE REVIEW

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 1]
```diff
@@ -0,0 +1,400 @@
...
+  [super setUp];
+  FIRSetLoggerLevel(FIRLoggerLevelMax);
+  if (![FIRApp isDefaultAppConfigured]) {
+    [FIRApp configureWithOptions:[self firstAppOptions]];
+  }
+  _expectationTimeout = 5;
+  _checkCompletionTimeout = 1.0;
+
+  // Always remove the database at the start of testing.
+  _DBPath = [RCNTestUtilities remoteConfigPathForTestDatabase];
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: nit: I would prefer having separate helper methods for the setup operations as it looks more readable to me. Maybe even move some into `RCNTestUtilities` ?

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 2]
```diff
@@ -0,0 +1,400 @@
...
+  id classMock = OCMClassMock([RCNConfigDBManager class]);
+  OCMStub([classMock remoteConfigPathForDatabase]).andReturn(_DBPath);
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Do we need to stop mocking the class at the end of the test to avoid interference with other tests? If so `classMock` should be stored to an ivar  and taken care in `tearDown` method.

The same for similar mocks below.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 3]
```diff
@@ -0,0 +1,400 @@
...
+  _DBManager = [[RCNConfigDBManager alloc] init];
+
+  _userDefaultsSuiteName = [RCNTestUtilities userDefaultsSuiteNameForTestSuite];
+  _userDefaults = [[NSUserDefaults alloc] initWithSuiteName:_userDefaultsSuiteName];
+  id userDefaultsClassMock = OCMClassMock([RCNUserDefaultsManager class]);
+  OCMStub([userDefaultsClassMock sharedUserDefaultsForBundleIdentifier:[OCMArg any]])
+      .andReturn(_userDefaults);
+
+  RCNConfigContent *configContent = [[RCNConfigContent alloc] initWithDBManager:_DBManager];
+  _configInstances = [[NSMutableArray alloc] initWithCapacity:3];
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: nit: use `RCNTestRCNumTotalInstances` instead of `3`?

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 4]
```diff
@@ -0,0 +1,400 @@
...
+
+// Instance ID token is nil. Error is not nil. Verify fetch fails.
+- (void)testNilInstanceIDTokenAndError {
+  NSMutableArray<XCTestExpectation *> *expectations =
+      [[NSMutableArray alloc] initWithCapacity:RCNTestRCNumTotalInstances];
+
+  // Test for each RC FIRApp, namespace instance.
+  for (int i = 0; i < RCNTestRCNumTotalInstances; i++) {
+    // Set the token as nil.
+    [self mockInstanceIDMethodForTokenAndIdentity:nil
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: looks like it should be out of the loop.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 5]
```diff
@@ -0,0 +1,400 @@
...
+                                    identityError:nil];
+
+    expectations[i] =
+        [self expectationWithDescription:
+                  [NSString stringWithFormat:@"Test fetch configs successfully - instance %d", i]];
+    XCTAssertEqual(_configInstances[i].lastFetchStatus, FIRRemoteConfigFetchStatusNoFetchYet);
+    FIRRemoteConfigFetchCompletion fetchCompletion =
+        ^void(FIRRemoteConfigFetchStatus status, NSError *error) {
+          XCTAssertNotNil(error);
+          [expectations[i] fulfill];
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Do we expect a particular `status` value here?

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m [hunk 6]
```diff
@@ -0,0 +1,400 @@
...
+        };
+    [_configInstances[i] fetchWithExpirationDuration:43200 completionHandler:fetchCompletion];
+  }
+
+  [self waitForExpectationsWithTimeout:_expectationTimeout
+                               handler:^(NSError *error) {
+                                 XCTAssertNil(error);
+                               }];
+}
+
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Maybe add a test for a success case?

File: FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m [hunk 7]
```diff
@@ -1396,7 +1396,9 @@ - (void)testSetFetchTimeoutConfigSetting {
 - (void)testConfigureConfigWithValidInput {
   // Configure the default app with our options and ensure the Remote Config instance is set up
   // properly.
-  XCTAssertNoThrow([FIRApp configureWithOptions:[self firstAppOptions]]);
+  if (![FIRApp isDefaultAppConfigured]) {
```
Comment (maksymmalyhin) [inline FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m]: Why the default app may be configured here? It looks cleaner to me to make sure previous tests clean up the state in `tearDown` and assert this condition in the tests or `setUp`, so the check below is performed unconditionally.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 1 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: will raincheck on this one. Some of the setup is particular to this file and will need to spend some time for a good generic option to pull this into RCNTestUtilities.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 2 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Done.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 3 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Done.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 5 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Done.

File: FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m (hunk 7 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m]: The IID SDK's init needs a default app configured. How do i reset FIRApp state in teardown?

Comment (maksymmalyhin) [reply FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m]: I think [[FIRApp deleteApp:]](https://github.com/firebase/firebase-ios-sdk/blob/7108b9b08a551d2b96d57800b385b0fd24ebc31d/FirebaseCore/Sources/Public/FIRApp.h#L98) or probably better  [[FIRApp resetApps]](https://github.com/firebase/firebase-ios-sdk/blob/7108b9b08a551d2b96d57800b385b0fd24ebc31d/FirebaseCore/Sources/Private/FIRAppInternal.h#L153) should do the trick.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 5 above)
Comment (maksymmalyhin) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Would you like to add a particular `status` check to other similar tests?

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 6 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: This should be addressed in the other tests.

File: FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m (hunk 4 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m]: Done.

File: FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m (hunk 7 above)
Comment (dmandar) [reply FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m]: Nice! done.

**Comment by paulb777** [comment]
Since code freeze is tomorrow and RC is a dependent pod, please try to resolve the open issues and merge today.

**Comment by paulb777** [comment]
Still seeing an Xcode 11 build warning:

    - WARN  | xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Sources/RCNFetch.m:250:63: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    - NOTE  | xcodebuild:  /Users/travis/build/firebase/firebase-ios-sdk/FirebaseRemoteConfig/Sources/RCNFetch.m:250:63: note: treat the string as an argument to avoid this

**Comment by raymundcat** [comment]
Hi! im coming here from https://github.com/firebase/firebase-ios-sdk/issues/4622
Wondering if you can help me out understand perhaps what was causing the crash and how did the update fix it?
