### PR TITLE
fix(spm): Add explicit SwiftPM dependencies to avoid undefined symbols

### LINKED ISSUE #15276: Missing dependencies specified for SPM
### Description

We're using Tuist in our project to generate Xcode project for us. Due to structure of our modules we need to integrate several Firebase libraries to be linked dynamically. But we encountered several build errors when making  FirebaseSessions, FirebaseRemoteConfigInternal and GoogleAppMeasurement to be linked dynamically.

FirebaseSessions
```swift
  "_pb_decode", referenced from:
      FirebaseSessions.SessionStartEvent.encodeDecodeEvent() -> __C._firebase_appquality_sessions_SessionEvent in SessionStartEvent.o
  "_pb_istream_from_buffer", referenced from:
      FirebaseSessions.SessionStartEvent.encodeDecodeEvent() -> __C._firebase_appquality_sessions_SessionEvent in SessionStartEvent.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 

FirebaseRemoteConfigInternal
```swift
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
       in RCNConfigSettings.o
ld: symbol(s) not found for architecture arm64
``` 

GoogleAppMeasurement
```swift
Undefined symbols for architecture arm64:
 "_GULIsLoggableLevel", referenced from:
-[APMMonitor isLoggableLevel:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
"_GULOSLogBasic", referenced from:
-[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement[arm64][12](APMASLLogger.o)
 "_GULOSLogError", referenced from:
-[APMPersistentDictionary initWithFileName:] in GoogleAppMeasurement[arm64][287](APMPersistentDictionary.o)
_APMWriteDictionaryToURL in GoogleAppMeasurement[arm64][287](APMPersistentDictionary.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][342](APMUserDefaults.o)
"_GULOSLogInfo", referenced from:
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][361](UIViewController+APMScreenClassName.o)
"_GULOSLogWarning", referenced from:
+[APMMeasurement sharedInstance] in GoogleAppMeasurement[arm64][62](APMMeasurement.o)
-[APMPersistentDictionary objectForKey:] in GoogleAppMeasurement[arm64][287](APMPersistentDictionary.o)
-[APMPersistentDictionary setObject:forKey:] in GoogleAppMeasurement[arm64][287](APMPersistentDictionary.o)
-[APMUserDefaults objectForKey:] in GoogleAppMeasurement[arm64][342](APMUserDefaults.o)
-[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement[arm64][342](APMUserDefaults.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][342](APMUserDefaults.o)
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][361](UIViewController+APMScreenClassName.o)
...
"_GULSetLoggerLevel", referenced from:
-[APMMonitor setDebugModeEnabled:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
 -[APMMonitor setDebugModeEnabled:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
-[APMMonitor setSGTMDebugModeEnabled:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
-[APMMonitor setSGTMDebugModeEnabled:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
-[APMMonitor setVerboseLoggingEnabled:] in GoogleAppMeasurement[arm64][70](APMMonitor.o)
"_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
  in GoogleAppMeasurement[arm64][5](APMAEU.o)
ld: symbol(s) not found for architecture arm64
```

This happens because these targets are missing several dependencies in target descriptions in Package.swift:
1. FirebaseSessions missing `nanopb` dependency specified.
2. FirebaseRemoteConfigInternal missing `GULEnvironment` dependency from `GoogleUtilities` package.
3. GoogleAppMeasurement missing `GULLogger` and `GULEnvironment` dependencies from `GoogleUtilities` package.

Can we update Package.swift for Firebase iOS SDK and GoogleAppMeasurement?

### Firebase SDK Version

11.15.0

### Xcode Version

16.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
GoogleAppMeasurement PR: https://github.com/google/GoogleAppMeasurement/pull/107

For the Sessions change, there is, intentionally, no Sessions changelog so I added the fix to Crashlytics and Performance, which are the sole clients of Sessions.

Fixes #15276

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -1100,6 +1101,7 @@ let package = Package(
         "FirebaseInstallations",
         "FirebaseCoreExtension",
         "FirebaseSessionsObjC",
```
Comment (themiswang) [inline Package.swift:1103]: nanoPD dependency is in `FirebaseSessionsObjC` (refer the code [here](https://github.com/firebase/firebase-ios-sdk/pull/15287/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eL1128-R1137)) already and that is  declared as a dependency in `FirebaseSessions `,  do we have to redo this in the outer target?

Comment (themiswang) [reply Package.swift:1103]: Wonder if it worth to make a comment on why it is needed here? Looks like even if the target does not have a direct dependency on the product we should still add them to outer scope dependency list for dynamic link support.

Comment (ncooke3) [reply Package.swift:1103]: > do we have to redo this in the outer target?

I'm unsure. This fix is a guess. I can try reproducing the original issue.

Comment (nostrouh) [reply Package.swift:1103]: > the target does not have a direct dependency on the product

The thing is that `FirebaseSessions` is using `nanopb` directly in swift code. Here is the code [here](https://github.com/firebase/firebase-ios-sdk/blob/9bc71e35b4250816412a5772cf2c730c81eddf6c/FirebaseSessions/Sources/SessionStartEvent.swift#L216) in SessionStartEvent.

Comment (themiswang) [reply Package.swift:1103]: @nostrouh if you see the interface for `FirebaseSessionsObjC` it already imports nanopb all public methods including `pb_istream_from_buffer`.
image
Screenshot 2025-09-04 at 10 51 29 AM

Comment (ncooke3) [reply Package.swift:1103]: Hi @nostrouh, do you think you could try pointing to this branch and seeing if this resolves the issue?

Comment (nostrouh) [reply Package.swift:1103]: @themiswang Yeah, SPM is probably able to resolve dependency from inner target and adds to outer target, even though nanopb is not specified explicitly for outer target. 
But we're using Tuist and it has it's own mechanism to build dependencies graph based on Package.swift. So when nanopb is not explicitly added as dependency for `FirebaseSessions`, then it's not linked to `FirebaseSessions` target and we have missing symbols build error

Comment (nostrouh) [reply Package.swift:1103]: @ncooke3 I've pointed to this branch and with your changes for GoogleAppMeasurement everything compiles successfully on our side. No more missing symbols errors.

Comment (themiswang) [reply Package.swift:1103]: Thank you for the verification folks. Let's have a comment for the reason of adding and I'll approve the change.

**Review by themiswang — APPROVED** [review]

File: Package.swift [hunk 2]
```diff
@@ -1100,6 +1101,7 @@ let package = Package(
...
+        .product(name: "nanopb", package: "nanopb"),
```
Comment (ncooke3) [inline Package.swift:1110]:
```suggestion
         // The `FirebaseSessions` target transitively depends on nanopb via the internal
         // `FirebaseSessionsObjC` target. Not explicitly depending on nanopb leads to
         // undefined symbol errors in Tuist based SPM builds.
         // See the conversations in
         // - https://github.com/firebase/firebase-ios-sdk/issues/15276
         // - https://github.com/firebase/firebase-ios-sdk/pull/15287
        .product(name: "nanopb", package: "nanopb"),
```

File: Package.swift (hunk 1 above)
Comment (ncooke3) [reply Package.swift:1103]: Added a comment. Thank you, @nostrouh, for verifying this fixed the issue. It will be released the week of Sept. 15
