### PR TITLE
Fix FIAM test flakes and exposed library bugs

### LINKED ISSUE #3046: FIAM test failing often in CI
Please fix or disable.  Most recently at https://travis-ci.org/firebase/firebase-ios-sdk/jobs/535124299

```
FIRIAMClearcutUploaderTests
  testUploadNotTriggeredWhenWaitTimeConditionNotSatisfied, ((sendingAttempted) is false) failed
  /Users/travis/build/firebase/firebase-ios-sdk/InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m:150
  ```
  [self waitForExpectationsWithTimeout:10.0 handler:nil];
  XCTAssertFalse(sendingAttempted);
}

```

### PR DESCRIPTION
**Pull request by paulb777**
Fix #3046.

- Add a test specific cache file for logStorage so that tests don't fail because of stuff in the cache from other tests. Thanks to @ryanwilson for the suggestion and helper file implementation!
- Set up the `self.mockTimeFetcher currentTimestampInSeconds` stub before the mock is passed to other functions.
- Stop calling `scheduleNextSend` in the initializer since the first zero-delayed log can happen logs to happen to soon.
- Remove early exit from `scheduleNextSend` since it can cause logs to get dropped if the first zero-length log is scheduled, the next real log gets scheduled, but the log has already been dropped because of no packets available.
- Multiple spelling and wording fixes.

### CODE REVIEW

**Comment by paulb777** [comment]
Tests ran cleanly except for #3102

File: Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m [hunk 1]
```diff
@@ -105,9 +105,6 @@ - (instancetype)initWithRequestSender:(FIRIAMClearcutHttpRequestSender *)request
     _nextValidSendTimeInMills = (int64_t)
         [_userDefaults doubleForKey:FIRIAM_UserDefaultsKeyForNextValidClearcutUploadTimeInMills];
 
-    // seed the first send upon SDK start-up
-    [self scheduleNextSend];
```
Comment (ryanwilson) [inline Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: Will want to hear back from @christibbs about this one. We may want to do this in case there are actually pending logs that are written to disk?

File: Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m [hunk 2]
```diff
@@ -205,15 +202,6 @@ - (void)attemptUploading {
 }
 
 - (void)scheduleNextSend {
-  @synchronized(self) {
-    if (_nextSendScheduled) {
```
Comment (ryanwilson) [inline Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: Don't we want to keep this, checking if `_nextSendScheduled` is already set? I noticed in the log you mentioned it could cause an issue, but is the issue because of this check AND the `scheduleNextSend` in the `init` or just the one?

File: InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m [hunk 3]
```diff
@@ -51,20 +66,24 @@ - (void)setUp {
...
 - (void)testUploadTriggeredWhenWaitTimeConditionSatisfied {
   // using a real storage in this case
   FIRIAMClearcutLogStorage *logStorage =
       [[FIRIAMClearcutLogStorage alloc] initWithExpireAfterInSeconds:1000
-                                                     withTimeFetcher:self.mockTimeFetcher];
+                                                     withTimeFetcher:self.mockTimeFetcher
+                                                       withCacheFile:self.cachePath];
+
+  NSTimeInterval currentMoment = 10000;
+  OCMStub([self.mockTimeFetcher currentTimestampInSeconds]).andReturn(currentMoment);
```
Comment (ryanwilson) [inline InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m]: I think we'd still want this to go above the `logStorage` instantiation since it uses `mockTimeFetcher`.

Comment (ryanwilson) [reply InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m]: As well as all the other instances of this happening below.

**Comment by ryanwilson** [comment]
LGTM but want to confirm that the `scheduleNextSend` logic change is okay and is tested with a sample app.

**Comment by christibbs** [comment]
@ryanwilson I'm testing out an approach where it only schedules the next send on `init` if there are logs to be sent at that time.

File: Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m (hunk 2 above)
Comment (christibbs) [reply Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: I added this check back, but I'm not sure what `_nextSendScheduled = YES` in the else block was doing.. it's already being set to YES at the end of the method. I removed the else block.

File: Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m (hunk 1 above)
Comment (christibbs) [reply Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: Trying out an approach where we only call this if there are pending logs to be sent.

File: Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m (hunk 2 above)
Comment (paulb777) [reply Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: I think this could still cause problems if you want to waitTime. The new waitTime will get ignored for the next scheduled send. Perhaps that's ok?

Comment (christibbs) [reply Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m]: I think that should be fine. The timing of sending logs doesn't need to be precise in this case.
