### PR TITLE
Store and update config metadata entries by namespace  

### LINKED ISSUE #7179: Using Performance together with Remote Config impedes the activation of Remote Config remote values
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 7.3.0
  * Installation method: CocoaPods
  * Firebase Component: Remote Config, Performance

#### Steps to reproduce:

- The Remote Config is set up in `func application(_:didFinishLaunchingWithOptions:)` to activate the currently fetched remote values and after that fetches new remote values to activate at the next app start.
- This means that from the second app start the activation method should activate the fetched remote values.
- When FirebasePerfomance is also installed, the fetching process succeeds as before but the activation process does not work anymore as expected.
- The `activateWithCompletion` completion handler gets called but its `changed` property is always `false` and calling `config.allKeys(from: .remote)` always returns `0`. This suggests that there are no remote values to be activated but there should be because the fetch completed successfully. 
- I could successfully fix this behaviour by removing `FirebasePerformance`.

#### Relevant Code:

```swift
func setupRemoteConfig() {
    let config = RemoteConfig.remoteConfig()
    config.setDefaults(fromPlist: "RemoteConfigDefaults")
    config.activate(completion: { changed, _ in
        if changed {
            config.allKeys(from: .remote).forEach { key in
                if let value = config[key].stringValue {
                    UserDefaults.standard.setValue(value, forKey: key)
                }
            }
        }
    })
    config.fetch(completionHandler: nil)
}
```

#### Podfile:

<details><summary>Podfile.lock</summary>
<p>

```
PODS:
...
  - Firebase/AdMob (7.3.0):
    - Firebase/CoreOnly
    - Google-Mobile-Ads-SDK (~> 7.66)
  - Firebase/Analytics (7.3.0):
    - Firebase/Core
  - Firebase/Core (7.3.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 7.3.0)
  - Firebase/CoreOnly (7.3.0):
    - FirebaseCore (= 7.3.0)
  - Firebase/Crashlytics (7.3.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.3.0)
  - Firebase/Functions (7.3.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (~> 7.3.0)
  - Firebase/InAppMessaging (7.3.0):
    - Firebase/CoreOnly
    - FirebaseInAppMessaging (~> 7.3.0-beta)
  - Firebase/Messaging (7.3.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 7.3.0)
  - Firebase/Performance (7.3.0):
    - Firebase/CoreOnly
    - FirebasePerformance (~> 7.3.0)
  - Firebase/RemoteConfig (7.3.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 7.3.0)
  - FirebaseABTesting (7.3.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30906.0)
  - FirebaseCore (7.3.0):
    - FirebaseCoreDiagnostics (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.3.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30906.0)
  - FirebaseCrashlytics (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30906.0)
    - PromisesObjC (~> 1.2)
  - FirebaseFunctions (7.3.0):
    - FirebaseCore (~> 7.0)
    - GTMSessionFetcher/Core (~> 1.4)
  - FirebaseInAppMessaging (7.3.0-beta):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - nanopb (~> 2.30906.0)
  - FirebaseInstallations (7.3.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseMessaging (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstanceID (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Reachability (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebasePerformance (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseRemoteConfig (~> 7.0)
    - GoogleDataTransport (~> 8.1)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/ISASwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GTMSessionFetcher/Core (~> 1.1)
    - Protobuf (~> 3.12)
  - FirebaseRemoteConfig (7.3.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
  - Google-Mobile-Ads-SDK (7.69.0):
    - GoogleAppMeasurement (~> 7.0)
    - GoogleUserMessagingPlatform (~> 1.1)
  - GoogleAppMeasurement (7.3.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30906.0)
  - GoogleDataTransport (8.1.0):
    - nanopb (~> 2.30906.0)
  - GoogleToolboxForMac/Defines (2.3.0)
  - GoogleToolboxForMac/Logger (2.3.0):
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - "GoogleToolboxForMac/NSData+zlib (2.3.0)":
    - GoogleToolboxForMac/Defines (= 2.3.0)
  - GoogleUserMessagingPlatform (1.4.0)
  - GoogleUtilities (7.1.1):
    - GoogleUtilities/AppDelegateSwizzler (= 7.1.1)
    - GoogleUtilities/Environment (= 7.1.1)
    - GoogleUtilities/ISASwizzler (= 7.1.1)
    - GoogleUtilities/Logger (= 7.1.1)
    - GoogleUtilities/MethodSwizzler (= 7.1.1)
    - GoogleUtilities/Network (= 7.1.1)
    - "GoogleUtilities/NSData+zlib (= 7.1.1)"
    - GoogleUtilities/Reachability (= 7.1.1)
    - GoogleUtilities/SwizzlerTestHelpers (= 7.1.1)
    - GoogleUtilities/UserDefaults (= 7.1.1)
  - GoogleUtilities/AppDelegateSwizzler (7.1.1):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.1.1):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/ISASwizzler (7.1.1)
  - GoogleUtilities/Logger (7.1.1):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.1.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.1.1):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.1.1)"
  - GoogleUtilities/Reachability (7.1.1):
    - GoogleUtilities/Logger
  - GoogleUtilities/SwizzlerTestHelpers (7.1.1):
    - GoogleUtilities/MethodSwizzler
  - GoogleUtilities/UserDefaults (7.1.1):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.5.0)
  - nanopb (2.30906.0):
    - nanopb/decode (= 2.30906.0)
    - nanopb/encode (= 2.30906.0)
  - nanopb/decode (2.30906.0)
  - nanopb/encode (2.30906.0)
...
  - Protobuf (3.14.0)

DEPENDENCIES:
...
  - Firebase/AdMob
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/Functions
  - Firebase/InAppMessaging
  - Firebase/Messaging
  - Firebase/Performance
  - Firebase/RemoteConfig
  - GoogleUtilities
...

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
...
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseFunctions
    - FirebaseInAppMessaging
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebasePerformance
    - FirebaseRemoteConfig
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleToolboxForMac
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb
...
    - Protobuf

SPEC CHECKSUMS:
...
  Firebase: 26223c695fe322633274198cb19dca8cb7e54416
  FirebaseABTesting: 303b5366c0c75be479424e8935e2f475cf24ce21
  FirebaseAnalytics: 2580c2d62535ae7b644143d48941fcc239ea897a
  FirebaseCore: 4d3c72622ce0e2106aaa07bb4b2935ba2c370972
  FirebaseCoreDiagnostics: d50e11039e5984d92c8a512be2395f13df747350
  FirebaseCrashlytics: d31325312c92e2cb2f0386d589b9aa44e303d99b
  FirebaseFunctions: 56b7275ad46d936b77b64ecacd306e77db7be251
  FirebaseInAppMessaging: 9436b16bbd1fd02bcb50c25ed485150b3269d611
  FirebaseInstallations: 971df89b48ae5ee4cc2bf6935f3857a525d28550
  FirebaseInstanceID: 5ccdee6a84e6b4bb5316de0a8cd88bc749ba490d
  FirebaseMessaging: 68d1bcb14880189558a8ae57167abe0b7e417232
  FirebasePerformance: 7915b7dfc8258030d5fac9544d7fa6b55fbe3e57
  FirebaseRemoteConfig: 826fad8bec5ce1912ef97a124d6ec0ce4dcf6ec1
  Google-Mobile-Ads-SDK: 2f288748a42920d1c744946a460896a95b0e9110
  GoogleAppMeasurement: 8d3c0aeede16ab7764144b5a4ca8e1d4323841b7
  GoogleDataTransport: 116c84c4bdeb76be2a7a46de51244368f9794eab
  GoogleToolboxForMac: 1350d40e86a76f7863928d63bcb0b89c84c521c5
  GoogleUserMessagingPlatform: b168e8c46cd8f92aa3e34b584c4ca78a411ce367
  GoogleUtilities: 3dc4ff0d5e4840e2fa8eef0889620e8c33d4218c
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  nanopb: 1bf24dd71191072e120b83dd02d08f3da0d65e53
...
  Protobuf: 0cde852566359049847168e51bd1c690e0f70056

PODFILE CHECKSUM: 11163c2b7e65cd88d7da843f3d7bbb1026b002c2

COCOAPODS: 1.10.0
```

</p>
</details>

### PR DESCRIPTION
**Pull request by karenyz**
Currently fetch/activation of different namespaces will modify a shared set of metadata, however fields such as `fetch_time`, `last_apply_time` should be namespace-specific

Fixes #7179

### CODE REVIEW

File: FirebaseRemoteConfig/Sources/RCNConfigDBManager.m [hunk 1]
```diff
@@ -267,8 +267,8 @@ - (BOOL)createTableSchema {
 
   static const char *createTableMetadata =
       "create TABLE IF NOT EXISTS " RCNTableNameMetadata
-      " (_id INTEGER PRIMARY KEY, bundle_identifier"
-      " TEXT, fetch_time INTEGER, digest_per_ns BLOB, device_context BLOB, app_context BLOB, "
+      " (_id INTEGER PRIMARY KEY, bundle_identifier TEXT, namespace TEXT,"
```
Comment (chliangGoogle) [inline FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:270]: Changing table scheme is not a trivial change, we need to ensure backward compatible and ensure different version of Remote config can work with each other without crashing.

**Review by chliangGoogle — COMMENTED** [review]
I was under the impression that the namespace API is deprecated in 3P concept. Do we know what are the use case or currently we are actually fetching per namespace and previous eng didn't manage to implement that in database?

**Comment by paulb777** [comment]
+ @visumickey For input on addressing Performance's namespace needs.

File: FirebaseRemoteConfig/Sources/RCNConfigDBManager.m [hunk 2]
```diff
@@ -354,9 +354,9 @@ - (BOOL)insertMetadataTableWithValues:(NSDictionary *)columnNameToValue {
   RCN_MUST_NOT_BE_MAIN_THREAD();
   static const char *SQL =
       "INSERT INTO " RCNTableNameMetadata
-      " (bundle_identifier, fetch_time, digest_per_ns, device_context, "
+      " (bundle_identifier, namespace, fetch_time, digest_per_ns, device_context, "
```
Comment (chliangGoogle) [inline FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:357]: what happen if user download a previous version of app using a previous version of remote config. Will this cause crash? 
Also once table has changed, will the old data be reset. Although I think metadata does not hold critical info so it's not as bad as the first concern.

**Comment by karenyz** [comment]
> I was under the impression that the namespace API is deprecated in 3P concept. Do we know what are the use case or currently we are actually fetching per namespace and previous eng didn't manage to implement that in database?

@chliangGoogle The use case is that Performance uses the namespace `fireperf`(initialized [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Configurations/FPRRemoteConfigFlags.m#L59)), and calls [fetchAndActivate](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Configurations/FPRRemoteConfigFlags.m#L118) independently of whether the developer uses RC. This should not affect the activation of the `firebase` template.

However right now activating `fireperf` will update the shared metadata(including `last_apply_time`) and this impacts activation of the `firebase` namespace ( based on `last_apply_time` it looks like the template has already been activated)

**Comment by paulb777** [comment]
Should we consider migrating to a more flexible storage mechanism like GULUserDefaults? @chliangGoogle Do you know why sqlite was chosen to be used?

**Comment by chliangGoogle** [comment]
No particular reason using sqlite tbh, and I think it might be easier for @karenyz to migrate to GULUserDefaults with the new metadata design.

File: FirebaseRemoteConfig/Sources/RCNConfigDBManager.m (hunk 1 above)
Comment (karenyz) [reply FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:271]: As discussed we'll use a new table name for the new schema, so that a new metadata table will always be created when developers upgrade to this version or later

If they revert to an older version they can still read/write to the old table (which doesn't have a `namespace` column)

File: FirebaseRemoteConfig/Sources/RCNConfigDBManager.m (hunk 2 above)
Comment (chliangGoogle) [reply FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:358]: have we tried install previous version of remote config and then update to this new version? Just wanna make sure it still functions without crashes.

File: FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m [hunk 3]
```diff
@@ -249,6 +253,11 @@ - (void)testWriteAndLoadMetadataResult {
     XCTAssertEqual([result[RCNKeyLastApplyTime] doubleValue], now - 100);
     XCTAssertEqual([result[RCNKeyLastSetDefaultsTime] doubleValue], now - 200);
 
+    // Check that writing metadata for one namespace doesn't affect another namespace
+    NSDictionary *resultForOtherNamespace =
+        [self->_DBManager loadMetadataWithBundleIdentifier:bundleIdentifier namespace:namespace2];
```
Comment (chliangGoogle) [inline FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m:258]: maybe also add a test case where you can update two namespaces at the same time.

**Review by chliangGoogle — CHANGES_REQUESTED** [review]

File: FirebaseRemoteConfig/Sources/RCNConfigDBManager.m (hunk 2 above)
Comment (karenyz) [reply FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:358]: Addressed in the earlier comment, but we are no longer updating the schema of an existing table.

It is true that metadata will initially be empty, but it doesn't affect previously fetched config values

Comment (chliangGoogle) [reply FirebaseRemoteConfig/Sources/RCNConfigDBManager.m:358]: theoretically yes, that's why we should test  it out in real devices/simulators.

File: FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m (hunk 3 above)
Comment (karenyz) [reply FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m:332]: Added!

**Review by chliangGoogle — APPROVED** [review]
Awesome. Thanks for doing this!

**Review by paulb777 — APPROVED** [review]
