### PR TITLE
[InAppMessaging] Fix #12882

### LINKED ISSUE #12882: FIAM Crashing App
### Description

Please bear with me as I'm not an "expert" bug poster. This issue started happening as soon as I upgraded from Firebase version 10.17.0 to 10.24.0. It also manifests in version 10.25.0

The issue is that my app crashes as soon as it's launched when it tries to display a modal FIAM message. I don't know if the modality has anything to do with things. From some Google searches, it looks like a similar issue may have existed before related to "bundles".

Stack trace from XCode 15.2 (from @implementation FIRIAMDefaultDisplayImpl)

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80049b761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800063904 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80038244d -[__NSPlaceholderArray initWithObjects:count:] + 482
	3   CoreFoundation                      0x00007ff800486947 +[NSArray arrayWithObjects:count:] + 40
	4   ****My App*****                    0x000000010e4bf1e4 __49+[FIRIAMDefaultDisplayImpl getViewResourceBundle]_block_invoke + 1540
	5   libdispatch.dylib                   0x00007ff800157d3a _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007ff8001590f3 _dispatch_once_callout + 20
	7    ****My App*****                     0x000000010e4beb13 +[FIRIAMDefaultDisplayImpl getViewResourceBundle] + 947
	8    ****My App*****                     0x000000010e4c15a6 __82+[FIRIAMDefaultDisplayImpl displayModalViewWithMessageDefinition:displayDelegate:]_block_invoke + 566
	9   libclang_rt.asan_iossim_dynamic.dyl 0x0000000114e1109c __wrap_dispatch_async_block_invoke + 204
	10  libdispatch.dylib                   0x00007ff800156a90 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00007ff800157d3a _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007ff800166ac0 _dispatch_main_queue_drain + 1420
	13  libdispatch.dylib                   0x00007ff800166526 _dispatch_main_queue_callback_4CF + 31
	14  CoreFoundation                      0x00007ff8003f7dc4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00007ff8003f26ff __CFRunLoopRun + 2463
	16  CoreFoundation                      0x00007ff8003f197d CFRunLoopRunSpecific + 557
	17  GraphicsServices                    0x00007ff80fe9d08f GSEventRunModal + 137
	18  UIKitCore                           0x00007ff805bbb53d -[UIApplication _run] + 972
	19  UIKitCore                           0x00007ff805bbffab UIApplicationMain + 123
	20   ****My App*****                    0x000000010c07ebbf main + 63
	21  dyld                                0x0000000113d733e0 start_sim + 10
	22  ???                                 0x00000001174e9386 0x0 + 4685992838
)
```

Screenshot of code from XCode:
Screenshot 2024-05-01 at 6 13 22 PM

### Reproducing the issue

I can reproduce it in my app by simply triggering an in-app message. 

### Firebase SDK Version

10.24 or earlier

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

In-App Messaging

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**

### CODE REVIEW

File: FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m [hunk 1]
```diff
@@ -72,10 +72,12 @@ + (NSBundle *)getViewResourceBundle {
            [NSBundle mainBundle],
            // Dynamically linked.
            [NSBundle bundleForClass:myClass],
+#if FIREBASE_BUILD_ZIP_FILE
            // Embedded static framework (zip distribution).
```
Comment (andrewheard) [inline FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m:76]: Just to make sure I understand what was going wrong, in the SPM and CocoaPods (static) cases (unlike with the zip distribution) you don't "Embed and Sign" the framework in Xcode so `[NSBundle bundleWithURL:[NSBundle.mainBundle.bundleURL URLByAppendingPathComponent:@"Frameworks/FirebaseInAppMessaging.framework"]]` was `nil`. Is that accurate?

Comment (ncooke3) [reply FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m:76]: precisely!

Comment (ncooke3) [reply FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m:76]: This does require that customers embed our zip distribution's XCFrameworks (or else it will crash with the error I'm fixing for static CocoaPods / SPM), but they should be embedding nowadays.

Comment (ncooke3) [reply FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m:76]: FIAM doesn't have a privacy manifest but it does have a the UI resource bundle, and to prevent the release tooling from packaging different bundles differently (e.g. some SDKs should be embedded, some don't have to), it's spelled out in the zip instructions to embed everything.

Comment (andrewheard) [reply FirebaseInAppMessaging/Sources/DefaultUI/FIRIAMDefaultDisplayImpl.m:76]: Sounds good, thanks!

**Review by andrewheard — APPROVED** [review]
