### PR TITLE
GDTTransformer: fix background tasks handling 

### LINKED ISSUE #6258: GDTTransformer Can't endBackgroundTask.
* Xcode version: Xcode 11.4 (11E146)
  * Installation method: CocoaPods

#### Steps to reproduce:
Don't know which component crash. We used pod to get firebase like this.
  
> pod 'FirebaseInstanceID'
>   pod 'Firebase/Analytics'
>   pod 'Firebase/RemoteConfig'
>   pod 'Firebase/Crashlytics'
>   pod 'Firebase/Performance'
>   pod 'Firebase/InAppMessaging'

When my phone upgrade to iOS 14 Beta,  and app enter background. Later it will crash.  Crash log is 
`[BackgroundTask] Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x2835e06c0>: taskID = 64, taskName = CCTLogWriter, creationTime = 64357 (elapsed = 0). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.
Message from debugger: Terminated due to signal 9`
And when I use `UIApplicationEndBackgroundTaskError()` to debug where goes wrong,  It breakpoint here.
F7D914F9D38C4B9558FE20619DC154FE

Could you please check this method to see if the backgroundtask is closed?

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Fixes #6258.

### CODE REVIEW

File: GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer_Private.h [hunk 1]
```diff
@@ -16,13 +16,22 @@
...
+@protocol GDTCORApplicationProtocol;
+
 NS_ASSUME_NONNULL_BEGIN
 
 @interface GDTCORTransformer ()
 
 /** The queue on which all work will occur. */
 @property(nonatomic) dispatch_queue_t eventWritingQueue;
 
+/** The application instance is used to begin/end background tasks.  */
```
Comment (mikehaney24) [inline GoogleDataTransport/GDTCORLibrary/Private/GDTCORTransformer_Private.h:28]: instance that is used

File: GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m [hunk 2]
```diff
@@ -125,6 +148,41 @@ - (void)testWriteEventWithTransformersThatCreateANewEvent {
...
+/** Sets  GDTCORApplicationFake handlers to expect the begin and the end of a background task with
+ * the specified name.
+ *  @return An array with the task begin and end XCTestExpectation.
+ */
+- (NSArray<XCTestExpectation *> *)expectationsBackgroundTaskBeginAndEndWithName:
+    (NSString *)expectedName {
+  XCTestExpectation *beginExpectation = [self expectationWithDescription:@"Background task begin"];
+  XCTestExpectation *endExpectation = [self expectationWithDescription:@"Background task end"];
+
+  GDTCORBackgroundIdentifier taskID = rand();
```
Comment (mikehaney24) [inline GoogleDataTransport/GDTCORTests/Unit/GDTCORTransformerTest.m:166]: I know it doesn't matter here, but I'd prefer something in the arc4random family just to prevent this code from being flagged for archaic API usage by external analyzers.

**Review by mikehaney24 — APPROVED** [review]
Wow, good find!

File: GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m [hunk 3]
```diff
@@ -51,45 +56,46 @@ - (void)transformEvent:(GDTCOREvent *)event
...
-                  [[GDTCORApplication sharedApplication] endBackgroundTask:bgID];
-                  bgID = GDTCORBackgroundIdentifierInvalid;
-                }];
+  bgID = [self.application beginBackgroundTaskWithName:@"GDTTransformer"
+                                     expirationHandler:^{
+                                       [self.application endBackgroundTask:bgID];
+                                       bgID = GDTCORBackgroundIdentifierInvalid;
+                                     }];
+
+  __auto_type completionWrapper = ^(BOOL wasWritten, NSError *_Nullable error) {
```
Comment (ryanwilson) [inline GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m:67]: Do we use `__auto_type` already in the SDK? Want to make sure it doesn't break some older Xcode versions or anything.

File: GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m [hunk 4]
```diff
@@ -39,10 +39,15 @@ + (instancetype)sharedInstance {
 }
 
 - (instancetype)init {
+  return [self initWithApplication:self.application];
```
[the remark this answers is not in the document]
Comment (maksymmalyhin) [reply GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m:42]: Great catch, I meant passing the shared application!

File: GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m (hunk 3 above)
Comment (maksymmalyhin) [reply GoogleDataTransport/GDTCORLibrary/GDTCORTransformer.m:67]: We've used it in tests only so far, but AFAIK it was introduced several years ago (sorry, could not find release notes for it though). Xcode 10.3 tests pass on Travis. I do you think we can proceed with it and change it back if we have a complain?

**Review by visumickey — APPROVED** [review]
