### PR TITLE
fix(auth, functions): Xcode 26.4 'async let' cleanup crashes

### LINKED ISSUE #15974: [Functions] Release build crash in HTTPSCallable.call() due to Swift 6.3 async let compiler bug
### Description

`HTTPSCallable.call()` crashes in release builds when compiled with Swift 6.3 (Xcode 26.4). The crash occurs in `FunctionsContextProvider.context()` which uses three `async let` calls. This is triggered by a Swift 6.3 compiler regression that generates incorrect async let teardown code in optimized builds.

The same code compiled with Swift 6.2.3 (Xcode 26.3) does not crash.

This is the same underlying Swift compiler bug affecting the Stripe iOS SDK: https://github.com/swiftlang/swift/issues/87481

### Crash location

`FunctionsContextProvider.context()` in `FunctionsContext.swift`:

```swift
func context(options: HTTPSCallableOptions?) async throws -> FunctionsContext {
    async let authToken = auth?.getToken(forcingRefresh: false)
    async let appCheckToken = getAppCheckToken(options: options)
    async let limitedUseAppCheckToken = getLimitedUseAppCheckToken(options: options)

    return try await FunctionsContext(
        authToken: authToken,
        fcmToken: messaging?.fcmToken,
        appCheckToken: appCheckToken,
        limitedUseAppCheckToken: limitedUseAppCheckToken
    )
}
```

This pattern (multiple `async let` + `try await`) is exactly the trigger described in the Swift compiler bug.

### Crash log

```
Exception Type:  EXC_CRASH (SIGABRT)
Termination Reason: SIGNAL 6 Abort trap: 6

Thread 3 Crashed:
0   libsystem_kernel.dylib         __pthread_kill + 8
1   libsystem_pthread.dylib        pthread_kill + 268
2   libsystem_c.dylib              __abort + 152
3   libsystem_c.dylib              abort + 160
4   libswift_Concurrency.dylib     swift::swift_Concurrency_fatalErrorv + 32
5   libswift_Concurrency.dylib     swift::swift_Concurrency_fatalError + 32
6   libswift_Concurrency.dylib     <deduplicated_symbol> + 84
7   libswift_Concurrency.dylib     swift::_swift_task_dealloc_specific + 108 (TaskAlloc.cpp:68)
8   libswift_Concurrency.dylib     asyncLet_finish_after_task_completion + 108 (AsyncLet.cpp:322)
9   <App>                          HTTPSCallable.call(_:) + 1 (HTTPSCallable.swift:163)
10  <App>                          <redacted>
```

### Environment

- Firebase iOS SDK: 12.10.0 (also reproduced with 12.11.0)
- Xcode 26.4 / Swift 6.3 (crashes)
- Xcode 26.3 / Swift 6.2.3 (no crash)
- iOS 26.4 device (iPhone18,4)
- Release build only; Debug does not crash

Any call to `HTTPSCallable.call()` in a release build from my App compiled with Xcode 26.4 will crash. It is 100% reproducible and not intermittent.

### Suggested workaround for Firebase SDK

Replace the `async let` pattern in `FunctionsContextProvider.context()` with `Task`:

```swift
func context(options: HTTPSCallableOptions?) async throws -> FunctionsContext {
    let authTokenTask = Task { try await auth?.getToken(forcingRefresh: false) }
    let appCheckTokenTask = Task { await getAppCheckToken(options: options) }
    let limitedUseAppCheckTokenTask = Task { await getLimitedUseAppCheckToken(options: options)}

    return FunctionsContext(
        authToken: await authTokenTask.value,
        fcmToken: messaging?.fcmToken,
        appCheckToken: await appCheckTokenTask.value,
        limitedUseAppCheckToken: await limitedUseAppCheckTokenTask.value
    )
}
```

### Related Swift compiler issues

- https://github.com/swiftlang/swift/issues/87481 — Same crash affecting Stripe iOS SDK (Swift 6.3)
- https://github.com/swiftlang/swift/pull/87665 — Proposed compiler fix

### Reproducing the issue

_No response_

### Firebase SDK Version

12.11

### Xcode Version

26.4

### Installation Method

Swift Package Manager

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by ncooke3**
> [!TIP]
> Recommend to review without whitespace changes: https://github.com/firebase/firebase-ios-sdk/pull/15991/changes?w=1

Local emulator testing
```
Test Case '-[FirebaseFunctionsIntegration.IntegrationTests testUnknownErrorAsync]' passed (0.012 seconds).
Test Suite 'IntegrationTests' passed at 2026-03-31 17:10:54.699.
	 Executed 51 tests, with 0 failures (0 unexpected) in 7.407 (7.425) seconds
Test Suite 'FirebaseFunctionsIntegration.xctest' passed at 2026-03-31 17:10:54.700.
	 Executed 51 tests, with 0 failures (0 unexpected) in 7.407 (7.425) seconds
Test Suite 'All tests' passed at 2026-03-31 17:10:54.700.
	 Executed 51 tests, with 0 failures (0 unexpected) in 7.407 (7.426) seconds
2026-03-31 17:10:54.984 xcodebuild[91020:874036] [MT] IDETestOperationsObserverDebug: 9.900 elapsed -- Testing started completed.
2026-03-31 17:10:54.984 xcodebuild[91020:874036] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2026-03-31 17:10:54.984 xcodebuild[91020:874036] [MT] IDETestOperationsObserverDebug: 9.900 sec, +9.900 sec -- end

Test session results, code coverage, and logs:
	/Users/nickcooke/Library/Developer/Xcode/DerivedData/firebase-ios-sdk-anxqgakbhyqozfhbkutiwmcpphvm/Logs/Test/Test-FirebaseFunctionsIntegration-2026.03.31_17-10-35--0400.xcresult

** TEST SUCCEEDED **

nickcooke@nickcooke-mac2 firebase-ios-sdk (nc/fix-15974) % git pull origin nc/fix-15974
From github.com:firebase/firebase-ios-sdk
 * branch                nc/fix-15974 -> FETCH_HEAD
Already up to date.
nickcooke@nickcooke-mac2 firebase-ios-sdk (nc/fix-15974) % xcode-select -p
/Applications/Xcode_26.4.app/Contents/Developer
```

Fix #15974

### CODE REVIEW

File: FirebaseFunctions/Sources/Internal/FunctionsContext.swift
Comment (ncooke3) [inline FirebaseFunctions/Sources/Internal/FunctionsContext.swift:1]: Since authToken.value can throw, an error will cause the operation block to exit early. Unlike async let, unstructured Tasks are not automatically cancelled when they go out of scope. This could lead to appCheckToken and limitedUseAppCheckToken continuing to run in the background if authToken fails.

Adding a defer block to cancel the tasks ensures they are cleaned up regardless of whether the function succeeds or throws.

Also, a task can be canceled more than once with no ill effects. 

Sources:
* https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/#Specifying-Cleanup-Actions
* https://developer.apple.com/documentation/swift/task/cancel()

File: FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift [hunk 1]
```diff
@@ -64,38 +64,49 @@ final class AuthBackend: AuthBackendProtocol {
                       httpMethod: String,
                       contentType: String,
                       requestConfiguration: AuthRequestConfiguration) async -> URLRequest {
+    // Previously, this section used `async let`, but that was changed for a
+    // `Task`-based approach to work around a Swift 6.0 regression in Xcode 16.4.
```
Comment (ncooke3) [inline FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift]:
```suggestion
    // `Task`-based approach to work around a Swift 6.3 regression in Xcode 26.4.
```

File: FirebaseFunctions/Sources/Internal/FunctionsContext.swift [hunk 2]
```diff
@@ -37,18 +37,32 @@ struct FunctionsContextProvider: Sendable {
   }
 
   func context(options: HTTPSCallableOptions?) async throws -> FunctionsContext {
-    async let authToken = auth?.getToken(forcingRefresh: false)
-    async let appCheckToken = getAppCheckToken(options: options)
-    async let limitedUseAppCheckToken = getLimitedUseAppCheckToken(options: options)
+    // Previously, this section used `async let`, but that was changed for a
+    // `Task`-based approach to work around a Swift 6.0 regression in Xcode 16.4.
```
Comment (ncooke3) [inline FirebaseFunctions/Sources/Internal/FunctionsContext.swift]:
```suggestion
    // `Task`-based approach to work around a Swift 6.3 regression in Xcode 26.4.
```

**Comment by ncooke3** [comment]
Hi @mikehardy, fwiw, I couldn't reproduce the issue with Auth. For one, the `async let`s used it are for async ObjC APIs. Perhaps the interop layer triggers a different compiler reaction? So, I tried to wrap these calls in Swift methods (much like Functions does). Still couldn't reproduce the crash. I did pin it down to the 2 AppCheck related async lets in Functions. Disable either and Functions works, even with the async let for the Auth token call. 

In any case, this "fix" shouldn't hurt Auth and I've decided to check it in anyhow to be preventative.

**Comment by mikehardy** [comment]
Interesting - thanks for the note there @ncooke3 , I reworded my placeholder issue over in react-native-firebase-land - hopefully doesn't affect too many folks before your workaround here makes it to release, it's been strangely quiet over there whereas I was expecting it to be a hot topic, so seems like your fix here is still out in front of most people's release build pipelines
