### PR TITLE
Mac OS FIS: use Firebase App ID as a suffix to Keychain service name Mac OS

### LINKED ISSUE #5540: [macOS] User sees permissions popup saying, "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain."
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: See below. Podfile just specifies unversioned `Firebase/Crashlytics` and `Firebase/Analytics`
  * Firebase Component: Firebase/Analytics (6.23.0), Firebase/Core (6.23.0), Firebase/CoreOnly (6.23.0), Firebase/Crashlytics (6.23.0), FirebaseCore (6.6.7), FirebaseCoreDiagnostics, FirebaseCoreDiagnosticsInterop, FirebaseCrashlytics (4.0.0), FirebaseInstallations (1.2.0), various Google subspecs
  * Component version: See above
  * Installation method: CocoaPods

#### Steps to reproduce:

This is for a macOS application, running on macOS 10.15.4. I see the issue when signing my app with a Developer ID cert with the DEBUG flag, but I don't see it when running with a macOS Development certificate.

In `applicationDidFinishLaunching`, I have simply:
```
FirebaseApp.configure()
```

Upon launch I then see this:
image

I haven't tried to proceed by entering my password, or Denying the request.

#### Relevant Code:

```
import Cocoa
import Firebase
import FirebaseCrashlytics

@NSApplicationMain class AppDelegate: NSApplicationDelegate {
    func adfl() {
        FirebaseApp.configure()
    }
}
```

Is there a workaround for this, so I can avoid spooking my users with this keychain perms request? Thanks!

### PR DESCRIPTION
**Pull request by maksymmalyhin**
Addresses an issue detected during investigation of #5540.

- Use Firebase App ID from `GoogleServices-Info.plist` as a suffix for Keychain Service name on Mac OS to make it unique per Mac OS app (see [comments](https://github.com/firebase/firebase-ios-sdk/pull/5603/files#diff-837cf256e9fc57b3d2bdacf30e6771c3R464) for details).

NOTE: This change will lead to reset of Firebase Installation ID on Mac OS. Migration is not provided because for it we will have to access the old storage which will trigger the user alert described in #5540. 
The Identifiers on iOS/TVOS/WatchOS won't be affected.

### CODE REVIEW

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m [hunk 1]
```diff
@@ -44,6 +44,8 @@
 
 NSTimeInterval const kFIRInstallationsTokenExpirationThreshold = 60 * 60;  // 1 hour.
 
+static NSString *const kStorageKeychainService = @"com.firebase.FIRInstallations.installations";
```
Comment (paulb777) [inline FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:47]: Could this be `kKeychainService`? When I see "Storage", my initial thought is it has something to do with FirebaseStorage.

Comment (maksymmalyhin) [reply FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:47]: Agreed, "Storage" is a bit extra here. Will update.

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m [hunk 2]
```diff
@@ -456,4 +459,23 @@ - (BOOL)isDefaultApp {
...
 
+#pragma mark - Keychain
+
++ (NSString *)keychainServiceWithBundleID:(nullable NSString *)bundleID {
+#if TARGET_OS_MACCATALYST || TARGET_OS_OSX
+  // We need to keep service name unique per application on macOS if bundleID provided.
+  // Applications on macOS may request access to Keychain items stored by other applications. It
+  // means that when the app looks up for a relevant Keychain item in the service scope it will
+  // request user password to grant access to the Keychain if there are other Keychain items from
+  // other applications stored under the same Keychain Service.
```
Comment (andirayo) [inline FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:470]: This comment is not helpful for me, a non Mac developer. Maybe we can rewrite it a bit?
a) What is "service name"?
b) Why does the "server name" only have to be unique if a Bundle ID was provided?
c) What is "relevant Keychain item"?
d) If an app requests access to another app's data, Mac asks for a user password - do I understand that correctly?
e) Is requesting a user password the use case that we want to prevent?

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m [hunk 3]
```diff
@@ -456,4 +459,23 @@ - (BOOL)isDefaultApp {
...
+  return [bundleID stringByAppendingFormat:@".%@", kKeychainService] ?: kKeychainService;
+#else
+  // Use a constant Keychain service for non-macOS because:
```
Comment (andirayo) [inline FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:473]: Does this affect iOS users of the SDK?

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m [hunk 4]
```diff
@@ -456,4 +459,23 @@ - (BOOL)isDefaultApp {
   return [self.appName isEqualToString:kFIRDefaultAppName];
 }
 
+#pragma mark - Keychain
```
Comment (andirayo) [inline FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:462]: out of curiosity?
what does the hash (#) prefix do?

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m (hunk 3 above)
Comment (maksymmalyhin) [reply FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:472]: No, only Mac OS apps will be affected.

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m (hunk 4 above)
Comment (maksymmalyhin) [reply FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m:461]: [This](https://nshipster.com/pragma/) looks like a good summary.

File: FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m (hunk 2 above)
Comment (maksymmalyhin) [reply FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m]: Discussed offline.
@andirayo Please let me know if you still have questions. 

As for Bundle ID - as we discussed, I decided to use Firebase App ID instead.
