### PR TITLE
Fix versioning bug in release tooling

### LINKED ISSUE #8179: Firebase/AnalyticsWithoutAdIdSupport subspec still points to `'FirebaseAnalytics/WithoutAdIdSupport', '~> 8.0.0'`, not 8.1.0
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.1.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

1. Depend on `pod 'Firebase/AnalyticsWithoutAdIdSupport', '~> 8.1.0'` in your Podfile
2. Run `pod update`
3. Inspect Podfile.lock or run `pod outdated`, and notice that `FirebaseAnalytics/WithoutAdIdSupport (8.0.0)` was installed, even though v8.1.0 of `FirebaseAnalytics` is available.

It appears that in the most recent version bump PR (#8152), the `AnalyticsWithoutAdIdSupport` subspec in `Firebase.podspec` was missed, and it still points to v8.0.0 instead of 8.1.0:

https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L72

I'm guessing that this is probably because it's a new subspec and the corresponding version bump tooling needs to be updated?

### PR DESCRIPTION
**Pull request by ncooke3**
When the release tooling [iterates through all of the defined `Pods`](https://github.com/firebase/firebase-ios-sdk/blob/5aaf38c022718421c389cfafa4fe2776227966d2/ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift#L74), it uses the `range(of:)` String API to find the first occurrence of the `pod` and then bumps the versioning. Because the API only finds the first occurrence, each pod will only get versioned bumped once. Because the `FirebaseAnalytics` substring now occurs in two places (after PR #7900 added `'FirebaseAnalytics/WithoutAdIDSupport'`):  

https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L37

and 

https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L72

it was only bumped once (the first occurrence). 

A new String API has been added to collect all of the ranges of the occurrences of a given substring.

Fixes #8179

### CODE REVIEW

**Review by ryanwilson — APPROVED** [review]
Changes LGTM - were you able to validate this works locally and doesn't have any unintended consequences?

**Review by paulb777 — APPROVED** [review]
LGTM assuming that a manual test has confirmed only the one expected change.

No need to wait for the zip CI.

File: ReleaseTooling/Sources/Utils/String+Utils.swift [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+import Foundation
+
+/// Utilities to simplify String operations.
+public extension String {
+  /// Finds and returns the ranges of all occurrences of a given string within a given range of the String, subject to given options,
+  /// using the specified locale, if any.
+  /// - Returns: An an optional array of ranges where each range corresponds to an occurence of the substring in the given string.
+  func ranges<T: StringProtocol>(of substring: T, options: CompareOptions = .literal,
+                                 locale: Locale? = nil) -> [Range<Index>]? {
```
Comment (maksymmalyhin) [inline ReleaseTooling/Sources/Utils/String+Utils.swift:25]: nit: What's the difference between `[]` and `nil` returned? If no difference, than I would suggest to use non-optional array. I think it will simplify the client code as well (no need for `guard`).

File: ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift [hunk 2]
```diff
@@ -93,20 +93,24 @@ struct InitializeRelease {
...
-        var versionStartIndex = contents.index(range.upperBound, offsetBy: 2)
-        while !contents[versionStartIndex].isWholeNumber {
-          versionStartIndex = contents.index(versionStartIndex, offsetBy: 1)
-        }
-        var versionEndIndex = contents.index(versionStartIndex, offsetBy: 1)
-        while contents[versionEndIndex] != "'" {
-          versionEndIndex = contents.index(versionEndIndex, offsetBy: 1)
+
+        for range in ranges {
+          var versionStartIndex = contents.index(range.upperBound, offsetBy: 2)
```
Comment (maksymmalyhin) [inline ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift:103]: optional: I know, it was here before your change, but it would be useful to add either comments explaining the intent or refactor it to a method(s) to make it self-documentary or both. I don't feel too strong about it but I think it will help future us.

**Review by maksymmalyhin — APPROVED** [review]
LGTM, a couple optional comments.

**Comment by maksymmalyhin** [comment]
> Changes LGTM - were you able to validate this works locally and doesn't have any unintended consequences?

I feel we have enough logic here to start adding tests to it. Test for this piece of logic could be giving different podspecs as inputs and validate expected outputs. Fortunately SPM provides pretty good support for tests.

File: ReleaseTooling/Sources/Utils/String+Utils.swift (hunk 1 above)
Comment (ncooke3) [reply ReleaseTooling/Sources/Utils/String+Utils.swift:25]: Agreed

File: ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift (hunk 2 above)
Comment (ncooke3) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift:103]: SGTM. To simplify this method even more, I'm curious if it was ever considered to bump the versions by calling
`contents.replacingOccurrences(of: oldVersion, with: newVersion)`

Comment (maksymmalyhin) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift:103]: I guess we may not always now old version for each pod that's why we try to parse the version from the file first. I think @paulb777 should have more context on it as the original author.

Comment (paulb777) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift:103]: Yep, when it started, there weren't consistent oldVersions. Also, a generic string replace, in theory, could change the string in a name or comment incorrectly. 

However, it could be fine to simplify now since `oldVersion` should be able to be defined and the context check might be not worth the extra complexity.

Comment (ncooke3) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift]: @paulb777 Makes sense. I was in the middle of refactoring some logic into a method when you replied so I figured I'd at least push those changes. WDYT of the current state? cc: @maksymmalyhin

**Review by maksymmalyhin — APPROVED** [review]
LGTM, thank you for the cleanup!

**Review by ncooke3 — COMMENTED** [review]
@ryanwilson @paulb777 @maksymmalyhin thanks for the feedback. I addressed some comments and manually verified that running the releaser bumps accordingly (and fixes the bug).

Following the conversation from above, I'm happy to simplify the implementation with `replaceOccurrences`, add old/new version launch arguments, and tests. Is this something I should work on now or add to the backlog after more conversation?

The PR in it's current state should be good for next release

File: ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift (hunk 2 above)
Comment (paulb777) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift]: LGTM

Comment (maksymmalyhin) [reply ReleaseTooling/Sources/FirebaseReleaser/InitializeRelease.swift]: IMO the concerns about unintentional changes look still relevant. We may mitigate it by using e.g. regex, but I'm not sure if it will end up more readable eventually. The current state LGTM.
