### PR TITLE
[Functions] 'call' API's completion handler should be called on the main thread

### LINKED ISSUE #14653: HTTPSCallable does not invoke completion blocks on the main thread
### Description

Issue: `HTTPSCallable`'s `callWithObject:completion` does not invoke the completion block on the main thread.

Regression: This appears to be a regression from #14085.

### Reproducing the issue

1. Create an HTTPSCallable function.
2. Invoke it with `callWithObject:completion`

Expected results: observe that the completion block is called on the main thread.
Actual results: the completion block is called on a background thread.

### Firebase SDK Version

11.11.1

### Xcode Version

16.2

### Installation Method

CocoaPods

### Firebase Product(s)

Functions

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

### PR DESCRIPTION
**Pull request by ncooke3**
ObjC regression tests (after deflaking): https://github.com/firebase/firebase-ios-sdk/actions/runs/14314286364/job/40119407605?pr=14667

Fix #14653

### CODE REVIEW

File: FirebaseFunctions/Sources/HTTPSCallable.swift [hunk 1]
```diff
@@ -79,7 +79,7 @@ open class HTTPSCallable: NSObject {
                                                    completion: @escaping (HTTPSCallableResult?,
                                                                           Error?) -> Void) {
     if #available(iOS 13, macCatalyst 13, macOS 10.15, tvOS 13, watchOS 7, *) {
-      Task {
+      Task { @MainActor in
         do {
           let result = try await call(data)
```
Comment (paulb777) [inline FirebaseFunctions/Sources/HTTPSCallable.swift:84]: Should only the completion be on the MainActor? Could the `call` lock it up?

Comment (ncooke3) [reply FirebaseFunctions/Sources/HTTPSCallable.swift:84]: I thought the same thing. I dropped a breakpoint in `call` and it was _off_ the main thread.

Comment (ncooke3) [reply FirebaseFunctions/Sources/HTTPSCallable.swift:84]: So the `call` will execute off of the main thread and won't block. We could be more precise and wrap the completion specifically which is arguably more defensive in case the logic in this scope grows and we want to minimize the work that occurs on the main thread.

Comment (paulb777) [reply FirebaseFunctions/Sources/HTTPSCallable.swift:84]: Why not be more precise? That would also be consistent with how Auth typically does completions.

Comment (ncooke3) [reply FirebaseFunctions/Sources/HTTPSCallable.swift:84]: I did a more precise approach in 9689fd8. But then decided to try the approach where we define the completion param as synchronized to the main actor (bdf79b3). This latter commit is better since the completion will be called on the main actor without needing to dispatch to it with `DispatchQueue.main.async { ... }` or `await MainActor.run { ... }`.

Comment (ncooke3) [reply FirebaseFunctions/Sources/HTTPSCallable.swift:84]: Previously marking the completion would lead to warnings when using Swift 5 x Xcode 15. In Xcode 16 though, I'm not seeing them issue warnings with Swift 5 projects. for Swift 6 mode, it makes it more restrictive as the closure is typed checked to the main actor.

**Review by morganchen12 — APPROVED** [review]

**Review by paulb777 — APPROVED** [review]

**Review by andrewheard — APPROVED** [review]
