### PR TITLE
Fix deprecation warnings by consolidating coding calls

### LINKED ISSUE #5086: Build error in googledatatransport archiveRootObject unarchiveObjectWithFile depreccated in ios 12
* Xcode version: 11.3.1
  * podfile.lock
  - Firebase/Auth (6.18.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.4.3)
  - Firebase/Core (6.18.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.3.0)
  - Firebase/CoreOnly (6.18.0):
    - FirebaseCore (= 6.6.3)
  - firebase_auth (0.0.1):
    - Firebase/Auth (~> 6.3)
    - Firebase/Core
    - Flutter
  - firebase_auth_web (0.1.0):
    - Flutter
  - firebase_core (0.0.1):
    - Firebase/Core
    - Flutter
  - firebase_core_web (0.1.0):
    - Flutter
  - FirebaseAnalytics (6.3.0):
    - FirebaseCore (~> 6.6)
    - FirebaseInstallations (~> 1.1)
    - GoogleAppMeasurement (= 6.3.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (= 0.3.9011)
  - FirebaseAuth (6.4.3):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.6.3):
    - FirebaseCoreDiagnostics (~> 1.2)
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.2.1):
    - FirebaseCoreDiagnosticsInterop (~> 1.2)
    - GoogleDataTransportCCTSupport (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
    - nanopb (~> 0.3.901)
  - FirebaseCoreDiagnosticsInterop (1.2.0)
  - FirebaseInstallations (1.1.0):
    - FirebaseCore (~> 6.6)
    - GoogleUtilities/UserDefaults (~> 6.5)
    - PromisesObjC (~> 1.2)
  * Installation method: Cocoa pod

I have the following errors when trying to build
```
/.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:143:26: error: 'archiveRootObject:toFile:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Werror,-Wdeprecated-declarations]
            [NSKeyedArchiver archiveRootObject:self toFile:[GDTCORStorage archivePath]];
                             ^
    In module 'Foundation' imported from /.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:67:1: note: 'archiveRootObject:toFile:' has been explicitly marked deprecated here
    + (BOOL)archiveRootObject:(id)rootObject toFile:(NSString *)path API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
    ^
    /.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:246:24: error: 'unarchiveObjectWithFile:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead [-Werror,-Wdeprecated-declarations]
        [NSKeyedUnarchiver unarchiveObjectWithFile:[GDTCORStorage archivePath]];
                           ^
    In module 'Foundation' imported from /.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:156:1: note: 'unarchiveObjectWithFile:' has been explicitly marked deprecated here
    + (nullable id)unarchiveObjectWithFile:(NSString *)path API_DEPRECATED("Use +unarchivedObjectOfClass:fromData:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
    ^
    /.../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:270:24: error: 'archiveRootObject:toFile:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Werror,-Wdeprecated-declarations]
          [NSKeyedArchiver archiveRootObject:self toFile:[GDTCORStorage archivePath]];
                           ^
    In module 'Foundation' imported from /Users/thomaslacan/git/sabaiFlutter/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:67:1: note: 'archiveRootObject:toFile:' has been explicitly marked deprecated here
    + (BOOL)archiveRootObject:(id)rootObject toFile:(NSString *)path API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
    ^
    /..../Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:290:24: error: 'archiveRootObject:toFile:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead [-Werror,-Wdeprecated-declarations]
          [NSKeyedArchiver archiveRootObject:self toFile:[GDTCORStorage archivePath]];
                           ^
    In module 'Foundation' imported from /Users/thomaslacan/git/sabaiFlutter/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/Private/GDTCORStorage.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyedArchiver.h:67:1: note: 'archiveRootObject:toFile:' has been explicitly marked deprecated here
    + (BOOL)archiveRootObject:(id)rootObject toFile:(NSString *)path API_DEPRECATED("Use +archivedDataWithRootObject:requiringSecureCoding:error: instead", macosx(10.2,10.14), ios(2.0,12.0), watchos(2.0,5.0), tvos(9.0,12.0));
    ^
    4 errors generated.
```
Some help would be appreciated I dont know what error I have done in my configuration.
Seems similar to https://github.com/firebase/firebase-ios-sdk/pull/4960

### PR DESCRIPTION
**Pull request by mikehaney24**
Fixes #5086

Hopefully this catches all the deprecation warnings.

cc: @paulb777 Together, we need to write some test automation that sets the deployment version of all targets to the highest OS version for any particular platform.

### CODE REVIEW

File: GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m [hunk 1]
```diff
@@ -118,6 +121,51 @@ GDTCORNetworkMobileSubtype GDTCORNetworkMobileSubTypeMessage() {
...
+    NSData *data = [NSKeyedArchiver archivedDataWithRootObject:obj
+                                         requiringSecureCoding:YES
+                                                         error:error];
+    BOOL result = [data writeToFile:archivePath atomically:YES];
+    if (!result) {
+    }
+    GDTCORLogDebug(@"Attempt to write archive. successful:%@ path:%@", result, archivePath);
+  } else {
+#elif !TARGET_OS_MACCATALYST && !TARGET_OS_WATCH
+  BOOL result [NSKeyedArchiver archiveRootObject:obj toFile:archivePath];
```
Comment (maksymmalyhin) [inline GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: BTW, the old methods throw an exception instead of returning an error if something goes wrong. It may be useful to catch the exception and convert it into an error.

File: GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m [hunk 2]
```diff
@@ -118,6 +121,51 @@ GDTCORNetworkMobileSubtype GDTCORNetworkMobileSubTypeMessage() {
 #endif
 }
 
+void GDTCOREncodeArchive(id<NSSecureCoding> obj, NSString *archivePath, NSError *_Nullable *error) {
+#if (defined(__IPHONE_11_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000) || \
+    (defined(__MAC_10_13) && MAC_OS_X_VERSION_MAX_ALLOWED >= 101300) ||      \
+    (defined(__TVOS_11_0) && __TV_OS_VERSION_MAX_ALLOWED >= 110000)
+  if (@available(macOS 10.13, iOS 11.0, tvOS 11.0, *)) {
```
Comment (doudounan) [inline GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: Do we still need this if(@available(*)) check for version on macOS , iOS and tvOS? because we already have checked above. All other changes LGTM

**Comment by mikehaney24** [comment]
Hold off, there's a couple of issues. I'm fixing test usage of NSKeyed(Un)Archivers, and the result variable is unused on older iOS versions (which is hard to test because the simulator runtimes don't go down that far).

File: GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m (hunk 2 above)
Comment (maksymmalyhin) [reply GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: I think yes, we still do in order to handle cases like an app is compiled to be run on iOS 10 - 13 but is deployed on iOS 10 device. `if(@available(*))` is a runtime check vs the macros - compile time check.

Comment (doudounan) [reply GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m]: Got new knowledge! Thanks.^_^

File: GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h [hunk 3]
```diff
@@ -88,6 +88,30 @@ GDTCORNetworkType GDTCORNetworkTypeMessage(void);
...
 GDTCORNetworkMobileSubtype GDTCORNetworkMobileSubTypeMessage(void);
 
+/** Writes the given object to the given fileURL and populates the given error if it fails.
+ *
+ * @param obj The object to encode.
+ * @param filePath The path to write the object to. Can be nil if you just need the data.
+ * @param error The error to populate if something goes wrong.
+ * @return The data of the archive. If error is nil, it's been written to disk.
+ */
+NSData *_Nullable GDTCOREncodeArchive(id<NSSecureCoding> obj,
```
Comment (paulb777) [inline GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h]: Adding to the public api should make this a minor version bump

Comment (mikehaney24) [reply GoogleDataTransport/GDTCORLibrary/Public/GDTCORPlatform.h]: Updated in the spreadsheet. CHANGELOG and podspec updates will come after this.
