### PR TITLE
[Auth] Fixed macOS extension keychain access by adding recommended kS…

### LINKED ISSUE #8950: SwiftUI/macOS Auth: "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain."
### Step 1: Describe your environment

Xcode version: Version 13.1 (13A1030d)
Firebase SDK version: 8.9.1
Installation method: Swift Package Manager
Firebase Component: Auth

#### Steps to reproduce:

What happened? How can we make the problem occur?
When build on MacOS, user sees permissions popup saying, "[App] wants to use your confidential information stored in 'com.firebase.FIRInstallations.installations' in your keychain." 

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

### PR DESCRIPTION
**Pull request by kamilpowalowski**
Fixes #8950, #6876

I'm working on the app that used Firebase Auth for authentication. I have an iOS app with iOS Share Extension and macOS app with macOS Share Extension.
By adding Keychain Access Group, I can use authenticated accounts between the main iOS app and iOS Share Extension. But the same code doesn't work on macOS.
When the app is installed on macOS or when I'm trying to access it from macOS Share Extension, I always get a prompt to keychain access. I started to dig, and I found the keychain parameter https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain
from its documentation, we can find

> use the data protection key when adding, searching for, or deleting an item to which the kSecAttrAccessible or **kSecAttrAccessGroup** attributes apply.

> It's highly recommended that you set the value of this key to true for all keychain operations. This key helps to improve the portability of your code across platforms.

It can be added to all platforms:

> The data protection key affects operations only in macOS. Other platforms automatically behave as if the key is set to true, and ignore the key in the query dictionary. You can safely use the key on all platforms.

`kSecUseDataProtectionKeychain` key is also mentioned in https://developer.apple.com/documentation/security/ksecattraccessgroup documentation

> This attribute applies to macOS keychain items only if you also set a value of true for the kSecUseDataProtectionKeychain key, the kSecAttrSynchronizable key, or both.

But I have to limit it a bit with `@available` parameter.

I took screenshot from keychain without that key (only main app listed)
Screen Shot 2021-12-15 at 13 15 43

and a screenshot from keychain after key added (KeychainGroup access instead is listed)
Screen Shot 2021-12-15 at 13 15 36

### CODE REVIEW

**Review by ncooke3 — COMMENTED** [review]
Thanks a lot for the investigation and contribution @kamilpowalowski! I've approved the CI workflows. 

Have you completed the [Google CLA](https://cla.developers.google.com/clas)?

**Comment by kamilpowalowski** [comment]
@ncooke3 No problem :) I need that for my own app so I was motivated.

Yes, I completed Google CLA yesterday.

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m [hunk 1]
```diff
@@ -81,6 +81,9 @@ - (FIRUser *)getStoredUserForAccessGroup:(NSString *)accessGroup
   query[(__bridge id)kSecAttrAccessGroup] = accessGroup;
   query[(__bridge id)kSecAttrService] = projectIdentifier;
   query[(__bridge id)kSecAttrAccount] = kSharedKeychainAccountValue;
+  if (@available(iOS 13.0, macOS 10.15, macCatalyst 13.0, tvOS 13.0, watchOS 6.0, *)) {
+    query[(__bridge id)kSecUseDataProtectionKeychain] = (__bridge id)kCFBooleanTrue;
+  }
```
Comment (ncooke3) [inline FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:86]: So IIUC: when the `kSecUseDataProtectionKeychain` is added to the query, the prompt on macOS is prevented. When it's not (i.e. we are on running on pre-macOS 10.15), the prompt will appear?

File: FirebaseAuth/CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,6 @@
 # Unreleased
 - [changed] Added a `X-Firebase-GMPID` header to network requests.
+- [fixed] macOS Extension access to Shared Keychain by adding kSecUseDataProtectionKeychain recommended key (#8950, #6876)
```
Comment (ncooke3) [inline FirebaseAuth/CHANGELOG.md:3]: Based on #8950's title, the keychain prompt was mentioning `com.firebase.FIRInstallations.installations`.

Could you confirm the bundle ID(s) mentioned in the keychain prompts you are seeing (without this fix)?

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m (hunk 1 above)
Comment (kamilpowalowski) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:86]: @ncooke3 yes. If macOS pre 10.15 don't behave differently, then on that system, after reinstall/update or when the account is checked from an extension there will be a keychain access prompt.

File: FirebaseAuth/CHANGELOG.md (hunk 2 above)
Comment (kamilpowalowski) [reply FirebaseAuth/CHANGELOG.md:3]: #8950 is a bit misleading because right now a keychain entry name is an API KEY, not a `com.firebase.FIRInstallations.installations`. Give me a few minutes, I'll find a commit that changed this.
So for me, a prompt was asking to access to `AlzaSy...` which is my app Firebase API KEY.

Comment (kamilpowalowski) [reply FirebaseAuth/CHANGELOG.md:3]: I found it https://github.com/firebase/firebase-ios-sdk/pull/5603. It was a critical PR. Otherwise, every macOS application with Firebase Auth tries to use the same keychain entry to store app auth information.

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m (hunk 1 above)
Comment (kamilpowalowski) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:86]: For <10.15 a working sulution may be to set `shareAuthStateAcrossDevices` to true. because [AccessGroup documentation](https://developer.apple.com/documentation/security/ksecattraccessgroup) says 

> This attribute applies to macOS keychain items only if you also set a value of true for the kSecUseDataProtectionKeychain key, the kSecAttrSynchronizable key, or both.

File: FirebaseAuth/CHANGELOG.md (hunk 2 above)
Comment (ncooke3) [reply FirebaseAuth/CHANGELOG.md:3]: I see- thanks! I was wondering because I think this PR's solution may be applied to other parts of Firebase that use the keychain. Again, great investigation!

Comment (kamilpowalowski) [reply FirebaseAuth/CHANGELOG.md:3]: You are right. It should be applied everywhere where `kSecAttrAccessGroup` is used, but `FIRAuthStoredUserManager` is the only place I found.

Comment (ncooke3) [inline FirebaseAuth/CHANGELOG.md:3]: Hi, could you remove the #8950 part from the changelog entry, please? Reason being is that this patch fixes Auth's keychain access but I believe we still need to investigate the root cause for the `com.firebase.FIRInstallations.installations`-related prompts, which may be a separate fix.

```suggestion
- [fixed] macOS Extension access to Shared Keychain by adding kSecUseDataProtectionKeychain recommended key (#6876)
```

**Review by ncooke3 — APPROVED** [review]
LGTM. I added one request below. Thanks again @kamilpowalowski!

File: FirebaseAuth/CHANGELOG.md (hunk 2 above)
Comment (kamilpowalowski) [reply FirebaseAuth/CHANGELOG.md]: Done, thank you.

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m [hunk 3]
```diff
@@ -81,6 +81,9 @@ - (FIRUser *)getStoredUserForAccessGroup:(NSString *)accessGroup
   query[(__bridge id)kSecAttrAccessGroup] = accessGroup;
   query[(__bridge id)kSecAttrService] = projectIdentifier;
   query[(__bridge id)kSecAttrAccount] = kSharedKeychainAccountValue;
+  if (@available(iOS 13.0, macOS 10.15, macCatalyst 13.0, tvOS 13.0, watchOS 6.0, *)) {
```
Comment (rosalyntan) [inline FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:84]: From the [docs](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain): "The data protection key affects operations only in macOS. Other platforms automatically behave as if the key is set to true, and ignore the key in the query dictionary. You can safely use the key on all platforms."

Do you mind adding a comment with this information wherever `kSecUseDataProtectionKeychain` is used?

**Review by rosalyntan — APPROVED** [review]
Thank you for the contribution! One minor comment, and there's a new merge conflict in the changelog that needs to be resolved before merging this, but otherwise LGTM!

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m (hunk 3 above)
Comment (kamilpowalowski) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:84]: @rosalyntan Will this be a problem if I did that (and rebase to resolve conflicts) beginning next week? Until that time, I only have access to the iPad, which is not a convenient tool for code editing and git operations.

Comment (paulb777) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m:84]: Thanks @kamilpowalowski It's fine to do next week. Our next release from master will be in January.

**Review by ncooke3 — APPROVED** [review]

File: FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m (hunk 3 above)
Comment (ncooke3) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m]: Thanks for the additional cleanup @kamilpowalowski!

Comment (rosalyntan) [reply FirebaseAuth/Sources/SystemService/FIRAuthStoredUserManager.m]: Thank you, @kamilpowalowski! LGTM.

**Comment by nidegen** [comment]
@kamilpowalowski do you have an idea by any chance if this would also fix a similar bug on tvOS?

**Comment by kamilpowalowski** [comment]
@nidegen, I don’t think so. It fixes a behavior related strictly to macOS. On macOS, you have access to the whole keychain. On other systems, you shouldn't have that problems. But (if possible) you should try to set `shareAuthStateAcrossDevices` to true. It may solve your problem.
