### PR TITLE
Fix an issue notification is not received during app first install

### LINKED ISSUE #6553: Background notifications not received on first open. Have to hard close and re-open app.
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7
  * Firebase SDK version: 6.33.0
  * Firebase Component: Messaging
  * Component version: 4.7.0
  * Installation method: CocoaPods
  * iOS: 13.7

### [REQUIRED] Step 2: Describe the problem

Background notifications not received on first app open. You have to hard close and re-open the app before they start working.

#### Steps to reproduce:

Install and deploy the iOS Messaging Quickstart app to TestFlight.

https://github.com/firebase/quickstart-ios/tree/master/messaging

The only change to the code I made was to copy the FCM token to the clipboard on tapping "Log Token"

This was my process:

- Built and deployed the iOS quick start app to TestFlight.
- Deleted any existing version of the iOS quick start app on my device.
- Restarted device
- Installed the app from TestFlight
- Allowed notifications and tapped "Log Token" to copy the FCM Token to my clipboard
- Backgrounded the app
- Sent a test message (with just title and notification text set to "Test") to the FCM Token via Firebase console
- No notification received.
- Force quit the app.
- Re-open the app.
- Background the app.
- Send another message via Firebase console to same FCM token
- Notification received

When testing the app without TestFlight and just running from Xcode to my device I experienced inconsistent results. Sometimes the notification is received on first install/open and other times I have to quit the app and re-open it. However, via TestFlight it seems to be consistently not working following the steps above (I've repeated them 10 times without seeing any difference).

Happy to help with any extra information I can. As a heads up, I'm afraid I know very little about native development! I came across from this issue on the react-native-firebase repo - https://github.com/invertase/react-native-firebase/issues/4299

### PR DESCRIPTION
**Pull request by chliangGoogle**
Fixes #6553.

There's a small chance the APNS token is returned from Apple with a delay so the first token request was sent without the apns token info. However, the retry logic didn't really trigger a second request, so fixed that.

### CODE REVIEW

File: Firebase/InstanceID/FIRInstanceID.m [hunk 1]
```diff
@@ -827,10 +827,27 @@ - (void)defaultTokenWithRetry:(BOOL)retry handler:(nullable FIRInstanceIDTokenHa
       if (!APNSRemainedSameDuringFetch && hasFirebaseMessaging) {
         // APNs value did change mid-fetch, so the token should be re-fetched with the current APNs
         // value.
-        [self retryGetDefaultTokenAfter:0];
+        [self.installations installationIDWithCompletion:^(NSString *_Nullable identifier,
```
Comment (maksymmalyhin) [inline Firebase/InstanceID/FIRInstanceID.m:830]: optional: May be worth refactoring to a separate method to improve readability.

**Review by maksymmalyhin — APPROVED** [review]
LGTM. It would be nice to add tests for the case, but I'm not too strong about it since we are replacing IID.

File: FirebaseMessaging/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,7 @@
 # unreleased -- v.7.0.0
 - [changed] Remove the deprecated FCM direct channel API and Upstream send API. (#6430)
 - [fixed] Fixed an issue that downloading an image failed when there's no extension in the file name but MIME type is set. (#6590)
+- [fixed] Fixed an issue that APNS token is not properly set sometimes when swizzling is disabled. (#6669)
```
Comment (paulb777) [inline FirebaseMessaging/CHANGELOG.md:4]: Use issue number 6553

**Review by paulb777 — APPROVED** [review]

File: Firebase/InstanceID/FIRInstanceID.m (hunk 1 above)
Comment (chliangGoogle) [reply Firebase/InstanceID/FIRInstanceID.m]: Done.

**Comment by ewfian** [comment]
Does this issue only occur in the case of disable swizzling?

**Comment by tomkelsey** [comment]
> Does this issue only occur in the case of disable swizzling?

This issue happened for me with swizzling enabled and this fix resolved it 👍

**Comment by ewfian** [comment]
@tomkelsey Thanks for confirm

@chliangGoogle The change log and the description of this pr said that `when swizzling is disabled `. So is it accurate here?

**Review by morganchen12 — APPROVED** [review]

**Comment by chliangGoogle** [comment]
@ewfian I guess not necessarily, it's just easier to reproduce for me when disable swizzling. But it should happen either way, the issue is when apple API returns the APNS token with a bit delay after the first token request is sent out.
I will update the comments. Thanks!

**Comment by tomkelsey** [comment]
@chliangGoogle Hey :)

I've noticed a crash impacting a number of users since integrating this PR into my project. It may just be coincidental but seems to relate to some of the code changed so thought I'd share here:

**Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010**

```
Crashed: com.apple.main-thread
0  App                  0x1048987d4 __96-[FIRInstanceIDTokenManager fetchNewTokenWithAuthorizedEntity:scope:instanceID:options:handler:]_block_invoke + 92 (FIRInstanceIDTokenManager.m:92)
1  libdispatch.dylib              0x1a0fb69a8 _dispatch_call_block_and_release + 24
2  libdispatch.dylib              0x1a0fb7524 _dispatch_client_callout + 16
3  libdispatch.dylib              0x1a0f695b4 _dispatch_main_queue_callback_4CF$VARIANT$mp + 904
4  CoreFoundation                 0x1a126f6bc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
5  CoreFoundation                 0x1a126a590 __CFRunLoopRun + 1724
6  CoreFoundation                 0x1a1269ba8 CFRunLoopRunSpecific + 424
7  GraphicsServices               0x1ab3e0344 GSEventRunModal + 160
8  UIKitCore                      0x1a53a53e4 UIApplicationMain + 1932
9  App                    0x10475de0c main + 7 (main.m:7)
10 libdyld.dylib                  0x1a10f18f0 start + 4
```

I may need some handholding if you need any more detailed logs - the above is what I was able to pull out of crashlytics.

Thanks again!

**Comment by chliangGoogle** [comment]
Is this only happening to the new version that you published with this PR?
Can you file a separate issue and assign back to me?

**Comment by morganchen12** [comment]
@chliangGoogle it's because handler is not checked for nil: https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:Firebase/InstanceID/FIRInstanceIDTokenManager.m;l=92?q=fetchNewTokenWithAuthorizedEntity:

**Comment by chliangGoogle** [comment]
@morganchen12 Thanks Morgan! I'm pulling out a fix for this right now.

**Comment by chliangGoogle** [comment]
@tomkelsey Thank you for the quick catch! no need to file an issue, the fix on the way.
