### PR TITLE
Fix fireperf exception

### LINKED ISSUE #12983: NSGenericException in `InstrumentUploadTaskWithStreamedRequest`
### Description

Description
- 
Similar to https://github.com/firebase/firebase-ios-sdk/issues/11821, our crash rate started to increase and the crash stack trace is pointing to this function `InstrumentUploadTaskWithStreamedRequest`.

Sample of our Crash Stacktrace
-
```
Fatal Exception: NSGenericException
0  CoreFoundation                 0xecb28 __exceptionPreprocess
1  libobjc.A.dylib                0x2af78 objc_exception_throw
2  CFNetwork                      0xdce4 _CFNetworkSetHSTSStoragePath
3  FirebasePerformance            0x18870 __InstrumentUploadTaskWithStreamedRequest_block_invoke + 486 (FPRNSURLSessionInstrument.m:486)
4  FirebasePerformance            0x18870 __InstrumentUploadTaskWithStreamedRequest_block_invoke + 486 (FPRNSURLSessionInstrument.m:486)
5  NewRelic                       0x38348 NRMAOverride__uploadTaskWithStreamedRequest + 355 (NRMAURLSessionOverride.m:355)
6  NewRelic                       0x530fc -[NRMAHexUploader handledErroredRequest:] + 141 (NRMAHexUploader.m:141)
7  NewRelic                       0x52cfc -[NRMAHexUploader URLSession:task:didCompleteWithError:] + 107 (NRMAHexUploader.m:107)
8  NewRelic                       0x353e8 -[NRURLSessionTaskDelegateBase URLSession:task:didCompleteWithError:] + 74 (NRMAURLSessionTaskDelegateBase.m:74)
9  FirebasePerformance            0x15eb4 __InstrumentURLSessionTaskDidCompleteWithError_block_invoke + 61 (FPRNSURLSessionDelegateInstrument.m:61)
10 CFNetwork                      0x1598c _CFNetworkSetHSTSStoragePath
11 libdispatch.dylib              0x213c _dispatch_call_block_and_release
12 libdispatch.dylib              0x3dd4 _dispatch_client_callout
13 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
14 libdispatch.dylib              0xbf64 _dispatch_lane_invoke
15 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
16 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x1f20 _pthread_wqthread
18 libsystem_pthread.dylib        0x1fc0 start_wqthread
```

### Reproducing the issue

_No response_

### Firebase SDK Version

10.24.0

### Xcode Version

15.3

### Installation Method

CocoaPods

### Firebase Product(s)

App Distribution, Crashlytics, Performance, Remote Config

### Targeted Platforms

iOS

### Relevant Log Output

_No response_

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

### PR DESCRIPTION
**Pull request by paulb777**
Fix #12983 

(Similar fix to #11825 and #11905)

### CODE REVIEW

File: FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m [hunk 1]
```diff
@@ -482,8 +482,15 @@ void InstrumentUploadTaskWithStreamedRequest(FPRNSURLSessionInstrument *instrume
...
       ThrowExceptionBecauseInstrumentHasBeenDeallocated(selector, instrumentor.instrumentedClass);
     }
-    typedef NSURLSessionUploadTask *(*OriginalImp)(id, SEL, NSURLRequest *);
-    NSURLSessionUploadTask *uploadTask = ((OriginalImp)currentIMP)(session, selector, request);
+    typedef NSURLSessionUploadTask *(*OriginalImp)(id, SEL, NSURLRequest *, NSData *);
+    // To avoid a runtime warning in Xcode 15, the given `URLRequest`
+    // should have a nil `HTTPBody`. To workaround this, the `HTTPBody` data is removed
+    // and requestData is replaced with it, if it bodyData was `nil`.
+    NSMutableURLRequest *requestWithoutHTTPBody = [request mutableCopy];
+    NSData *requestData = requestWithoutHTTPBody.HTTPBody;
```
Comment (visumickey) [inline FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:490]: I'm curious of scenrios where there is data already provided by the developer. Should we add an if condition to do this only when there is external request without any data?

Comment (paulb777) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:490]: Unlike the scenario in the function above, I don't see any other developer provided data in `InstrumentUploadTaskWithStreamedRequest` (or maybe I'm not following your question?)

Comment (visumickey) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:490]: In the request here, we are overwriting the parameter requestData (the 4th parameter) with what we get from the HTTPBody. I was worried about the scenario where the developers calls the UploadTask API with the requestData and we overwrite the value of requestData with the value we have in HTTPBody.

File: FirebasePerformance/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,6 @@
+# Unreleased
```
Comment (ncooke3) [inline FirebasePerformance/CHANGELOG.md:1]: I'm going to update the changelogs now. In case this makes it in before code freeze, I'm suggesting the correct changelog header.

```suggestion
# 10.27.0
```

File: FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m (hunk 1 above)
Comment (visumickey) [reply FirebasePerformance/Sources/Instrumentation/Network/FPRNSURLSessionInstrument.m:490]: After multiple investigation, I see that this is the best approach in resolving the issue. Apparently the extra parameter used is just for getting the upload task objet and so the extra parameter is not causing any issue. Marking the comment resolved and approving the PR.

**Review by visumickey — APPROVED** [review]
