### PR TITLE
Fix Firestore compilation under Xcode < 9.2

### LINKED ISSUE #1366: Firestore will not compile on Xcode 9.2 or earlier
Xcode 9.2 sees ambiguities in our `FormatArg` in `util/string_format.h` because `std::is_base_of<NSObject, T>{}` does not enable overloads that handle Objective-C types.

Xcode 8.3.3 sees static assertion failures in our specializations of `RankedInvokeHash` in `util/hashing.h` because `std::hash<T>` is defined for all `T`--it's just that it's an error to use the generic specialization of std::hash for anything that's not an enumeration type.

### PR DESCRIPTION
**Pull request by wilhuff**
A number of template-related errors have crept into the Firestore C++ codebase that happened to work in Xcode 9.3 and 9.4 but don't work on earlier versions.

Tested with Xcode 8.3.3 and 9.2.

Fixes #1366.

### CODE REVIEW

File: Firestore/core/src/firebase/firestore/util/type_traits.h [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+    return value;
+  }
+
+  constexpr bool operator()() const {
+    return value;
+  }
+};
+
+template <>
+struct is_objective_c_class<id> : public std::true_type {};
```
Comment (var-const) [inline Firestore/core/src/firebase/firestore/util/type_traits.h]: Why is this necessary in addition to `Choose(id)` overload?

File: Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+  static_assert(is_objective_c_class<NSObject>{}, "NSObject");
+  static_assert(is_objective_c_class<NSString>{}, "NSString");
+  static_assert(!is_objective_c_class<int>{}, "int");
+  static_assert(!is_objective_c_class<void>{}, "void");
+
+  struct Foo {};
+  static_assert(!is_objective_c_class<Foo>{}, "Foo");
+}
+
```
Comment (var-const) [inline Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm]: Optional: perhaps add a couple of tests to `has_std_hash`?

File: Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+#import <Foundation/NSString.h>
+
+#include "gtest/gtest.h"
+
+namespace firebase {
+namespace firestore {
+namespace util {
+
+TEST(TypeTraitsTest, IsObjectiveCClass) {
+  static_assert(is_objective_c_class<id>{}, "id");
```
Comment (var-const) [inline Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm]: Optional: add a test of `id<SomeProtocol>`?

File: Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+  static_assert(is_objective_c_class<NSObject>{}, "NSObject");
+  static_assert(is_objective_c_class<NSString>{}, "NSString");
+  static_assert(!is_objective_c_class<int>{}, "int");
+  static_assert(!is_objective_c_class<void>{}, "void");
```
Comment (var-const) [inline Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm]: Optional: add a test of pointer type.

File: Firestore/core/src/firebase/firestore/util/type_traits.h (hunk 1 above)
Comment (wilhuff) [reply Firestore/core/src/firebase/firestore/util/type_traits.h]: I added this because I wanted to be able to consider `id` to be an Objective-C type, but it didn't work naturally because even though `id` is a pointer type it does not match `T*` during overload resolution. 

Consider `T = NSString`:
  * `Instance()` returns `NSString*`
  * the compiler picks `Choose(id)` since Objective-C pointers are convertible to `id`.

Now consider `T = id`:
  * `Instance()` returns `id*` (a double-pointer)
  * the compiler picks `Choose(...)` since pointers to Objective-C pointers are not convertible to `id`.

However, your other feedback has prompted me to rethink this slightly: I generally don't care that the pointed-to thing is an Objective-C class, since instances are always referred to by pointer. What I actually care about is that the type of a given variable is a pointer to an Objective-C object.

Once examined through this lens, the trait that matters is `is_objective_c_pointer` and with a slight change in implementation this works naturally for `id` but no longer works correctly for `void`.

In any case, by naturally folding `id` into this pattern `id` no longer needs to be special cased in `StringFormat`'s constructors and so the `static_cast<id>` is no longer required for `id<Protocol>` references.

Thanks for pushing on this. I think the result is a great improvement.

File: Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm (hunk 3 above)
Comment (wilhuff) [reply Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm]: Done (for `id<NSCopying>`).

File: Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm (hunk 4 above)
Comment (wilhuff) [reply Firestore/core/test/firebase/firestore/util/type_traits_apple_test.mm]: Done.

File: Firestore/core/src/firebase/firestore/util/type_traits.h (hunk 1 above)
Comment (var-const) [reply Firestore/core/src/firebase/firestore/util/type_traits.h]: Thanks!

> the static_cast<id> is no longer required for id<Protocol> references.

Yes, this seems like a good feature.
