### PR TITLE
FirebaseOptions docs: Swift and Analytics exception

### LINKED ISSUE #9201: configuring Firebase using FirebaseOptions(googleAppID:gcmSenderID:) produces   "Could not locate configuration file" and "Google App ID from GoogleService-Info.plist is empty" warnings
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.2
  * Firebase SDK version: 8.10.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Analytiics
  * Target platform(s): `macOS`

### [REQUIRED] Step 2: Describe the problem

I configure `FirebaseApp` using `FirebaseOptions(googleAppID:gcmSenderID:)`:

```swift
        let fileopts = FirebaseOptions(googleAppID: "myAppID", gcmSenderID: "gcmSenderID")
        fileopts.apiKey = "myAPIKey"
        fileopts.projectID = "myProjectID"

        FirebaseCore.FirebaseApp.configure(options: fileopts)
```

 the following log is produced:

```
MyApp[44589:741323] 8.10.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
MyApp[44589:741321] 8.10.0 - [Firebase/Analytics][I-ACS020006] Google App ID from GoogleService-Info.plist is empty. Please, define GOOGLE_APP_ID in GoogleService-Info.plist for Analytics to work reliably. See https://goo.gl/txkZbE
MyApp[44589:741321] 8.10.0 - [Firebase/Analytics][I-ACS025020] Analytics requires Google App ID from GoogleService-Info.plist. Your data may be lost. Google App ID has been changed. Original, new ID: (nil), myAppIDxxxxxxxxxxxxx
MyApp[44589:741267] [Firebase/Crashlytics] Version 8.10.0
MyApp[44589:741325] [Metadata] unable to get a dev_t for store 1795162160.
MyApp[44589:741324] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
MyApp[44589:741324] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
MyApp[44589:741323] 8.10.0 - [Firebase/Analytics][I-ACS023007] Analytics v.8.10.0 started
```

I wouldn't expect Firebase to complain about locating its config file and reading values from it if I'm using `FirebaseOptions(googleAppID:gcmSenderID:)`

### PR DESCRIPTION
**Pull request by paulb777**
Fix #9201 

Clarify that FirebaseOptions APIs do not work for Analytics. Update rest of file to be Swifty.

#no-changelog

### CODE REVIEW

File: FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h [hunk 1]
```diff
@@ -99,25 +99,29 @@ NS_SWIFT_NAME(FirebaseOptions)
...
+ * Initializes a customized instance of FirebaseOptions from the file at the given plist file path.
+ * This will read the file synchronously from disk.
+ * For example:
+ * ```swift
+ *   if let path = Bundle.main.path(forResource:"GoogleServices-Info", ofType:"plist") {
+ *       let options = FirebaseOptions.init(contentsOfFile: path)
+ *   }
+ * ```
+ * Note that it is not possible to customize FirebaseOptions for Firebase Analytics which expects a
+ * static file named `GoogleServices-Info.plist`.
```
Comment (ryanwilson) [inline FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h:111]: Here and below can we add a reference to the issue?

**Comment by ryanwilson** [comment]
> 

cc @granluo to take a look at why the file specific diffs are so far off.

File: FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h [hunk 2]
```diff
@@ -99,25 +99,29 @@ NS_SWIFT_NAME(FirebaseOptions)
...
- * For example,
- * NSString *filePath =
- *     [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
- * FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
+ * Initializes a customized instance of FirebaseOptions from the file at the given plist file path.
+ * This will read the file synchronously from disk.
+ * For example:
+ * ```swift
+ *   if let path = Bundle.main.path(forResource:"GoogleServices-Info", ofType:"plist") {
+ *       let options = FirebaseOptions.init(contentsOfFile: path)
```
Comment (ryanwilson) [inline FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h:107]: Nit: prefer `FirebaseOptions(contentsOfFile: path)` instead of explicitly calling `.init`

**Review by ryanwilson — APPROVED** [review]

**Comment by granluo** [comment]
> cc @granluo to take a look at why the file specific diffs in the coverage report are so far off.

Some of tests send network call and this could cause a different coverage. One example is that different response codes in switch cases could have different coverages in the same test.
