### PR TITLE
Use new Google Utility for detecting whether to support background URL session uploads

### LINKED ISSUE #14793: `putFile` tries to perform background file uploads in app clip processes, which fails
### Description

As of now, you cannot upload a file using an App Clip. `putFile` needs to treat app clips the same as app extensions re: background uploads.

### Reproducing the issue

_No response_

### Firebase SDK Version

11.12

### Xcode Version

16.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell

```

### If using Swift Package Manager, the project's Package.resolved

_No response_

### If using CocoaPods, the project's Podfile.lock

_No response_

### PR DESCRIPTION
**Pull request by harlanhaskins**
This adopts a new GoogleUtilities API I am adding here: https://github.com/google/GoogleUtilities/pull/220

This will properly force App Clips to fall back to foreground uploads, since background uploads are not supported. Essentially, this expands the heuristic that was previously looking for app extensions.

Fixes #14793

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -149,8 +149,8 @@ let package = Package(
       "10.0.0" ..< "11.0.0"
     ),
     .package(
-      url: "https://github.com/google/GoogleUtilities.git",
```
Comment (harlanhaskins) [inline Package.swift:152]: I'll update this to use the proper GoogleUtilities tag once it's merged, tagged, and released.

**Comment by harlanhaskins** [comment]
cc @aerickson14 who hit this specific issue in his App Clip

File: Package.swift (hunk 1 above)
Comment (ncooke3) [reply Package.swift]: Hi @harlanhaskins, GoogleUtilities 8.1.0 has now been released

**Review by ncooke3 — APPROVED** [review]
Thanks for bumping the dependency versions!

**Comment by harlanhaskins** [comment]
It seems that crashlytics test might be flaky...

**Review by ncooke3 — APPROVED** [review]

**Comment by ncooke3** [comment]
Thanks!
