### PR TITLE
Fix token fetch not invoking callback for unchanged token

### LINKED ISSUE #3229: FIRInstanceID.instanceIDWithHandler() handler is not called if unregisterForRemoteNotifications() has previously been called more than once
* Xcode version: 10.2.1
  * Firebase SDK version: 6.2.0
  * Firebase Component: Messaging
  * Component version: 4.0.2

### [REQUIRED] Step 3: Describe the problem

The **instanceIDWithHandler()** method of FIRInstanceID docs say that the handler will always be called. However, seemingly if you have previously called your Application's **unregisterForRemoteNotifications()** twice, then the handler is never called.

This is happening in my application as I allow the user to enable/disable notifications from within the app, and if they turn them off and on a few times, the callback handler is never called and so things lock up.

[The docs](https://firebase.google.com/docs/cloud-messaging/ios/client#fetching-the-current-registration-token) say that you should be able to call this at any point to get the current token, rather than storing it yourself.
(The anchor link I have used doesn't seem to work - I am referring to the "*Fetching the current registration token*" section)

#### Steps to reproduce:

I've created a simple test project which shows the problem, which is attached.
[FirebaseMessagingTest.zip](https://github.com/firebase/firebase-ios-sdk/files/3310958/FirebaseMessagingTest.zip)

 * Add your own GoogleService-Info.plist, and change the Bundle Identifier accordingly.
 * Run ` pod install` to install the Firbase SDK via Cocoapods.
 * Run the app, with device attached, click the button to enable/disable notifications several times.
  * Watch the Output window in Xcode for log messages: Once it goes wrong, you'll see it starts fetching the token, but never finishes.

#### Relevant Code:

Alternatively, below is the code (minus the delegates):

```
class ViewController: UIViewController {
	
	typealias CompletionHandler = (_ success: Bool, _ error: Error?) -> Void
	
	private var mNotificationsEnabled = false

	override func viewDidLoad() {
		super.viewDidLoad()
		
		FirebaseApp.configure()
	}

	@IBAction func ButtonPressed(_ sender: UIButton) {
		mNotificationsEnabled = !mNotificationsEnabled
		let newTitle = mNotificationsEnabled ? "Disable Notifications" : "Enable Notifications"
		sender.setTitle(newTitle, for: .normal)
		sender.isEnabled = false
		
		setNotifications(enabled: mNotificationsEnabled, completionHandler: { (success, error) in
			sender.isEnabled = true
		})
	}
	
	func setNotifications(enabled: Bool, completionHandler: @escaping CompletionHandler) {
		if (enabled) {
			enableNotifications(completionHandler: {(success, error) in
				self.getToken(completionHandler)
			})
		}
		else {
			disableNotifications(completionHandler: completionHandler)
		}
	}
	
	func enableNotifications(completionHandler: @escaping CompletionHandler) {
		print("Enabling...")
		
		let notificationCenter = UNUserNotificationCenter.current()
		notificationCenter.requestAuthorization(options: [.alert, .sound, .badge], completionHandler: {(success, error) in
			if (success) {
				notificationCenter.delegate = self;
				Messaging.messaging().delegate = self
				
				DispatchQueue.main.async(execute: {
					UIApplication.shared.registerForRemoteNotifications() // Must run on main thread
					print("Notifications Enabled")
					completionHandler(success, error)
				})
				
			}
			else {
				print("Enabling failed")
				completionHandler(false, error)
			}
		})
	}
	
	func disableNotifications(completionHandler: @escaping CompletionHandler) {
		print("Disabling...")
		
		DispatchQueue.main.async(execute: {
			UIApplication.shared.unregisterForRemoteNotifications() // Must run on main thread
			print("Notifications Disabled")
			completionHandler(true, nil)
		})
	}
	
	func getToken(_ completionHandler: @escaping CompletionHandler) {
		print("Fetching Token...")
		
		//MARK: BUG? The following never calls its handler if invoked after unregisterForRemoteNotifications() has been called twice.
		InstanceID.instanceID().instanceID(handler: { (result, error) in
			if let error = error {
				print("Error fetching remote instance ID: \(error)")
				completionHandler(false, error)
			}
			else if let result = result {
				print("Token found")
				completionHandler(true, nil)
			}
		})
	}
	
}
```

### PR DESCRIPTION
**Pull request by morganchen12**
Fixes #3229.

### CODE REVIEW

File: Firebase/InstanceID/FIRInstanceID.m [hunk 1]
```diff
@@ -946,9 +946,9 @@ - (void)defaultTokenWithRetry:(BOOL)retry handler:(nullable FIRInstanceIDTokenHa
                                           object:[self.defaultFCMToken copy]];
         [[NSNotificationQueue defaultQueue] enqueueNotification:tokenRefreshNotification
                                                    postingStyle:NSPostASAP];
-
-        [self performDefaultTokenHandlerWithToken:token error:nil];
       }
+
+      [self performDefaultTokenHandlerWithToken:token error:nil];
```
Comment (chliangGoogle) [inline Firebase/InstanceID/FIRInstanceID.m]: aha I just realize this is a different issue that handler just simply doesn't get called. Thanks for fixing it!

**Comment by chliangGoogle** [comment]
@morganchen12 I might not be available in the next release, would you help paul on releasing the instanceID sdk with this change?

File: Example/InstanceID/Tests/FIRInstanceIDTest.m [hunk 2]
```diff
@@ -549,6 +549,76 @@ - (void)testDefaultToken_validCachedToken {
...
+                                 return obj != nil;
+                               }]];
+
+  __block NSInteger notificationPostCount = 0;
+  __block NSString *notificationToken = nil;
+
+  // Fetch token once to store token state
+  NSString *notificationName = kFIRInstanceIDTokenRefreshNotification;
+  self.tokenRefreshNotificationObserver = [[NSNotificationCenter defaultCenter]
+      addObserverForName:notificationName
```
Comment (maksymmalyhin) [inline Example/InstanceID/Tests/FIRInstanceIDTest.m]: Nit: This may be a bit nicer to express using `[self expectationForNotification:...]`, though probably no need to change since it is used in other tests as well.

**Comment by paulb777** [comment]
Please update https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/InstanceID/CHANGELOG.md with this fix.

File: Firebase/InstanceID/FIRInstanceID.m (hunk 1 above)
Comment (morganchen12) [reply Firebase/InstanceID/FIRInstanceID.m]: No problem!

File: Example/InstanceID/Tests/FIRInstanceIDTest.m (hunk 2 above)
Comment (morganchen12) [reply Example/InstanceID/Tests/FIRInstanceIDTest.m]: Keeping it this way for consistency (and laziness...) 

@chliangGoogle FYI

**Comment by morganchen12** [comment]
Updated changelog.

File: Firebase/InstanceID/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,6 @@
+# Unreleased
+- Fixed an issue where fetching an instance ID wouldn't invoke the callback handler if the instance ID had not changed. (#3251)
```
Comment (paulb777) [inline Firebase/InstanceID/CHANGELOG.md]: Issue number is preferable to PR when it exists.

Comment (paulb777) [reply Firebase/InstanceID/CHANGELOG.md]: Mark this is as 4.2.1 since today is code freeze and this will be the one fix for 4.2.1.

Comment (morganchen12) [reply Firebase/InstanceID/CHANGELOG.md]: Done; left the date TBA.

**Comment by paulb777** [comment]
Thanks! We should remove dates from these CHANGELOG's, but that is for another PR.
